/**
 * exportNavigatorLayer — convert CortexSim's MITRE coverage into a
 * MITRE ATT&CK Navigator v4.5 layer JSON.
 *
 * The exported file can be uploaded to the public Navigator
 * (https://mitre-attack.github.io/attack-navigator/) for executive
 * briefings. Each technique cell renders with a color reflecting
 * CortexSim's coverage state.
 *
 * Layer format spec:
 *   https://github.com/mitre-attack/attack-navigator/blob/master/layers/spec/v4.5/LAYERFORMAT.md
 *
 * Coverage state → color:
 *   detected         → #4FD1A1 (teal-green, score 100) — observed by Cortex
 *   run_not_detected → #F5A524 (amber,      score  60) — run but no signal
 *   not_run          → #5A6B84 (muted blue, score  30) — scenario exists, not run
 *   no_scenario      → unset / not in layer
 */

const STATUS_TO_COLOR = {
  detected:         { color: '#4FD1A1', score: 100 },
  run_not_detected: { color: '#F5A524', score:  60 },
  not_run:          { color: '#5A6B84', score:  30 },
}

/**
 * Build the layer JSON object for the given coverage payload.
 *
 * @param {object} coverage  — what `useMitreCoverage().data` returns
 * @param {object} options   — { name, description, version }
 * @returns {object} Navigator v4.5 layer
 */
export function buildLayer(coverage, options = {}) {
  if (!coverage || !coverage.by_tactic) {
    return emptyLayer(options)
  }

  const techniques = []
  for (const tactic of coverage.by_tactic) {
    for (const t of tactic.techniques) {
      const styling = STATUS_TO_COLOR[t.status]
      if (!styling) continue  // no_scenario → skip; cell stays uncolored
      const cell = {
        techniqueID: t.technique_id,
        tactic: tacticDisplayName(tactic.tactic_id),
        score: styling.score,
        color: styling.color,
        comment: buildComment(t),
        enabled: true,
      }
      techniques.push(cell)
    }
  }

  return {
    name: options.name || 'CortexSim Coverage',
    versions: {
      attack: '15',
      navigator: '5.0.1',
      layer: '4.5',
    },
    domain: 'enterprise-attack',
    description: options.description ||
      'Auto-generated by CortexSim. Shows MITRE ATT&CK technique coverage ' +
      'across the loaded scenario library. Color-coded by detection state ' +
      '(detected / run with no detection / scenario staged).',
    filters: { platforms: [
      'Linux', 'macOS', 'Windows', 'Network', 'PRE', 'Containers',
      'Office 365', 'SaaS', 'Google Workspace', 'IaaS', 'Azure AD',
    ] },
    sorting: 0,
    layout: {
      layout: 'side',
      aggregateFunction: 'average',
      showID: false,
      showName: true,
      showAggregateScores: true,
      countUnscored: false,
    },
    hideDisabled: false,
    techniques,
    gradient: {
      colors: ['#5A6B84', '#F5A524', '#4FD1A1'],
      minValue: 0,
      maxValue: 100,
    },
    legendItems: [
      { label: 'Detected (Cortex)',           color: '#4FD1A1' },
      { label: 'Run · no detection',          color: '#F5A524' },
      { label: 'Scenario staged · not run',   color: '#5A6B84' },
    ],
    metadata: [
      { name: 'generator', value: 'CortexSim' },
      { name: 'exported_at', value: new Date().toISOString() },
      { name: 'scenario_count', value: String(coverage.summary?.total_techniques || 0) },
    ],
    showTacticRowBackground: false,
    tacticRowBackground: '#101A28',
    selectTechniquesAcrossTactics: true,
    selectSubtechniquesWithParent: false,
  }
}

/**
 * Trigger a browser download of the layer JSON.
 *
 * Returns the filename used so callers can surface it in a toast.
 */
export function downloadLayer(coverage, options = {}) {
  const layer = buildLayer(coverage, options)
  const ts = new Date().toISOString().replace(/[-:]/g, '').slice(0, 15)
  const filename = options.filename || `cortexsim-attack-navigator-${ts}.json`
  const blob = new Blob([JSON.stringify(layer, null, 2)], {
    type: 'application/json',
  })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
  return filename
}

/* ─── helpers ─────────────────────────────────────────────────────── */

function buildComment(t) {
  const lines = []
  if (t.scenarios && t.scenarios.length > 0) {
    lines.push(`Scenarios: ${t.scenarios.join(', ')}`)
  }
  if (typeof t.observed_detections === 'number') {
    lines.push(`Detections: ${t.observed_detections}/${t.total_detections}`)
  }
  if (t.planes && t.planes.length > 0) {
    lines.push(`Planes: ${t.planes.join(', ')}`)
  }
  return lines.join('\n')
}

// ATT&CK tactic IDs to the lowercase-with-hyphens "shortname" Navigator
// uses for filtering. Manual mapping — the Navigator's v4.5 schema
// expects the shortname, not the TAxxxx id.
const TACTIC_SHORTNAMES = {
  TA0043: 'reconnaissance',
  TA0042: 'resource-development',
  TA0001: 'initial-access',
  TA0002: 'execution',
  TA0003: 'persistence',
  TA0004: 'privilege-escalation',
  TA0005: 'defense-evasion',
  TA0006: 'credential-access',
  TA0007: 'discovery',
  TA0008: 'lateral-movement',
  TA0009: 'collection',
  TA0011: 'command-and-control',
  TA0010: 'exfiltration',
  TA0040: 'impact',
}

function tacticDisplayName(tacticId) {
  return TACTIC_SHORTNAMES[tacticId] || (tacticId || '').toLowerCase()
}

function emptyLayer(options) {
  return {
    name: options.name || 'CortexSim Coverage (empty)',
    versions: { attack: '15', navigator: '5.0.1', layer: '4.5' },
    domain: 'enterprise-attack',
    description: 'No coverage data available.',
    techniques: [],
    sorting: 0,
    hideDisabled: false,
  }
}

/* ─── Single-TTP layer export ──────────────────────────────────────── */

/**
 * Build a Navigator v4.5 layer scoped to a single TTP card. Each
 * technique the card maps gets a teal cell annotated with the TTP id,
 * name, and tactic. This is the "paste into the customer's Navigator
 * to show exactly what this one detection covers" artifact — the
 * focused counterpart to the library-wide `buildLayer`.
 *
 * @param {object} detail  — the /api/ttps/:id payload (raw TTP JSON)
 * @returns {object} Navigator v4.5 layer
 */
export function buildTtpLayer(detail) {
  const mitre = (detail && detail.mitre_attack) || {}
  const rawTechniques = mitre.techniques || []
  const ttpId = (detail && detail.id) || 'TTP'
  const ttpName = (detail && detail.identity && detail.identity.name) || ttpId

  const techniques = []
  for (const t of rawTechniques) {
    if (!t || typeof t !== 'object') continue
    // Navigator keys cells on the most-specific technique id available.
    const techniqueID = t.subtechnique_id || t.technique_id
    if (!techniqueID) continue
    const tacticIds = t.tactic_ids || []
    const comment = [
      `${ttpId} — ${ttpName}`,
      t.name ? `Technique: ${t.name}` : null,
    ].filter(Boolean).join('\n')

    if (tacticIds.length === 0) {
      // No tactic context — emit a single untargeted cell.
      techniques.push({
        techniqueID,
        score: 100,
        color: '#00C0E8',
        comment,
        enabled: true,
      })
      continue
    }
    // One cell per (technique, tactic) pair so the cell lands in every
    // column the technique belongs to — matches Navigator semantics.
    for (const tid of tacticIds) {
      techniques.push({
        techniqueID,
        tactic: tacticDisplayName(tid),
        score: 100,
        color: '#00C0E8',
        comment,
        enabled: true,
      })
    }
  }

  return {
    name: `${ttpId} — ${ttpName}`,
    versions: { attack: '15', navigator: '5.0.1', layer: '4.5' },
    domain: 'enterprise-attack',
    description:
      `CortexSim ATT&CK Navigator layer for ${ttpId} (${ttpName}). ` +
      `Highlights the technique(s) this detection card covers. ` +
      `Generated ${new Date().toISOString()}.`,
    sorting: 0,
    layout: {
      layout: 'side',
      showID: true,
      showName: true,
    },
    hideDisabled: false,
    techniques,
    legendItems: [
      { label: `Covered by ${ttpId}`, color: '#00C0E8' },
    ],
    metadata: [
      { name: 'generator', value: 'CortexSim' },
      { name: 'ttp_id', value: ttpId },
      { name: 'exported_at', value: new Date().toISOString() },
    ],
    selectTechniquesAcrossTactics: true,
    selectSubtechniquesWithParent: false,
  }
}

/**
 * Trigger a browser download of a single-TTP Navigator layer.
 * Returns the filename used so callers can surface it in a toast.
 */
export function downloadTtpLayer(detail, options = {}) {
  const layer = buildTtpLayer(detail)
  const ttpId = (detail && detail.id) || 'ttp'
  const filename = options.filename || `cortexsim-${ttpId.toLowerCase()}-navigator.json`
  const blob = new Blob([JSON.stringify(layer, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
  return filename
}
