#!/usr/bin/env python3
"""PostToolUse hook — validate the detection corpus after edits.

Fires on Edit/Write/MultiEdit. When the edited file is a scenario YAML, a TTP
card, or a tool-adapter pack, run the matching gate so corpus-breaking changes
surface at edit time instead of at SimCore boot or in CI.

  - scenarios/**/*.yml
        → .claude/hooks/lint-scenario.py                   (loader-contract lint;
          the boot loader needs SQLAlchemy/Py3.11, unavailable on the host)
  - detection_scanner/ttps/*.json
        → detection_scanner/scripts/validate.py --quiet     (CI 'detection' job)
  - tools/packs/*.yml
        → scripts/check-adapter-sources.sh                  (CI 'adapters' job)

TTP edits additionally regenerate detection_scanner/exports/ (idempotent) so the
export-determinism gate stays green; the hook reports back if exports changed.

Exit codes:
  0  — not a corpus file, or validation passed
  2  — validation failed; stderr is fed back to Claude
"""
import json
import os
import subprocess
import sys
from pathlib import Path


def _run(cmd, cwd, env):
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, env=env)


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0

    file_path = payload.get("tool_input", {}).get("file_path", "")
    if not file_path:
        return 0

    project_dir = Path(
        os.environ.get("CLAUDE_PROJECT_DIR", payload.get("cwd", "."))
    ).resolve()
    try:
        rel = Path(file_path).resolve().relative_to(project_dir)
    except ValueError:
        return 0  # edit outside the repo — not our concern
    rel_str = str(rel)

    # Mirror the loader's _find_yaml_files: only *.yml under scenarios/, skip
    # _schema.yml, and prune the non-scenario sub-trees (probes/, packages/,
    # campaigns/) that hold prompt-attacker probes, packaged supporting YAML,
    # and browser campaigns — the loader never treats those as scenarios.
    _LOADER_SKIP_DIRS = {"probes", "packages", "campaigns"}
    is_scenario = (
        rel_str.startswith("scenarios/")
        and rel.suffix == ".yml"
        and rel.name != "_schema.yml"
        and _LOADER_SKIP_DIRS.isdisjoint(rel.parts)
    )
    is_ttp = rel_str.startswith("detection_scanner/ttps/") and rel.suffix == ".json"
    is_adapter = rel_str.startswith("tools/packs/") and rel.suffix in {".yml", ".yaml"}

    checks = []
    if is_scenario:
        checks.append(
            (["python3", str(project_dir / ".claude" / "hooks" / "lint-scenario.py"),
              str(Path(file_path).resolve()), str(project_dir)],
             "scenario schema lint")
        )
    if is_ttp:
        checks.append(
            (["python3", "detection_scanner/scripts/validate.py", "--quiet"],
             "detection-corpus validator")
        )
    if is_adapter:
        checks.append((["scripts/check-adapter-sources.sh"], "adapter-source preflight"))

    if not checks:
        return 0

    env = {**os.environ, "CORTEXSIM_BASE_DIR": str(project_dir)}

    failures = []
    for cmd, label in checks:
        proc = _run(cmd, project_dir, env)
        if proc.returncode != 0:
            out = (proc.stdout + proc.stderr).strip()
            failures.append(f"[{label}] FAILED:\n{out}")

    if failures:
        print(
            f"Corpus validation failed after editing {rel_str}:\n\n"
            + "\n\n".join(failures)
            + "\n\nFix the reported errors before continuing.",
            file=sys.stderr,
        )
        return 2

    # TTP card changed → keep the deterministic exports in sync (idempotent).
    if is_ttp:
        _run(["python3", "detection_scanner/scripts/export_artifacts.py"],
             project_dir, env)
        diff = _run(["git", "diff", "--name-only", "detection_scanner/exports/"],
                    project_dir, env)
        if diff.stdout.strip():
            print(json.dumps({
                "hookSpecificOutput": {
                    "hookEventName": "PostToolUse",
                    "additionalContext": (
                        "detection_scanner/exports/ was regenerated by "
                        "export_artifacts.py after this TTP edit. Stage the "
                        "regenerated exports alongside the card change so the "
                        "export-determinism CI gate (git diff --exit-code) stays green."
                    ),
                }
            }))

    return 0


if __name__ == "__main__":
    sys.exit(main())
