apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eal-simulator.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eal-simulator.labels" . | nindent 4 }}
data:
  CORTEXSIM_ENV: {{ .Values.api.env.CORTEXSIM_ENV | quote }}
  CORTEXSIM_PORT: {{ .Values.api.env.CORTEXSIM_PORT | quote }}
  CORTEXSIM_BIND_ADDRESS: {{ .Values.api.bindAddress | quote }}
  EAL_AUDIT_STDOUT: {{ .Values.audit.stdout | quote }}
  EAL_AUDIT_FILE_ENABLED: {{ .Values.audit.file.enabled | quote }}
  EAL_AUDIT_FILE_PATH: {{ .Values.audit.file.path | quote }}
{{- if .Values.redis.enabled }}
  EAL_REDIS_URL: "redis://{{ include "eal-simulator.fullname" . }}-redis:6379/0"
{{- end }}
