#!/usr/bin/env bash
# ==============================================================================
# publish-agent.sh — build the beacon for the lab and publish a one-line installer.
#
# Run this ON THE CONTROL PLANE (the machine running SimCore). It:
#   1. Cross-compiles the Go beacon for linux/amd64 + linux/arm64 (CGO_ENABLED=0,
#      stdlib-only → a static ELF that runs on any glibc/musl victim, no Go needed
#      on the target).
#   2. Generates `enroll.sh` with the control-plane URL BAKED IN — the fix for the
#      "can't phone home" failure, where an installer fetched over localhost bakes
#      SERVER=http://localhost:8888 and the victim then dials itself.
#   3. Publishes all three under dist/agent/, which SimCore serves at /agent/.
#
# Then each victim is one line, with no Go and no scp:
#
#   curl -fsSL http://<cp>:8888/agent/enroll.sh | CORTEXSIM_TOKEN=cxs_… bash
#
# Usage:
#   scripts/lab/publish-agent.sh                        # auto-detect LAN IP
#   scripts/lab/publish-agent.sh --server http://192.168.1.50:8888
#   scripts/lab/publish-agent.sh --token cxs_…          # bake a default token too
# ==============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." >/dev/null 2>&1 && pwd)"
cd "${REPO_ROOT}"

SERVER=""
TOKEN=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --server) SERVER="$2"; shift 2 ;;
    --token)  TOKEN="$2";  shift 2 ;;
    -h|--help) sed -n '2,25p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) printf 'unknown flag: %s\n' "$1" >&2; exit 2 ;;
  esac
done

log() { printf '\033[0;36m[publish-agent]\033[0m %s\n' "$*"; }
err() { printf '\033[0;31m[publish-agent] ERROR:\033[0m %s\n' "$*" >&2; }

# ---------------------------------------------------------------------------
# 1. Resolve the control-plane URL victims will dial.
#    NEVER localhost/127.0.0.1 — on a victim that resolves to the victim itself,
#    which is exactly the phone-home failure this script exists to prevent.
# ---------------------------------------------------------------------------
PORT="$(sed -n 's/^CORTEXSIM_PORT=\([0-9][0-9]*\).*/\1/p' "${REPO_ROOT}/.env" 2>/dev/null | head -n1)"
PORT="${PORT:-8888}"

detect_ip() {
  # macOS (control plane is typically the MBP), then Linux, then hostname -I.
  if command -v ipconfig >/dev/null 2>&1; then
    for iface in en0 en1; do
      ip="$(ipconfig getifaddr "$iface" 2>/dev/null || true)"
      [[ -n "$ip" ]] && { printf '%s' "$ip"; return; }
    done
  fi
  if command -v ip >/dev/null 2>&1; then
    ip route get 1.1.1.1 2>/dev/null | sed -n 's/.*src \([0-9.]*\).*/\1/p' | head -n1 && return
  fi
  hostname -I 2>/dev/null | awk '{print $1}'
}

if [[ -z "${SERVER}" ]]; then
  IP="$(detect_ip || true)"
  [[ -n "${IP}" ]] || { err "Could not auto-detect a LAN IP. Pass --server http://<ip>:${PORT}"; exit 1; }
  SERVER="http://${IP}:${PORT}"
  log "Auto-detected control plane: ${SERVER}"
fi

case "${SERVER}" in
  *localhost*|*127.0.0.1*)
    err "Refusing to bake ${SERVER}: on a victim that points at the victim itself."
    err "Pass the control plane's LAN address, e.g. --server http://192.168.1.50:${PORT}"
    exit 1 ;;
esac

# ---------------------------------------------------------------------------
# 2. Cross-compile. Stdlib-only + CGO_ENABLED=0 → portable static ELF.
# ---------------------------------------------------------------------------
command -v go >/dev/null 2>&1 || { err "Go 1.21+ required on the control plane to build the beacon."; exit 1; }

OUT="${REPO_ROOT}/dist/agent"
mkdir -p "${OUT}"

for arch in amd64 arm64; do
  log "Building linux/${arch} …"
  ( cd "${REPO_ROOT}/agent" && CGO_ENABLED=0 GOOS=linux GOARCH="${arch}" \
      go build -trimpath -o "${OUT}/cortexsim-agent-${arch}" . )
done

# ---------------------------------------------------------------------------
# 3. Generate the victim-side installer with SERVER (and optionally TOKEN) baked.
# ---------------------------------------------------------------------------
cat > "${OUT}/enroll.sh" <<ENROLL
#!/usr/bin/env bash
# CortexSim victim enrollment — generated by scripts/lab/publish-agent.sh.
# No Go, no scp: downloads a static beacon, enrolls for a server-assigned id,
# and installs a systemd unit when it can.
#
#   curl -fsSL ${SERVER}/agent/enroll.sh | CORTEXSIM_TOKEN=cxs_… bash
set -euo pipefail

SERVER="\${CORTEXSIM_SERVER:-${SERVER}}"
TOKEN="\${CORTEXSIM_TOKEN:-${TOKEN}}"
INTERVAL="\${CORTEXSIM_INTERVAL:-10}"

say() { printf '[cortexsim] %s\n' "\$*"; }
die() { printf '[cortexsim] ERROR: %s\n' "\$*" >&2; exit 1; }

[ -n "\${TOKEN}" ] || die "No enrollment token. Mint one on the control plane:
  curl -s -X POST \${SERVER}/api/agents/enroll/tokens -H 'Content-Type: application/json' \\\\
    -d '{\"label\":\"lab-victims\",\"ttl_seconds\":86400,\"max_uses\":25}'
then re-run with CORTEXSIM_TOKEN=cxs_…"

# --- reachability preflight: fail loudly HERE, not silently in the beacon loop
say "control plane : \${SERVER}"
curl -fsS --max-time 5 "\${SERVER}/api/health" >/dev/null 2>&1 \\
  || die "cannot reach \${SERVER}/api/health from \$(hostname).
  - is SimCore up on the control plane?
  - is the control-plane firewall allowing inbound \${SERVER##*:}?  (macOS blocks by default)
  - can this host route to it?   curl -v \${SERVER}/api/health"

# --- architecture
case "\$(uname -m)" in
  x86_64|amd64) ARCH=amd64 ;;
  aarch64|arm64) ARCH=arm64 ;;
  *) die "unsupported architecture: \$(uname -m)" ;;
esac

BIN_DIR=/usr/local/bin
[ -w "\${BIN_DIR}" ] 2>/dev/null || BIN_DIR="\${HOME}/.local/bin"
mkdir -p "\${BIN_DIR}"
BIN="\${BIN_DIR}/cortexsim-agent"

say "downloading beacon (linux/\${ARCH}) …"
curl -fsSL "\${SERVER}/agent/cortexsim-agent-\${ARCH}" -o "\${BIN}" \\
  || die "download failed: \${SERVER}/agent/cortexsim-agent-\${ARCH}"
chmod +x "\${BIN}"

# --- enroll: SimCore assigns the id; we never invent one
say "enrolling …"
RESP="\$(curl -fsSL -X POST "\${SERVER}/api/agents/enroll" \\
  -H 'Content-Type: application/json' \\
  -d "{\\"token\\":\\"\${TOKEN}\\",\\"hostname\\":\\"\$(hostname)\\",\\"os\\":\\"linux\\"}")" \\
  || die "enrollment rejected — token invalid, expired, revoked, or out of uses"

AGENT_ID="\$(printf '%s' "\${RESP}" | sed -n 's/.*"agent_id":[[:space:]]*"\\([^"]*\\)".*/\\1/p')"
[ -n "\${AGENT_ID}" ] || die "no agent_id in enroll response: \${RESP}"
say "enrolled as: \${AGENT_ID}"

# --- run: systemd when we can (survives reboot), else foreground
# /run/systemd/system is the canonical "systemd is PID 1" test. A systemctl
# binary alone is not enough — containers and WSL ship one that cannot
# reach a bus, and blindly calling it aborts the install under set -e.
if [ "\$(id -u)" = "0" ] && [ -d /run/systemd/system ] && command -v systemctl >/dev/null 2>&1; then
  cat > /etc/systemd/system/cortexsim-agent.service <<UNIT
[Unit]
Description=CortexSim beacon agent
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=\${BIN} --server \${SERVER} --id \${AGENT_ID} --interval \${INTERVAL}
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT
  if systemctl daemon-reload 2>/dev/null && systemctl enable --now cortexsim-agent 2>/dev/null; then
    say "installed + started systemd unit: cortexsim-agent"
    say "logs: journalctl -u cortexsim-agent -f"
  else
    say "systemd present but unusable — falling back to foreground"
    rm -f /etc/systemd/system/cortexsim-agent.service
    exec "\${BIN}" --server "\${SERVER}" --id "\${AGENT_ID}" --interval "\${INTERVAL}"
  fi
else
  say "no systemd/root — running in foreground (Ctrl-C to stop)"
  exec "\${BIN}" --server "\${SERVER}" --id "\${AGENT_ID}" --interval "\${INTERVAL}"
fi
ENROLL
chmod +x "${OUT}/enroll.sh"

# ---------------------------------------------------------------------------
# 4. Publish into the static mount for native mode. Docker mode picks the same
#    dist/agent up via the read-only bind mount in docker-compose.yml.
# ---------------------------------------------------------------------------
if [[ -d "${REPO_ROOT}/core/static" ]]; then
  mkdir -p "${REPO_ROOT}/core/static/agent"
  cp "${OUT}/cortexsim-agent-amd64" "${OUT}/cortexsim-agent-arm64" "${OUT}/enroll.sh" \
     "${REPO_ROOT}/core/static/agent/"
  log "Published into core/static/agent/ (native mode)."
  log "NOTE: a UI rebuild replaces core/static — re-run this script afterwards."
else
  log "core/static not present (Docker-only mode) — serving from the dist/agent bind mount."
fi

printf '\n  \033[0;32m✓ Beacon published.\033[0m  Enroll each victim with one line:\n\n'
if [[ -n "${TOKEN}" ]]; then
  printf '    curl -fsSL %s/agent/enroll.sh | bash\n\n' "${SERVER}"
else
  printf '    curl -fsSL %s/agent/enroll.sh | CORTEXSIM_TOKEN=cxs_… bash\n\n' "${SERVER}"
  printf '  Mint the token first:\n'
  printf "    curl -s -X POST %s/api/agents/enroll/tokens -H 'Content-Type: application/json' \\\\\n" "${SERVER}"
  printf '      -d '"'"'{"label":"lab-victims","ttl_seconds":86400,"max_uses":25}'"'"'\n\n'
fi
