"""
core/engine/efficacy_scorecard.py — POV efficacy scorecard.

Computes a Cortex-branded *efficacy scorecard* from one **or many** runs'
``Result`` rows. The scorecard is the CISO/exec one-pager companion to the
per-detection POV report generated by ``core/api/runs.py`` + the artifact set
in ``core/engine/report_generator.py``:

  * overall detection coverage % (detected / expected)
  * detected / missed / pending counts
  * MTTD distribution — min / median / p90 / max
  * coverage broken down **by plane**, **by detection_type**
    (``BIOC | XQL | Analytics | Correlation | IOC | ABIOC``), and **by Cortex
    product** (EDR → Cortex XDR, CDR → Cortex Cloud, …)

Design mirrors ``report_generator.py`` exactly:

  * **pure** — consumes only ``Result.to_dict()``-shaped dicts (the shape
    already emitted by ``core/models.py``); imports no ORM/session/FastAPI.
  * **frozen dataclasses** with ``.to_dict()`` so the API layer can serialize.
  * status derivation matches ``report_generator._status_from_result`` so the
    scorecard and the detection matrix never disagree.

Bolts onto the existing report export via a ``?format=scorecard`` branch on
``GET /api/runs/{id}/report`` (see the integration patch in the handoff).
"""

from __future__ import annotations

import dataclasses
import html
import logging
from datetime import datetime, timezone
from typing import Any, Iterable, Optional


logger = logging.getLogger("cortexsim.engine.efficacy_scorecard")


# ---------------------------------------------------------------------------
# Cortex vocabulary + product mapping
# ---------------------------------------------------------------------------

# The full six-value detection_type vocabulary. Anything that does not
# normalize into one of these buckets is surfaced under ``Other`` so the
# scorecard never silently drops a signal type.
DETECTION_TYPES: tuple[str, ...] = (
    "BIOC", "XQL", "Analytics", "Correlation", "IOC", "ABIOC",
)

# Plane → customer-facing Cortex product. Lower-cased plane keys (planes ship
# as lower-case module names — ``edr``, ``cdr``, …) so lookups are
# case-insensitive. Unmapped planes fall back to ``Cortex XSIAM`` (the SIEM
# substrate every plane ultimately lands in).
PLANE_TO_PRODUCT: dict[str, str] = {
    "edr": "Cortex XDR",
    "koi": "Cortex XDR",
    "cdr": "Cortex Cloud",
    "cspm": "Cortex Cloud",
    "cloud_app": "Cortex Cloud",
    "ndr": "Cortex XSIAM",
    "itdr": "Cortex XSIAM",
    "analytics": "Cortex XSIAM",
    "tim": "Cortex XSIAM",
    "email": "Cortex XSIAM",
    "asm": "Cortex ASM",
    "airs": "Cortex AIRS",
    "ai_access": "Cortex AI Access Security",
    "ai_spm": "Cortex AI-SPM",
    "browser": "Prisma Browser",
}
_DEFAULT_PRODUCT = "Cortex XSIAM"

# Cortex design tokens (mirrors ui/src/styles/cortex-theme.css).
_CORTEX_NAVY = "#003366"
_CORTEX_TEAL = "#00C0E8"
_CORTEX_STEEL = "#6B7E8E"
_DETECTED_GREEN = "#1f9d55"
_MISSED_RED = "#e60d0d"
_PENDING_AMBER = "#c98a00"


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class CoverageStats:
    detected: int
    missed: int
    pending: int
    expected: int
    pct: float

    def to_dict(self) -> dict[str, Any]:
        return dataclasses.asdict(self)


@dataclasses.dataclass(frozen=True)
class MttdDistribution:
    count: int
    min_seconds: Optional[float]
    median_seconds: Optional[float]
    p90_seconds: Optional[float]
    max_seconds: Optional[float]

    def to_dict(self) -> dict[str, Any]:
        return dataclasses.asdict(self)


@dataclasses.dataclass(frozen=True)
class BreakdownRow:
    """One coverage row for a plane / detection_type / product breakdown."""

    label: str
    detected: int
    missed: int
    pending: int
    expected: int
    pct: float

    def to_dict(self) -> dict[str, Any]:
        return dataclasses.asdict(self)


@dataclasses.dataclass(frozen=True)
class VerdictTally:
    """How many runs actually MET their bound test case's bar.

    Coverage answers "how much of what we expected did we see". It does not
    answer "did the test case pass", which is the question a POV readout turns
    on — and the two diverge: a run can observe every seeded detection and still
    miss its MTTD threshold. ``not_applicable`` is carried explicitly rather
    than folded into a pass rate, because a test case the index gave no
    measurable threshold can never be certified and saying so is the point.
    """

    passed: int = 0
    failed: int = 0
    pending: int = 0
    not_applicable: int = 0
    unscored: int = 0            # no verdict recorded at all

    @property
    def scored(self) -> int:
        return self.passed + self.failed

    @property
    def pass_pct(self) -> Optional[float]:
        """Share of SCOREABLE runs that passed. None when nothing was scoreable
        — a 0% that really means "nothing could be scored" misleads a reader."""
        return round(self.passed / self.scored * 100, 1) if self.scored else None

    def to_dict(self) -> dict[str, Any]:
        return {
            "passed": self.passed, "failed": self.failed,
            "pending": self.pending, "not_applicable": self.not_applicable,
            "unscored": self.unscored,
            "scored": self.scored, "pass_pct": self.pass_pct,
        }


@dataclasses.dataclass(frozen=True)
class EfficacyScorecard:
    title: str
    run_count: int
    run_ids: tuple[str, ...]
    coverage: CoverageStats
    mttd: MttdDistribution
    by_plane: tuple[BreakdownRow, ...]
    by_detection_type: tuple[BreakdownRow, ...]
    by_product: tuple[BreakdownRow, ...]
    generated_at: str
    verdicts: VerdictTally = dataclasses.field(default_factory=VerdictTally)

    def to_dict(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "run_count": self.run_count,
            "run_ids": list(self.run_ids),
            "coverage": self.coverage.to_dict(),
            "verdicts": self.verdicts.to_dict(),
            "mttd": self.mttd.to_dict(),
            "by_plane": [r.to_dict() for r in self.by_plane],
            "by_detection_type": [r.to_dict() for r in self.by_detection_type],
            "by_product": [r.to_dict() for r in self.by_product],
            "generated_at": self.generated_at,
        }


# ---------------------------------------------------------------------------
# Core builder (pure)
# ---------------------------------------------------------------------------


def normalize_detection_type(result: dict[str, Any]) -> str:
    """Map a result row onto the six-value detection_type vocabulary.

    Prefers the finer-grained ``detection_kind`` (``bioc | xql | correlation |
    ioc``, populated from the TTP card) and falls back to ``signal_type``
    (``BIOC | IOC | Analytics`` legacy). Anything unrecognized lands in
    ``Other`` so the scorecard never drops a signal.
    """
    kind = (result.get("detection_kind") or "").strip().lower()
    signal = (result.get("signal_type") or "").strip()
    raw = kind or signal.lower()
    mapping = {
        "bioc": "BIOC",
        "abioc": "ABIOC",
        "xql": "XQL",
        "analytics": "Analytics",
        "correlation": "Correlation",
        "ioc": "IOC",
    }
    if raw in mapping:
        return mapping[raw]
    # signal_type may already be canonical-cased (e.g. "Analytics").
    for dt in DETECTION_TYPES:
        if signal.lower() == dt.lower():
            return dt
    return "Other"


def product_for_plane(plane: Optional[str]) -> str:
    return PLANE_TO_PRODUCT.get((plane or "").strip().lower(), _DEFAULT_PRODUCT)


def _status(result: dict[str, Any]) -> str:
    """detected | missed | pending — matches report_generator._status_from_result."""
    if result.get("observed"):
        return "detected"
    if result.get("observed_at"):
        return "missed"
    return "pending"


def _percentile(values: list[float], pct: float) -> Optional[float]:
    """Linear-interpolation percentile (pct in 0..100). Pure, no numpy."""
    if not values:
        return None
    ordered = sorted(values)
    if len(ordered) == 1:
        return round(ordered[0], 1)
    rank = (pct / 100.0) * (len(ordered) - 1)
    low = int(rank)
    high = min(low + 1, len(ordered) - 1)
    frac = rank - low
    return round(ordered[low] + (ordered[high] - ordered[low]) * frac, 1)


def _coverage_from_counts(detected: int, missed: int, pending: int) -> CoverageStats:
    expected = detected + missed + pending
    pct = round(detected / expected * 100, 1) if expected else 0.0
    return CoverageStats(detected=detected, missed=missed, pending=pending,
                         expected=expected, pct=pct)


def _breakdown(results: list[dict[str, Any]], key_fn) -> list[BreakdownRow]:
    buckets: dict[str, dict[str, int]] = {}
    for r in results:
        label = key_fn(r)
        slot = buckets.setdefault(label, {"detected": 0, "missed": 0, "pending": 0})
        slot[_status(r)] += 1
    rows: list[BreakdownRow] = []
    for label, slot in buckets.items():
        cov = _coverage_from_counts(slot["detected"], slot["missed"], slot["pending"])
        rows.append(BreakdownRow(label=label, detected=cov.detected, missed=cov.missed,
                                 pending=cov.pending, expected=cov.expected, pct=cov.pct))
    # Highest coverage-gap first (most missed), then by expected volume — the
    # rows a CISO cares about float to the top.
    rows.sort(key=lambda x: (-(x.missed + x.pending), -x.expected, x.label))
    return rows


def build_efficacy_scorecard(
    results: Iterable[dict[str, Any]],
    *,
    run_ids: Optional[Iterable[str]] = None,
    title: Optional[str] = None,
    generated_at: Optional[str] = None,
    tc_verdicts: Optional[Iterable[Optional[str]]] = None,
) -> EfficacyScorecard:
    """Build the efficacy scorecard from ``Result.to_dict()``-shaped dicts.

    Works for a single run (pass that run's results) or a portfolio (pass the
    concatenated results of many runs and their ``run_ids``). Pure — no ORM,
    no session, fully unit-testable.
    """
    rows = list(results)

    detected = sum(1 for r in rows if _status(r) == "detected")
    missed = sum(1 for r in rows if _status(r) == "missed")
    pending = sum(1 for r in rows if _status(r) == "pending")
    coverage = _coverage_from_counts(detected, missed, pending)

    mttds = [float(r["mttd_seconds"]) for r in rows if r.get("mttd_seconds") is not None]
    mttd = MttdDistribution(
        count=len(mttds),
        min_seconds=round(min(mttds), 1) if mttds else None,
        median_seconds=_percentile(mttds, 50),
        p90_seconds=_percentile(mttds, 90),
        max_seconds=round(max(mttds), 1) if mttds else None,
    )

    by_plane = _breakdown(rows, lambda r: r.get("plane") or "—")
    by_detection_type = _breakdown(rows, normalize_detection_type)
    by_product = _breakdown(rows, lambda r: product_for_plane(r.get("plane")))

    ids = tuple(dict.fromkeys(run_ids or []))  # de-dupe, preserve order
    run_count = len(ids) if ids else (1 if rows else 0)

    # Run.tc_verdict is per-RUN, not per-result, so it arrives alongside the
    # rows rather than inside them. A run with no verdict counts as unscored —
    # never silently as a pass.
    counts: dict[str, int] = {}
    for v in (tc_verdicts or []):
        counts[v or "unscored"] = counts.get(v or "unscored", 0) + 1
    tally = VerdictTally(
        passed=counts.get("pass", 0),
        failed=counts.get("fail", 0),
        pending=counts.get("pending", 0),
        not_applicable=counts.get("not_applicable", 0),
        unscored=counts.get("unscored", 0),
    )

    return EfficacyScorecard(
        title=title or "Cortex POV Efficacy Scorecard",
        run_count=run_count,
        run_ids=ids,
        coverage=coverage,
        mttd=mttd,
        by_plane=tuple(by_plane),
        by_detection_type=tuple(by_detection_type),
        by_product=tuple(by_product),
        generated_at=generated_at or datetime.now(timezone.utc).isoformat(),
        verdicts=tally,
    )


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------


def format_mttd(seconds: Optional[float]) -> str:
    """Human-readable MTTD. Mirrors runs.py:_fmt_mttd so the two agree."""
    if seconds is None:
        return "—"
    if seconds < 60:
        return f"{seconds:g}s"
    if seconds < 3600:
        return f"{int(seconds // 60)}m {int(seconds % 60)}s"
    return f"{int(seconds // 3600)}h {int((seconds % 3600) // 60)}m"


def _verdict(pct: float) -> str:
    if pct >= 80:
        return ("Strong Cortex detection coverage confirmed across the simulated "
                "surface. Recommend promoting to a customer-facing POV report.")
    if pct >= 50:
        return ("Partial detection coverage. Recommend reviewing the missed "
                "detections and considering custom-rule remediation before hand-off.")
    return ("Coverage gap identified. Recommend authoring BIOC / correlation "
            "content to close the missed-detection delta before hand-off.")


# ---------------------------------------------------------------------------
# Markdown renderer
# ---------------------------------------------------------------------------


def render_markdown(scorecard: EfficacyScorecard) -> str:
    """Render the scorecard as Cortex-branded markdown for report export."""
    sc = scorecard
    cov = sc.coverage
    lines: list[str] = []

    lines.append(f"# {sc.title}")
    lines.append("")
    lines.append("---")
    lines.append("")
    scope = (f"{sc.run_count} run(s)" if sc.run_count != 1 else "1 run")
    lines.append(f"**Scope:** {scope}  ")
    if sc.run_ids:
        lines.append(f"**Runs:** {', '.join(f'`{r}`' for r in sc.run_ids)}  ")
    lines.append(f"**Generated:** {sc.generated_at}  ")
    lines.append("")

    # Executive summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(
        f"Cortex detected **{cov.detected} of {cov.expected}** expected "
        f"detections (**{cov.pct}% coverage**) across {scope}. "
        f"{_verdict(cov.pct)}"
    )
    lines.append("")

    # Test-case verdict. Deliberately its own section directly under the
    # summary: coverage is "how much of what we expected did we see", the
    # verdict is "did the test case meet its bar", and a reader who sees only
    # the first will take a high coverage number as a pass.
    v = sc.verdicts
    if v.passed or v.failed or v.pending or v.not_applicable or v.unscored:
        lines.append("## Test-Case Verdict")
        lines.append("")
        if v.scored:
            lines.append(
                f"**{v.passed} of {v.scored}** scoreable test case(s) met their "
                f"threshold (**{v.pass_pct}%**)."
            )
        else:
            lines.append(
                "No test case in this scope carries a machine-evaluable "
                "threshold, so none can be certified as passed."
            )
        if v.not_applicable:
            lines.append("")
            lines.append(
                f"_{v.not_applicable} test case(s) report `not_applicable` — the "
                f"index defines no measurable threshold for them, so a pass "
                f"cannot be asserted._"
            )
        if v.pending:
            lines.append("")
            lines.append(f"_{v.pending} still pending verification._")
        lines.append("")

    # Coverage headline
    lines.append("## Detection Coverage")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Coverage | **{cov.pct}%** |")
    lines.append(f"| Detected | {cov.detected} |")
    lines.append(f"| Missed | {cov.missed} |")
    lines.append(f"| Pending | {cov.pending} |")
    lines.append(f"| Expected (denominator) | {cov.expected} |")
    lines.append("")

    # MTTD
    lines.append("## Mean Time to Detect (MTTD)")
    lines.append("")
    if sc.mttd.count:
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Fastest (min) | {format_mttd(sc.mttd.min_seconds)} |")
        lines.append(f"| Median (p50) | **{format_mttd(sc.mttd.median_seconds)}** |")
        lines.append(f"| p90 | {format_mttd(sc.mttd.p90_seconds)} |")
        lines.append(f"| Slowest (max) | {format_mttd(sc.mttd.max_seconds)} |")
        lines.append(f"| Detections measured | {sc.mttd.count} |")
    else:
        lines.append("_No evidence-backed MTTD measured for this scope._")
    lines.append("")

    def _bd_table(header: str, rows: Iterable[BreakdownRow]) -> None:
        rows = list(rows)
        if not rows:
            return
        lines.append(f"## Coverage by {header}")
        lines.append("")
        lines.append(f"| {header} | Coverage | Detected | Missed | Pending | Expected |")
        lines.append("|" + "---|" * 6)
        for r in rows:
            lines.append(
                f"| {r.label} | {r.pct}% | {r.detected} | {r.missed} | "
                f"{r.pending} | {r.expected} |"
            )
        lines.append("")

    _bd_table("Cortex Product", sc.by_product)
    _bd_table("Detection Plane", sc.by_plane)
    _bd_table("Detection Type", sc.by_detection_type)

    lines.append("---")
    lines.append("")
    lines.append("*Generated by CortexSim — Palo Alto Networks Cortex Detection "
                 "Simulation Engine*")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML renderer (Cortex-branded, self-contained)
# ---------------------------------------------------------------------------


def _pct_bar(pct: float) -> str:
    return (
        f'<div class="cs-bar"><div class="cs-bar-fill" '
        f'style="width:{max(0.0, min(100.0, pct))}%"></div></div>'
    )


def _bd_html(header: str, rows: Iterable[BreakdownRow]) -> str:
    rows = list(rows)
    if not rows:
        return ""
    body = []
    for r in rows:
        body.append(
            "<tr>"
            f"<td class=\"cs-label\">{html.escape(r.label)}</td>"
            f"<td class=\"cs-pct\">{r.pct}% {_pct_bar(r.pct)}</td>"
            f"<td class=\"cs-num cs-det\">{r.detected}</td>"
            f"<td class=\"cs-num cs-miss\">{r.missed}</td>"
            f"<td class=\"cs-num cs-pend\">{r.pending}</td>"
            f"<td class=\"cs-num\">{r.expected}</td>"
            "</tr>"
        )
    return (
        f'<section class="cs-section"><h2>Coverage by {html.escape(header)}</h2>'
        '<table class="cs-table"><thead><tr>'
        f"<th>{html.escape(header)}</th><th>Coverage</th><th>Detected</th>"
        "<th>Missed</th><th>Pending</th><th>Expected</th>"
        "</tr></thead><tbody>" + "".join(body) + "</tbody></table></section>"
    )


def render_html(scorecard: EfficacyScorecard) -> str:
    """Render the scorecard as a self-contained Cortex-branded HTML document."""
    sc = scorecard
    cov = sc.coverage
    scope = (f"{sc.run_count} runs" if sc.run_count != 1 else "1 run")

    def _kpi(value: str, label: str, accent: str = _CORTEX_TEAL) -> str:
        return (
            f'<div class="cs-kpi"><div class="cs-kpi-val" style="color:{accent}">'
            f'{html.escape(value)}</div>'
            f'<div class="cs-kpi-lbl">{html.escape(label)}</div></div>'
        )

    mttd_kpis = ""
    if sc.mttd.count:
        mttd_kpis = (
            _kpi(format_mttd(sc.mttd.median_seconds), "Median MTTD (p50)")
            + _kpi(format_mttd(sc.mttd.p90_seconds), "p90 MTTD", _CORTEX_STEEL)
        )

    style = f"""
    .cs-root {{ font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI',
        sans-serif; color: {_CORTEX_NAVY}; max-width: 960px; margin: 0 auto;
        padding: 32px; background: #fff; }}
    .cs-root h1 {{ font-size: 26px; margin: 0 0 4px; color: {_CORTEX_NAVY}; }}
    .cs-root h2 {{ font-size: 18px; margin: 28px 0 12px; color: {_CORTEX_NAVY};
        border-bottom: 2px solid {_CORTEX_TEAL}; padding-bottom: 4px; }}
    .cs-meta {{ color: {_CORTEX_STEEL}; font-size: 13px; margin-bottom: 20px; }}
    .cs-meta code {{ font-family: 'JetBrains Mono', monospace; font-size: 12px; }}
    .cs-summary {{ background: {_CORTEX_NAVY}; color: #fff; padding: 20px 24px;
        border-radius: 8px; line-height: 1.5; }}
    .cs-summary strong {{ color: {_CORTEX_TEAL}; }}
    .cs-kpis {{ display: flex; flex-wrap: wrap; gap: 16px; margin: 20px 0; }}
    .cs-kpi {{ flex: 1 1 140px; border: 1px solid #e2e8ee; border-radius: 8px;
        padding: 16px; text-align: center; }}
    .cs-kpi-val {{ font-size: 30px; font-weight: 700; font-family: 'JetBrains Mono',
        monospace; }}
    .cs-kpi-lbl {{ font-size: 12px; color: {_CORTEX_STEEL}; margin-top: 4px;
        text-transform: uppercase; letter-spacing: .04em; }}
    .cs-table {{ width: 100%; border-collapse: collapse; font-size: 14px; }}
    .cs-table th {{ text-align: left; color: {_CORTEX_STEEL}; font-weight: 600;
        border-bottom: 2px solid #e2e8ee; padding: 8px 10px; }}
    .cs-table td {{ border-bottom: 1px solid #eef2f6; padding: 8px 10px; }}
    .cs-num {{ text-align: right; font-family: 'JetBrains Mono', monospace; }}
    .cs-det {{ color: {_DETECTED_GREEN}; font-weight: 600; }}
    .cs-miss {{ color: {_MISSED_RED}; }}
    .cs-pend {{ color: {_PENDING_AMBER}; }}
    .cs-pct {{ white-space: nowrap; }}
    .cs-bar {{ display: inline-block; width: 90px; height: 8px; background: #e2e8ee;
        border-radius: 4px; overflow: hidden; vertical-align: middle;
        margin-left: 8px; }}
    .cs-bar-fill {{ height: 100%; background: {_CORTEX_TEAL}; }}
    .cs-foot {{ margin-top: 32px; color: {_CORTEX_STEEL}; font-size: 12px;
        border-top: 1px solid #e2e8ee; padding-top: 12px; }}
    """

    run_ids_html = ""
    if sc.run_ids:
        run_ids_html = ("<div class=\"cs-meta\">Runs: "
                        + ", ".join(f"<code>{html.escape(r)}</code>" for r in sc.run_ids)
                        + "</div>")

    accent = (_DETECTED_GREEN if cov.pct >= 80
              else _CORTEX_TEAL if cov.pct >= 50 else _MISSED_RED)

    doc = (
        f"<style>{style}</style>"
        '<div class="cs-root">'
        f"<h1>{html.escape(sc.title)}</h1>"
        f'<div class="cs-meta">Scope: {html.escape(scope)} · '
        f"Generated {html.escape(sc.generated_at)}</div>"
        f"{run_ids_html}"
        f'<div class="cs-summary">Cortex detected '
        f"<strong>{cov.detected} of {cov.expected}</strong> expected detections "
        f"(<strong>{cov.pct}% coverage</strong>) across {html.escape(scope)}. "
        f"{html.escape(_verdict(cov.pct))}</div>"
        '<div class="cs-kpis">'
        + _kpi(f"{cov.pct}%", "Coverage", accent)
        + _kpi(str(cov.detected), "Detected", _DETECTED_GREEN)
        + _kpi(str(cov.missed), "Missed", _MISSED_RED)
        + _kpi(str(cov.pending), "Pending", _PENDING_AMBER)
        + mttd_kpis
        + "</div>"
        + _bd_html("Cortex Product", sc.by_product)
        + _bd_html("Detection Plane", sc.by_plane)
        + _bd_html("Detection Type", sc.by_detection_type)
        + '<div class="cs-foot">Generated by CortexSim — Palo Alto Networks '
          "Cortex Detection Simulation Engine</div>"
        "</div>"
    )
    return doc
