# TTP-2026-0131 — AI SOC Summarization Accuracy & Latency — 72-Minute Identity-to-Exfil Narrative Reconstruction (T1078 / T1059.001 / T1567.002 / T1041)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — AI-SOC-72 Valid-Account Reuse From Anomalous Endpoint Context (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned automation-identity baseline (scheduled cron jobs, no interactive shell) -> service-account authentication -> interactive endpoint session that diverges from the baseline, anchored to the originating auth as the initial-access phase.
# A valid service account whose learned Cortex profile is scheduled, non-interactive automation is driven interactively from an endpoint context that deviates from its baseline — the identity-driven initial-access phase (65% of intrusions per Unit 42). ABIOC anchors the deviation to the causality chain (service-account authentication -> interactive shell) rather than any known-bad binary, so hands-on-keyboard reuse of a legitimate account surfaces as the first signal the AI must name as initial access.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_effective_username in ("svc-backup", "svc-identity")
| filter action_process_image_name in ("bash", "sh", "zsh")
| filter action_process_command_line contains "sh -i"
| filter causality_actor_process_image_name in ("sshd", "su", "runuser", "sudo", "login", "systemd")
| comp count() as interactive_sessions by agent_hostname, actor_effective_username, causality_actor_process_image_name
| filter interactive_sessions >= 1
| fields agent_hostname, actor_effective_username, causality_actor_process_image_name, interactive_sessions

## ABIOC — AI-SOC-72 Rapid Privilege Escalation After Valid-Account Compromise (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Interactive shell under the compromised valid account -> rapid fan-out of distinct escalation utilities that exceeds the account's learned process diversity, anchored to the spawning shell as the privilege-escalation phase.
# Within minutes of the anomalous valid-account session, the account runs a scripted-interpreter escalation burst (sudo / pkexec / PowerShell-style encoded execution) at a cadence and privilege-seeking shape its learned baseline never exhibits. Every binary is legitimate; the ABIOC fires on the escalation-diversity deviation, anchored to the interactive shell that spawned it — the privilege-escalation phase the AI narrative must name second.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_effective_username in ("svc-backup", "svc-identity")
| filter action_process_image_name in ("sudo", "su", "pkexec", "pwsh", "powershell")
| comp count_distinct(action_process_image_name) as escalation_tools by agent_hostname, actor_effective_username
| filter escalation_tools >= 2
| sort desc escalation_tools
| fields agent_hostname, actor_effective_username, escalation_tools

## VALIDATION — AI-SOC-72 Exfiltration to Cloud Storage From Compromised Host
# purpose: validation
# dataset: pan_ngfw_traffic

dataset = pan_ngfw_traffic
| filter _time > to_timestamp(current_time() - 4320)
| filter dst_host contains "s3.amazonaws.com" or dst_host contains ".s3." or dst_host contains "storage.googleapis" or dst_host contains "blob.core.windows" or dst_host contains "cortexsim-exfil"
| comp sum(bytes_sent) as egress_bytes, count() as sessions by source_ip, dst_host
| filter egress_bytes >= 512
| sort desc egress_bytes
| fields source_ip, dst_host, egress_bytes, sessions

## VALIDATION — AI-SOC-72 Breakout-Window Timing From Identity to Exfil
# purpose: metric
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 4320)
| filter actor_effective_username in ("svc-backup", "svc-identity", "www-data", "nobody")
| comp min(_time) as first_signal, max(_time) as last_signal by agent_hostname, actor_effective_username
| alter breakout_seconds = last_signal - first_signal
| filter breakout_seconds <= 4320
| fields agent_hostname, actor_effective_username, first_signal, last_signal, breakout_seconds

