# TTP-2026-0024 — Container Escape via Privileged Mode and nsenter (T1611)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — CDR-003 Container Capability Read With Block Device Access
# severity: high
# Container privilege enumeration — /proc/self/status capability read combined with /dev device access. A container process reads its own capability mask and probes a host block device, the precondition check for a privileged-mode escape.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter action_process_image_command_line contains_any ("/proc/self/status", "CapEff", "CapBnd")
| filter action_process_image_command_line contains_any ("/dev/sda", "/dev/sd", "/dev/nvme", "/dev/xvda")

## BIOC — CDR-003 Privileged Container Full Capability Set Anomaly
# severity: high
# Privileged container anomaly — process capability set indicates full host capabilities. A container process is observed running with the full Linux capability bounding set (privileged mode).

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_command_line contains_any ("CapEff:\t0000003fffffffff", "CapBnd:\t0000003fffffffff", "CapPrm:\t0000003fffffffff")

## BIOC — CDR-003 Host Filesystem Access Via Proc1 Root From Container
# severity: high
# Host filesystem access via /proc/1/root from container — namespace traversal attempt. A container process reads host paths through /proc/1/root, reaching the host root filesystem without a formal escape.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter container_id != null
| filter action_file_path contains "/proc/1/root/"
| filter actor_process_image_name in ("ls", "cat", "bash", "sh", "find")

## BIOC — CDR-003 Proc1 Root Traversal Host Namespace Enumeration
# severity: medium
# Suspicious /proc/1/root traversal in container context — host namespace enumeration. A container process lists or reads host configuration through PID 1's root link to map the host before escaping.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter action_process_image_command_line contains "/proc/1/root"

## BIOC — CDR-003 nsenter Into PID1 Mount Namespace Container Escape
# severity: critical
# nsenter execution targeting PID 1 mount namespace — container escape via privileged mode (high fidelity). nsenter joins the host (PID 1) mount namespace from inside a container, the definitive escape primitive.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name = "nsenter"
| filter causality_actor_process_image_name in ("bash", "sh", "runc", "containerd-shim")
| filter action_process_image_command_line contains_any ("/proc/1/ns/mnt", "--mount=/proc/1", "-t 1", "--target 1")
| fields _time, container_id, causality_actor_process_image_name, causality_actor_process_instance_id, actor_effective_username, action_process_image_command_line

## BIOC — CDR-003 Anomalous Namespace Switch From Container Process
# severity: high
# Host namespace access via nsenter — anomalous namespace switch from container process. A container process switches into a host namespace via nsenter, an action no legitimate workload performs.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name = "nsenter"
| filter action_process_image_command_line contains_any ("--mount", "--pid", "--net", "--ipc", "--uts")

## BIOC — CDR-003 Host Passwd Read From Container Via Namespace Escape
# severity: high
# Host /etc/passwd access from container via namespace escape — credential harvesting post-escape. After escaping, the process reads the host /etc/passwd or /etc/shadow through the joined namespace.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter container_id != null
| filter action_file_path in ("/etc/passwd", "/etc/shadow")
| filter causality_actor_process_image_name = "nsenter" or actor_process_image_name = "nsenter"
| fields _time, container_id, causality_actor_process_image_name, causality_actor_process_instance_id, actor_process_image_name, action_file_path

## BIOC — CDR-003 Sensitive Host File Read Following Container Escape
# severity: high
# Sensitive host file read following successful container escape — multi-stage attack chain detected. A sensitive host credential file is read in the same container lineage that just performed an nsenter escape.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name = "nsenter"
| filter action_process_image_command_line contains_any ("/etc/passwd", "/etc/shadow", "cat /etc")

## BIOC — CDR-003 Host Cron Persistence Written From Escaped Container
# severity: critical
# Cron persistence written to host filesystem from container escape — T1611 + T1053 chained. The escaped process writes a cron job to the host /etc/cron.d to persist on the node.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter event_sub_type = ENUM.FILE_CREATE
| filter container_id != null
| filter action_file_path contains "/etc/cron.d/"
| filter causality_actor_process_image_name = "nsenter" or actor_process_image_name = "nsenter"
| fields _time, container_id, causality_actor_process_image_name, causality_actor_process_instance_id, action_file_path

## BIOC — CDR-003 Host CronD File Creation After Namespace Escape
# severity: critical
# Host cron.d file creation following container namespace escape — kill chain stitching signal. A new /etc/cron.d file appears on the host in a lineage that performed a namespace switch.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter action_process_image_command_line contains "/etc/cron.d/"
| filter causality_actor_process_image_name = "nsenter"

## VALIDATION — CDR-003 Validate nsenter PID1 Escape From Container
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name = "nsenter"
| filter action_process_image_command_line contains "/proc/1/ns"
| fields _time, agent_hostname, container_id, actor_effective_username, action_process_image_command_line

## VALIDATION — CDR-003 Validate Host Credential Read After Escape
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter container_id != null
| filter action_process_image_command_line contains_any ("/etc/passwd", "/etc/shadow")
| filter action_process_image_command_line contains "nsenter" or causality_actor_process_image_name = "nsenter"
| fields _time, agent_hostname, container_id, action_process_image_command_line

## VALIDATION — CDR-003 Validate Host CronD Persistence From Container
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter container_id != null
| filter action_process_image_command_line contains "/etc/cron.d/"
| fields _time, agent_hostname, container_id, actor_process_image_name, action_process_image_command_line

