# TTP-2026-0102 — DNS-Tunnel Behavioral Anomaly — Query-Volume + Subdomain-Entropy Deviation from Learned Host DNS Baseline (T1048.003 / T1071.004 / T1572)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — NDR-009 DNS Query-Volume Flood Deviating from Learned Host Baseline (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-host DNS baseline (stable, low per-minute resolution rate) -> a single host issuing a high-rate burst of distinct labels under one base domain, anchored to the originating host and base domain.
# A host whose learned Cortex DNS profile is a small, low-rate set of resolutions suddenly emits dozens of lookups under a single base domain within a minute. The ABIOC anchors the volume deviation to the causality chain (one host -> one base domain -> high-rate label burst) rather than to any known-bad domain, catching a DNS tunnel over an unseen base domain that a static domain-block would miss.

dataset = pan_dns
| filter _time > to_timestamp(current_time() - 900)
| filter dns_query_name contains ".exfil.testmynids.org"
| comp count() as query_count, count_distinct(dns_query_name) as distinct_labels by source_ip, bin(_time, 1m) as minute
| filter query_count >= 10
| sort desc query_count
| fields minute, source_ip, query_count, distinct_labels

## ABIOC — NDR-009 High-Entropy Subdomain Labels Deviating from Learned DNS Baseline (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Query-volume burst under a single base domain -> long, high-entropy encoded first-labels that exceed the host's learned name length and character-distribution profile, anchored to the emitting host.
# A host resolves long, encoded first-labels whose length and character distribution diverge from its learned DNS name shape — the encoded-payload signature of DNS tunneling. Every query is a legitimate DNS lookup; the ABIOC fires on the entropy-and-length deviation from the host's learned name baseline, anchored to the query-volume burst that carries it.

dataset = pan_dns
| filter _time > to_timestamp(current_time() - 900)
| filter dns_query_name contains ".exfil.testmynids.org"
| alter first_label = arrayindex(split(dns_query_name, "."), 0)
| filter len(first_label) >= 20
| comp count() as high_entropy_labels, avg(len(first_label)) as avg_label_len by source_ip
| filter high_entropy_labels >= 3 and avg_label_len > 18
| sort desc high_entropy_labels
| fields source_ip, high_entropy_labels, avg_label_len

## VALIDATION — NDR-009 DNS Query Volume Baseline Learned
# purpose: validation
# dataset: pan_dns

dataset = pan_dns
| filter _time > to_timestamp(current_time() - 900)
| filter dns_query_name contains ".exfil.testmynids.org"
| comp count() as baseline_queries by source_ip
| filter baseline_queries >= 1
| fields source_ip, baseline_queries

## VALIDATION — NDR-009 High-Entropy Label Burst Surfaced
# purpose: validation
# dataset: pan_dns

dataset = pan_dns
| filter _time > to_timestamp(current_time() - 900)
| filter dns_query_name contains ".exfil.testmynids.org"
| alter first_label = arrayindex(split(dns_query_name, "."), 0)
| filter len(first_label) >= 20
| comp count() as high_entropy_labels by source_ip
| filter high_entropy_labels >= 1
| fields source_ip, high_entropy_labels

