# TTP-2026-0093 — EMAIL — Thread-Hijack Reply-Chain Phishing (Proofpoint TAP + Microsoft 365)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — EMAIL-004 Pre-Flight email_emitter Metadata Visible
# severity: informational
# Pre-flight: email_emitter metadata visible to operator. Confirms the EAL plugin is registered and exposes EMAIL targets before any events are emitted, so a null result means a harness fault rather than a detection miss.

dataset = proofpoint_tap_raw
| filter messageType in ("messagesBlocked", "messagesDelivered", "clicksPermitted") or _raw_log contains "email_emitter"
| comp count() as preflight_events by recipient
| filter preflight_events >= 0

## VALIDATION — EMAIL-004 Thread-Hijack Reply-Chain Phishing Delivered
# purpose: validation
# dataset: proofpoint_tap_raw

// [MODEL: dataset=proofpoint_tap_raw, content_id="ProofpointTAP"]
dataset = proofpoint_tap_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter classification = "phish" and messageType = "messagesDelivered" and in_reply_to_existing_subject = true
| comp count() as hijack_events, values(sender) as senders, values(threatUrl) as urls by recipient
| filter hijack_events >= 1
| fields recipient, senders, urls, hijack_events

## VALIDATION — EMAIL-004 Thread-Hijack Permitted Click Follow-On
# purpose: validation
# dataset: proofpoint_tap_raw

dataset = proofpoint_tap_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter messageType = "clicksPermitted" and classification = "phish"
| comp count() as click_events, values(threatUrl) as clicked_urls by recipient, sender
| filter click_events >= 1
| fields recipient, sender, click_events, clicked_urls

