# TTP-2026-0173 — Token Jacking — A Stolen LLM Provider API Key Replayed From Foreign Infrastructure for Unauthorized Compute
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — LLM Provider API Key Replayed From Infrastructure Absent From Its Learned Calling Baseline (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: The API key identity owns this chain. The baseline arm and the anomalous arm share the key and nothing else, which is what makes the calling-location delta attributable rather than merely coincident.
# The primary claim. The key itself is valid and the traffic is well-formed TLS to a legitimate provider, so nothing about the request is malformed or blockable. The anomaly is that this key has a calling history and this call is not in it. Anchored per API key id rather than per user, because the credential is the actor: whoever holds it is indistinguishable from its owner by every other signal.

dataset = panw_ngfw_traffic_raw
| filter cortexsim_run_tag = "AIACC006"
| filter app in ("openai-api", "anthropic-api", "google-gemini-api", "ssl")
| comp count() as requests, count_distinct(source_ip) as calling_ips, count_distinct(dest_fqdn) as providers by api_key_id, user_agent
| filter requests >= 20 and calling_ips >= 2
| sort desc requests
| fields api_key_id, user_agent, providers, calling_ips, requests

## ABIOC — Sustained Inference Spend Deviating From the Key's Learned Token-Consumption Envelope (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Same API key identity, joined to the calling-location deviation on api_key_id so the two deltas raise one incident about one credential rather than two anomalies about traffic.
# The second delta, and the one that survives an adversary who proxies through the victim's own egress to defeat the location signal. Token consumption per key has a shape — request cadence, prompt and completion size, model mix — and unauthorized compute has a different one because its purpose is different. This is also the detection that produces the dollar figure, which is the rarest thing in a security POV: a finding that converts directly into a line on the cloud bill.

dataset = panw_ngfw_traffic_raw
| filter cortexsim_run_tag = "AIACC006"
| filter app in ("openai-api", "anthropic-api", "google-gemini-api", "ssl")
| comp sum(prompt_tokens) as prompt_total, sum(completion_tokens) as completion_total, count() as requests, count_distinct(model_name) as models by api_key_id
| alter total_tokens = add(prompt_total, completion_total)
| filter total_tokens >= 500000 and models >= 2
| sort desc total_tokens
| fields api_key_id, models, requests, prompt_total, completion_total, total_tokens

## VALIDATION — Baseline Arm — The Same Key Used Normally From Corporate Egress Before the Anomalous Arm
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 7200)
| filter cortexsim_run_tag = "AIACC006" and cortexsim_label = "benign"
| comp count() as requests, sum(prompt_tokens) as prompt_total, count_distinct(model_name) as models by api_key_id, source_ip
| filter requests >= 1
| sort desc requests
| fields api_key_id, source_ip, models, requests, prompt_total

## VALIDATION — Model and Endpoint Mix First Seen for This API Key
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 7200)
| filter cortexsim_run_tag = "AIACC006"
| filter model_first_seen_for_key = true
| comp count() as requests, count_distinct(model_name) as novel_models by api_key_id, dest_fqdn
| filter novel_models >= 1
| sort desc novel_models
| fields api_key_id, dest_fqdn, novel_models, requests

## VALIDATION — Unauthorized Inference Spend Accounting for the Compromised Key
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 7200)
| filter cortexsim_run_tag = "AIACC006" and cortexsim_label = "malicious"
| comp sum(prompt_tokens) as prompt_total, sum(completion_tokens) as completion_total, count() as requests by api_key_id, source_ip
| alter unauthorized_tokens = add(prompt_total, completion_total)
| sort desc unauthorized_tokens
| fields api_key_id, source_ip, requests, unauthorized_tokens

## VALIDATION — AI Provider API Keys Ranked by Calling-Location Spread
# purpose: hunt
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 86400)
| filter app in ("openai-api", "anthropic-api", "google-gemini-api")
| comp count_distinct(source_ip) as calling_ips, count_distinct(model_name) as models, count() as requests by api_key_id
| sort desc calling_ips
| limit 100
| fields api_key_id, calling_ips, models, requests

