# TTP-2026-0090 — EMAIL — Phishing Credential-Harvest Link (Proofpoint TAP + Microsoft 365)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — EMAIL-001 Pre-Flight email_emitter Metadata Visible
# severity: informational
# Pre-flight: email_emitter metadata visible to operator. Confirms the EAL plugin is registered and exposes EMAIL targets before any events are emitted, so a null result means a harness fault rather than a detection miss.

dataset = proofpoint_tap_raw
| filter messageType in ("messagesBlocked", "messagesDelivered", "clicksPermitted") or _raw_log contains "email_emitter"
| comp count() as preflight_events by recipient
| filter preflight_events >= 0

## VALIDATION — EMAIL-001 Phishing Credential-Link Blocked + Permitted Click
# purpose: validation
# dataset: proofpoint_tap_raw

// [MODEL: dataset=proofpoint_tap_raw, content_id="ProofpointTAP"]
dataset = proofpoint_tap_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter classification in ("credphish", "phish") and messageType in ("messagesBlocked", "clicksPermitted")
| comp count() as phish_events, values(messageType) as event_kinds, values(threatUrl) as urls by recipient, sender
| filter phish_events >= 1
| fields recipient, sender, phish_events, event_kinds, urls

## VALIDATION — EMAIL-001 Phishing Link Microsoft 365 EmailEvents Shape
# purpose: validation
# dataset: msft_o365

dataset = msft_o365
| filter _time > to_timestamp(current_time() - 1800)
| filter RecordType = "EmailEvents" and ThreatTypes contains "Phish" and UrlCount >= 1
| comp count() as phish_events, values(Url) as urls by RecipientEmailAddress, SenderFromAddress
| filter phish_events >= 1
| fields RecipientEmailAddress, SenderFromAddress, phish_events, urls

## VALIDATION — EMAIL-001 NGFW Outbound POST Burst To Email Collector
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter app in ("web-browsing", "ssl") and dst_port = 443
| filter uri_path contains "/email/events" or url contains "/email/events"
| comp count() as post_count, sum(bytes_sent) as bytes_out by src_ip, dst_host
| filter post_count >= 1
| fields src_ip, dst_host, post_count, bytes_out

