# TTP-2026-0029 — Cloud App — Google Full-Mailbox + Offline Token Replay Risk (T1114.002)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — CLOUD-003 Pre-Flight oauth_grant_emulator Plugin Registered
# severity: informational
# Pre-flight: oauth_grant_emulator metadata visible to operator. Confirms the EAL plugin is registered and its eal_targets enumerate the Cloud App OAuth-grant detections before any grant is emitted.

dataset = saas_audit_logs
| filter event_type = "eal_plugin_describe" or action contains "oauth_grant_emulator"
| filter app_name = "oauth_grant_emulator"
| fields _time, user, app_name, action

## VALIDATION — CLOUD-003 Google Full Mailbox Scope Grant Attempt
# purpose: validation
# dataset: google_workspace_audit

dataset = google_workspace_audit
| filter _time > to_timestamp(current_time() - 1800)
| filter oauth_scopes contains_any ("mail.google.com", "gmail.modify", "gmail.readonly")
| filter client_id != null
| fields _time, user, app_name, client_id, oauth_scopes, consent_type, source_ip, geo

## VALIDATION — CLOUD-003 NGFW Google OAuth Authorize Mailbox-Scope Egress
# purpose: validation
# dataset: saas_audit_logs

dataset = saas_audit_logs
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host = "accounts.google.com"
| filter uri_path contains "/o/oauth2/v2/auth"
| filter oauth_scopes contains "mail.google.com"
| fields _time, user, dst_host, uri_path, oauth_scopes, source_ip

## VALIDATION — CLOUD-003 Microsoft Mail ReadWrite Offline Access Token-Replay Grant
# purpose: validation
# dataset: msft_o365_audit

dataset = msft_o365_audit
| filter _time > to_timestamp(current_time() - 1800)
| filter oauth_scopes contains "Mail.ReadWrite"
| filter oauth_scopes contains "offline_access" or grant_type in ("offline", "refresh")
| fields _time, user, app_name, client_id, oauth_scopes, grant_type, source_ip

## VALIDATION — CLOUD-003 Cross-Provider Mailbox Collection Same Identity Stitch
# purpose: validation
# dataset: saas_audit_logs

dataset = saas_audit_logs
| filter _time > to_timestamp(current_time() - 1800)
| filter oauth_scopes contains_any ("mail.google.com", "gmail.modify", "Mail.ReadWrite", "Mail.Send")
| comp count_distinct(app_name) as mail_providers, values(app_name) as providers by user
| filter mail_providers >= 2
| fields user, mail_providers, providers

