# TTP-2026-0157 — GCP BigQuery Foreign-Project Exfil via Impersonated Service Account — Cortex ABIOC (T1537 / T1078.004)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — GCP Service Account Impersonation Attempt (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: statistical
# causality_anchor: Learned per-caller and per-peer-group service-account impersonation graph -> a caller principal (protoPayload.authenticationInfo.principalEmail) issues an iamcredentials GenerateAccessToken for a target_service_account new to its learned impersonation set, anchored to the impersonation call and its protoPayload.requestMetadata.callerIp.
# A caller principal mints short-lived credentials for a service account by calling iamcredentials.googleapis.com GenerateAccessToken, impersonating a service account that neither this caller nor its learned peer group has a history of impersonating. Every call is a legitimate IAM operation; this Cortex Analytics alert fires on the new caller-to-service-account impersonation edge — the deviation from the learned impersonation graph — anchored to the iamcredentials call rather than to any known-bad method name. The cloud_audit_emitter GCP builder emits only GenerateAccessToken for this preset (the impersonated principal is carried in the top-level target_service_account shape hint), so the logic keys on that single fully-qualified methodName rather than a leaf-name list.

dataset = cloud_audit_logs
| filter protoPayload.serviceName = "iamcredentials.googleapis.com"
| filter protoPayload.methodName = "google.iam.credentials.v1.IAMCredentials.GenerateAccessToken"
| comp count() as impersonation_calls by protoPayload.authenticationInfo.principalEmail, target_service_account, protoPayload.requestMetadata.callerIp
| filter impersonation_calls >= 1
| sort desc impersonation_calls
| fields protoPayload.authenticationInfo.principalEmail, target_service_account, protoPayload.requestMetadata.callerIp, impersonation_calls

## ABIOC — BigQuery Table or Query Results Exfiltrated to a Foreign Project (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-caller BigQuery destination-project set -> a BigQuery InsertJob writes results to a foreign project (foreign_project=true, destination_project_id outside the learned set), anchored to the caller principal (protoPayload.authenticationInfo.principalEmail) that submitted the job.
# A BigQuery job (query-results write / extract) run by a caller writes its output to a destination project that diverges from the account's learned set of destination projects — the shape of data exfiltration to a project outside the organization boundary. The individual InsertJob call is legitimate; the ABIOC fires on the foreign-destination-project deviation from the identity's learned BigQuery behavior. The cloud_audit_emitter GCP builder tags the exfil record with the foreign_project=true shape hint and the foreign destination_project_id, so the logic keys on that emitted deviation flag and destination project rather than an unemitted resource-vs-destination inequality.

dataset = cloud_audit_logs
| filter protoPayload.serviceName = "bigquery.googleapis.com"
| filter protoPayload.methodName = "google.cloud.bigquery.v2.JobService.InsertJob"
| filter foreign_project = true
| comp count() as foreign_project_jobs by protoPayload.authenticationInfo.principalEmail, destination_project_id
| filter foreign_project_jobs >= 1
| sort desc foreign_project_jobs
| fields protoPayload.authenticationInfo.principalEmail, destination_project_id, foreign_project_jobs

## VALIDATION — CDR-022 Service Account Impersonation Events Landed in Cloud Audit Log
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 900)
| filter protoPayload.serviceName = "iamcredentials.googleapis.com"
| filter protoPayload.methodName = "google.iam.credentials.v1.IAMCredentials.GenerateAccessToken"
| comp count() as impersonation_events by protoPayload.authenticationInfo.principalEmail, target_service_account
| filter impersonation_events >= 1
| fields protoPayload.authenticationInfo.principalEmail, target_service_account, impersonation_events

## VALIDATION — CDR-022 BigQuery Foreign-Project Export Landed in Cloud Audit Log
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 900)
| filter protoPayload.serviceName = "bigquery.googleapis.com"
| filter protoPayload.methodName = "google.cloud.bigquery.v2.JobService.InsertJob"
| filter foreign_project = true
| comp count() as foreign_project_jobs by protoPayload.authenticationInfo.principalEmail, destination_project_id
| filter foreign_project_jobs >= 1
| fields protoPayload.authenticationInfo.principalEmail, destination_project_id, foreign_project_jobs

