# TTP-2026-0146 — Certificate-Fingerprint Infrastructure Pivot — GNN Surfaces a Self-Signed TLS Cert Reused Across Trident Ursa IPs (T1587.003)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — SIM-TIM-004 Estate Handshake to a TIM-Armed Self-Signed Certificate
# severity: high
# An estate host completes a TLS handshake to a destination presenting the mocktaxii-armed self-signed certificate — server-certificate fingerprint equals the feed-armed value 07eee6e893766e8bcc4a711abfdf201ee2920799. Keying on the armed fingerprint (not a broad self-signed-cert predicate and not any single domain) is what seeds the fingerprint fan-out; a default/snakeoil self-signed cert cannot match, so there is no false-positive breadth.

dataset = panw_ngfw_traffic_raw
| filter app = "ssl" or app = "web-browsing"
| filter tls_cert_self_signed = true and tls_cert_fingerprint_sha1 = "07eee6e893766e8bcc4a711abfdf201ee2920799"
| comp count() as handshakes by agent_hostname, src_host, dst_ip, dst_host, tls_cert_fingerprint_sha1
| filter handshakes >= 1
| fields agent_hostname, src_host, dst_ip, dst_host, tls_cert_fingerprint_sha1, handshakes

## VALIDATION — SIM-TIM-004 Cert-Fingerprint Indicator Ingested
# purpose: validation
# dataset: threat_intel

dataset = threat_intel
| filter indicator_type in ("CERT_FINGERPRINT", "TLS_CERT_SHA1")
| filter indicator_value = "07eee6e893766e8bcc4a711abfdf201ee2920799"
| filter reference contains "certificate-fingerprint-pivot"
| comp count() as armed_indicators by indicator_type, indicator_value
| filter armed_indicators >= 1
| fields indicator_type, indicator_value, armed_indicators

## VALIDATION — SIM-TIM-004 Shared Self-Signed Cert Fingerprint Fan-Out Across IPs
# purpose: hunt
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter app = "ssl" or app = "web-browsing"
| filter tls_cert_self_signed = true and tls_cert_fingerprint_sha1 = "07eee6e893766e8bcc4a711abfdf201ee2920799"
| comp count_distinct(dst_ip) as distinct_ips, count_distinct(dst_host) as distinct_domains by tls_cert_fingerprint_sha1
| filter distinct_ips >= 2
| sort desc distinct_ips
| fields tls_cert_fingerprint_sha1, distinct_ips, distinct_domains

## VALIDATION — SIM-TIM-004 Feed Match Stitched to TLS Handshake on Cert Fingerprint
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter tls_cert_self_signed = true and tls_cert_fingerprint_sha1 = "07eee6e893766e8bcc4a711abfdf201ee2920799"
| comp count() as cluster_sessions, count_distinct(dst_ip) as cluster_ips by tls_cert_fingerprint_sha1, src_host
| filter cluster_sessions >= 1
| fields tls_cert_fingerprint_sha1, src_host, cluster_sessions, cluster_ips

