# TTP-2026-0112 — Leaked .env Credential to Self-Propagating Lambda Escalation — Large-Scale Cloud Extortion (SIM-CDR-017)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — IAM Self-Escalation to AdministratorAccess by a Newly Observed Access Key (behavioral-ML, causality-anchored)
# severity: critical
# behavioral_profile: machine-learning
# causality_anchor: Learned non-administrator access-key baseline -> leaked-key session -> iam:CreateRole (lambda-ex) -> iam:AttachRolePolicy attaching AdministratorAccess, anchored to the originating access key.
# An access key whose learned Cortex profile is a narrow application identity that has never performed IAM writes suddenly issues iam:CreateRole immediately followed by iam:AttachRolePolicy attaching the managed AdministratorAccess policy. Every call is a legitimate AWS API; the ABIOC fires on the self-escalation deviation from the key's learned (non-admin) behavior and anchors it to the causality chain (leaked key -> CreateRole -> AttachRolePolicy AdministratorAccess) rather than to any known-bad signature.

dataset = cloud_audit_logs
| filter cloud_provider = "AWS" and event_source = "iam.amazonaws.com"
| filter identity_type = "IAMUser"
| filter operation_name in ("CreateRole", "AttachRolePolicy")
| alter admin_attach = if(operation_name = "AttachRolePolicy" and request_parameters.policyArn contains "AdministratorAccess", 1, 0)
| comp count_distinct(operation_name) as iam_verbs, sum(admin_attach) as admin_attaches by identity_name, access_key_id
| filter iam_verbs >= 2 and admin_attaches >= 1 and access_key_id not in user_baseline.iam_writers
| fields identity_name, access_key_id, iam_verbs, admin_attaches

## ABIOC — Denied EC2 Compute Attempt Immediately Followed by Cross-Region Lambda Deployment (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Leaked-key session -> denied ec2:RunInstances (Client.UnauthorizedOperation) -> successful lambda:CreateFunction fan-out across multiple regions, anchored to the access key that pivoted from compute-denied to serverless-succeeded.
# The signature behavioral tell of this campaign: the same access key is denied on ec2:RunInstances (Client.UnauthorizedOperation) and then, within minutes, succeeds at deploying lambda:CreateFunction across multiple enabled regions. Cortex has learned this identity never spins up compute; the ABIOC anchors the denied-EC2-then-succeed-on-Lambda pivot and the cross-region fan-out to the key's causality chain, catching victim-funded compute abuse that no static rule keyed on a single API name would flag.

dataset = cloud_audit_logs
| filter cloud_provider = "AWS"
| filter (operation_name = "RunInstances" and error_code = "Client.UnauthorizedOperation") or (event_source = "lambda.amazonaws.com" and operation_name in ("CreateFunction20150331", "CreateFunction"))
| comp count_distinct(if(event_source = "lambda.amazonaws.com", region, null)) as lambda_regions, sum(if(operation_name = "RunInstances", 1, 0)) as denied_ec2 by identity_name, access_key_id
| filter denied_ec2 >= 1 and lambda_regions >= 3
| sort desc lambda_regions
| fields identity_name, access_key_id, denied_ec2, lambda_regions

## VALIDATION — Cross-Region Lambda Function Ex Fan-Out From Single Principal
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 3600)
| filter cloud_provider = "AWS" and event_source = "lambda.amazonaws.com"
| filter operation_name in ("CreateFunction20150331", "CreateFunction")
| comp count_distinct(region) as regions_deployed, count() as function_creates by identity_name, access_key_id
| filter regions_deployed >= 3
| sort desc regions_deployed
| fields identity_name, access_key_id, regions_deployed, function_creates

## VALIDATION — SES Sending-Quota Enumeration Burst After Key Validation
# purpose: hunt
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 3600)
| filter cloud_provider = "AWS" and event_source = "ses.amazonaws.com"
| filter operation_name in ("GetSendQuota", "GetAccountSendingEnabled", "GetAccount", "ListVerifiedEmailAddresses", "ListIdentities")
| comp count_distinct(operation_name) as ses_recon_calls by identity_name, access_key_id, caller_ip
| filter ses_recon_calls >= 3
| sort desc ses_recon_calls
| fields identity_name, access_key_id, caller_ip, ses_recon_calls

