# TTP-2026-0140 — Kali External-to-Internal Kill-Chain — Recon to Web Exploit to Credential Access to Lateral Movement (Chained Causality)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — MP-019 External Port-and-Service Scan Burst Against Exposed Host
# severity: medium
# The recon root. nmap + masscan + dnsrecon fan out from one operator source against the exposed lab host, producing a burst of connections to many distinct destination ports from a single source IP — the classic NDR port-scan signature that opens the kill-chain before any web or endpoint signal exists.

dataset = xdr_data
| filter event_type = ENUM.NETWORK and event_sub_type = ENUM.NETWORK_CONNECTION
| filter action_remote_ip = "${CORTEXSIM_WEB_TARGET}"
| comp count() as conns, count_distinct(action_remote_port) as distinct_ports by action_local_ip, action_remote_ip
| filter distinct_ports >= 20
| fields action_local_ip, action_remote_ip, distinct_ports, conns

## BIOC — MP-019 Web-Service Process Spawns Interactive Shell After Injection Exploit
# severity: high
# The exposure_exploit pivot and process-lineage anchor. The web app the operator enumerated is exploited (sqlmap injection / metasploit module) and lands code execution in the web-service context — the runtime tell is an interactive shell (bash/sh) whose causality_actor_process is the web server (nginx/apache/php-fpm) running as www-data. The BIOC keys on causality_actor_process_image_name + causality_actor_process_instance_id so the shell binds to the SAME web foothold the correlation opens on, not an incidental subprocess.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter causality_actor_process_image_name in ("nginx", "apache2", "httpd", "php", "php-fpm", "node") or actor_effective_username = "www-data"
| filter action_process_image_name in ("bash", "sh", "dash", "zsh")
| comp min(_time) as first_shell, count() as shells by agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, causality_id, actor_effective_username
| filter shells >= 1
| fields agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, causality_id, actor_effective_username, first_shell, shells

## BIOC — MP-019 Credential Brute-Force Child Spawned From Web-Service Shell
# severity: high
# The process_lineage pivot into credential access. From the landed www-data shell the operator launches an online guessing / spraying tool (hydra, netexec/nxc, medusa, ncrack) against the internal identity surface. The BIOC keys on the causality_actor_process (still the www-data shell) AND the brute-force interpreter child, tying the credential burst to the same web foothold rather than treating it as anonymous auth traffic.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter causality_actor_process_image_name in ("bash", "sh", "dash", "zsh") and actor_effective_username = "www-data"
| filter action_process_image_name in ("hydra", "nxc", "netexec", "crackmapexec", "medusa", "ncrack")
| comp min(_time) as first_bf, count() as bf_spawns by agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, causality_id, action_process_image_name
| filter bf_spawns >= 1
| fields agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, causality_id, action_process_image_name, first_bf, bf_spawns

## ABIOC — MP-019 Anomalous Lateral Authentication Burst From Web Host (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-host baseline of distinct remote SMB/DCE-RPC authentications; the ABIOC fires when a web host that never authenticates laterally bursts SMB/RPC auth to the DC from an impacket process spawned inside the www-data exploit shell (causality_actor_process).
# The exploit-chain terminal, keyed on the reused credential (shared_entity). Impacket (secretsdump.py / psexec.py) authenticates from the compromised web host to the Domain Controller over SMB/DCE-RPC — a host that in the learned baseline never initiates lateral authentication. The ABIOC anchors its deviation on the causality_actor_process (the impacket child of the www-data shell) and the source host, learning the per-host baseline of distinct remote SMB/RPC authentications and flagging the sudden lateral burst, so the DC auth binds back to the web-exploit chain rather than looking like a legitimate admin action.

dataset = xdr_data
| filter event_type = ENUM.NETWORK and event_sub_type = ENUM.NETWORK_CONNECTION
| filter action_remote_port in (445, 135, 139, 5985, 5986) and action_remote_ip = "${CORTEXSIM_DC_TARGET}"
| filter causality_actor_process_image_name in ("bash", "sh", "python", "python3") or action_process_image_name in ("secretsdump.py", "psexec.py", "wmiexec.py", "nxc", "netexec")
| comp count() as lateral_auths, count_distinct(action_remote_ip) as distinct_targets by agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, causality_id
| filter lateral_auths >= 1
| fields agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, causality_id, lateral_auths, distinct_targets

## VALIDATION — MP-019 External Recon Port-Scan Fan-Out Observed
# purpose: hunt
# dataset: xdr_data

dataset = xdr_data
| filter event_type = ENUM.NETWORK and event_sub_type = ENUM.NETWORK_CONNECTION
| filter action_remote_ip = "${CORTEXSIM_WEB_TARGET}"
| comp count() as conns, count_distinct(action_remote_port) as distinct_ports by action_local_ip, action_remote_ip
| filter distinct_ports >= 10
| sort desc distinct_ports
| fields action_local_ip, action_remote_ip, distinct_ports, conns

## VALIDATION — MP-019 Web Content-Discovery Fan-Out From Single Source
# purpose: hunt
# dataset: xdr_data

dataset = xdr_data
| filter event_type = ENUM.NETWORK
| filter action_remote_ip = "${CORTEXSIM_WEB_TARGET}" and action_remote_port in (80, 443, 8080, 9001)
| comp count() as requests, count_distinct(dst_action_url_domain) as distinct_uris by action_local_ip, action_remote_ip
| filter requests >= 50
| sort desc requests
| fields action_local_ip, action_remote_ip, requests, distinct_uris

## VALIDATION — MP-019 Injection Exploit Lands Shell In Web-Service Context
# purpose: hunt
# dataset: xdr_data

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter causality_actor_process_image_name in ("nginx", "apache2", "httpd", "php", "php-fpm") and action_process_image_name in ("bash", "sh", "dash")
| filter actor_effective_username = "www-data"
| comp min(_time) as first_shell, count() as shells by agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, causality_id
| filter shells >= 1
| fields agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, causality_id, first_shell, shells

## VALIDATION — MP-019 Online Password Brute-Force From Compromised Host
# purpose: hunt
# dataset: xdr_data

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_name in ("hydra", "nxc", "netexec", "crackmapexec", "medusa", "ncrack")
| filter causality_actor_process_image_name in ("bash", "sh", "dash") and actor_effective_username = "www-data"
| comp count() as bf_runs by agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, causality_id, action_process_command_line
| filter bf_runs >= 1
| fields agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, causality_id, action_process_command_line, bf_runs

## VALIDATION — MP-019 Impacket Lateral Movement With Harvested Credential
# purpose: hunt
# dataset: xdr_data

dataset = xdr_data
| filter event_type = ENUM.NETWORK and event_sub_type = ENUM.NETWORK_CONNECTION
| filter action_remote_ip = "${CORTEXSIM_DC_TARGET}" and action_remote_port in (445, 135, 139)
| filter action_process_image_name in ("secretsdump.py", "psexec.py", "wmiexec.py", "smbexec.py", "python", "python3") or causality_actor_process_image_name in ("bash", "sh")
| comp min(_time) as first_lateral, count() as lateral_conns by agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, causality_id, action_remote_ip
| filter lateral_conns >= 1
| fields agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, causality_id, action_remote_ip, first_lateral, lateral_conns

## VALIDATION — MP-019 External-to-Internal Kill-Chain Observed
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter action_remote_ip in ("${CORTEXSIM_WEB_TARGET}", "${CORTEXSIM_DC_TARGET}") or actor_effective_username = "www-data" or action_process_image_name in ("hydra", "nxc", "secretsdump.py", "psexec.py")
| comp count() as chain_events, count_distinct(event_sub_type) as distinct_stages by agent_hostname, causality_id
| filter chain_events >= 1
| fields agent_hostname, causality_id, chain_events, distinct_stages

