# TTP-2026-0181 — Clipboard and Local Memory Harvesting of Protected Health Information (PHI)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — Hl7 Phi Data Staging
# severity: high
# Hl7 Phi Data Staging

preset = xdr_data | filter event_type = 'FILE_WRITE' and action_file_name contains 'patient_phi' and (action_file_path contains '/tmp/' or action_file_path contains 'AppData')

## BIOC — Phi Clipboard Harvesting
# severity: high
# Phi Clipboard Harvesting

preset = xdr_data | filter event_type = 'FILE_WRITE' and action_file_name contains 'clipboard_capture' and action_file_path contains '/tmp/'

## VALIDATION — Endpoint DLP Clipboard PHI Audit
# purpose: hunt

dataset = xdr_data | filter event_type in ('FILE_WRITE', 'PROCESS_EXEC') and (action_file_name contains '.hl7' or action_file_name contains 'clipboard') | comp count() as ops by agent_hostname, actor_process_username | filter ops >= 1

