# TTP-2026-0047 — C2 Beacon Callback — NGFW + XDR Stitch Validation
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — XDR — interactive bash spawned from www-data service context
# severity: high
# XDR — interactive bash spawned from www-data service context

// AUTO-GENERATED SKELETON — replace with real XQL before promotion.
// MITRE technique: T1059.004
// Multi-plane correlation — combine BIOCs across planes
| filter /* TODO: predicate matching the BIOC name */
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

## BIOC — NGFW — repetitive HTTP beacon to testmynids.org (known IOC list)
# severity: high
# NGFW — repetitive HTTP beacon to testmynids.org (known IOC list)

// AUTO-GENERATED SKELETON — replace with real XQL before promotion.
// MITRE technique: T1071.001
// Multi-plane correlation — combine BIOCs across planes
| filter /* TODO: predicate matching the BIOC name */
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

## BIOC — XDR — curl executed from www-data with suspicious user-agent
# severity: high
# XDR — curl executed from www-data with suspicious user-agent

// AUTO-GENERATED SKELETON — replace with real XQL before promotion.
// MITRE technique: T1071.001
// Multi-plane correlation — combine BIOCs across planes
| filter /* TODO: predicate matching the BIOC name */
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

## BIOC — XSIAM correlation — NGFW outbound session + XDR process event sharing src_host + session_time stitched into single...
# severity: high
# XSIAM correlation — NGFW outbound session + XDR process event sharing src_host + session_time stitched into single incident

// AUTO-GENERATED SKELETON — replace with real XQL before promotion.
// MITRE technique: T1071.001
// Multi-plane correlation — combine BIOCs across planes
| filter /* TODO: predicate matching the BIOC name */
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

## BIOC — NGFW — DNS anomaly: high TXT query volume with high-entropy labels
# severity: high
# NGFW — DNS anomaly: high TXT query volume with high-entropy labels

// AUTO-GENERATED SKELETON — replace with real XQL before promotion.
// MITRE technique: T1572
// Multi-plane correlation — combine BIOCs across planes
| filter /* TODO: predicate matching the BIOC name */
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

## BIOC — XDR — repetitive dig invocation from service account
# severity: high
# XDR — repetitive dig invocation from service account

// AUTO-GENERATED SKELETON — replace with real XQL before promotion.
// MITRE technique: T1572
// Multi-plane correlation — combine BIOCs across planes
| filter /* TODO: predicate matching the BIOC name */
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

## BIOC — XSIAM stitching — DNS exfil pattern correlated with process lineage into unified exfiltration incident
# severity: high
# XSIAM stitching — DNS exfil pattern correlated with process lineage into unified exfiltration incident

// AUTO-GENERATED SKELETON — replace with real XQL before promotion.
// MITRE technique: T1572
// Multi-plane correlation — combine BIOCs across planes
| filter /* TODO: predicate matching the BIOC name */
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

## BIOC — NGFW — download from IOC-listed domain matching threat intel feed
# severity: high
# NGFW — download from IOC-listed domain matching threat intel feed

// AUTO-GENERATED SKELETON — replace with real XQL before promotion.
// MITRE technique: T1105
// Multi-plane correlation — combine BIOCs across planes
| filter /* TODO: predicate matching the BIOC name */
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

## BIOC — XDR — file written to /tmp/ by curl from service account
# severity: high
# XDR — file written to /tmp/ by curl from service account

// AUTO-GENERATED SKELETON — replace with real XQL before promotion.
// MITRE technique: T1105
// Multi-plane correlation — combine BIOCs across planes
| filter /* TODO: predicate matching the BIOC name */
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

