# TTP-2026-0084 — WildFire Test-Sample Retrieval in Container + Pod Misconfiguration — Cortex Cloud CDR (T1610 / T1204)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — CDR-012 Privileged or HostPath Pod Misconfiguration
# severity: medium
# A pod runs with a privileged securityContext, runs as root (runAsUser 0), or mounts a hostPath volume — the runtime-observable insecure-pod misconfiguration the lab's K8-container-misconfig manifest plants (T1610 Deploy Container). This is the posture state that enables container escape and malware staging.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_container_info != null
| alter privileged = json_extract_scalar(actor_container_info, "$.privileged")
| filter privileged = "true" or actor_effective_username = "root"
| comp count() as privileged_proc_events by agent_hostname, actor_effective_username
| filter privileged_proc_events >= 1
| fields agent_hostname, actor_effective_username, privileged_proc_events

## BIOC — CDR-012 Container Executes Downloaded Sample
# severity: high
# A container chmod-s and executes a file it just downloaded into a hidden staging directory (the WildFire sample path /var/tmp/.hidden_wildfire_samples), the download-then-execute shape of container malware delivery (T1204 User Execution). CortexSim stages only benign WildFire test files, but the telemetry shape is identical to a real drop.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_container_info != null
| filter action_process_image_command_line contains "/var/tmp/.hidden_wildfire_samples" or actor_process_image_command_line contains "chmod +x"
| comp count() as exec_events by agent_hostname, actor_process_image_name
| filter exec_events >= 1
| fields agent_hostname, actor_process_image_name, exec_events

## VALIDATION — CDR-012 Container Workload Projection
# purpose: hunt
# dataset: xdr_data

dataset = xdr_data
| fields actor_container_info as container_info
| filter container_info != null
| alter pod_namespace = json_extract_scalar(container_info, "$.pod_namespace")
| alter pod_name = json_extract_scalar(container_info, "$.pod_name")
| alter image_name = json_extract_scalar(container_info, "$.image_name")
| alter image_id = json_extract_scalar(container_info, "$.image_id")
| alter container_id = json_extract_scalar(container_info, "$.id")
| alter privileged = json_extract_scalar(container_info, "$.privileged")
| filter actor_process_image_name in ("curl", "wget", "sh", "bash")

## VALIDATION — CDR-012 WildFire Test Sample Retrieval in Container
# purpose: validation
# dataset: network_story

dataset = network_story
| filter _time > to_timestamp(current_time() - 600)
| filter dst_host = "wildfire.paloaltonetworks.com" or action_external_hostname = "wildfire.paloaltonetworks.com"
| filter actor_process_image_name in ("curl", "wget")
| comp count() as wildfire_pulls by agent_hostname, actor_process_image_name
| filter wildfire_pulls >= 1
| sort desc wildfire_pulls
| fields agent_hostname, actor_process_image_name, wildfire_pulls

## VALIDATION — CDR-012 Insecure Pod Misconfiguration Surfaced
# purpose: validation
# dataset: cortex_cloud_posture

dataset = cortex_cloud_posture
| filter _time > to_timestamp(current_time() - 600)
| filter resource_type in ("k8s_pod", "k8s_deployment")
| filter finding_class in ("privileged-container", "run-as-root", "hostpath-mount", "missing-resource-limits", "missing-securitycontext")
| comp count_distinct(resource_id) as misconfigured_pods by finding_class
| filter misconfigured_pods >= 1
| fields finding_class, misconfigured_pods

