# TTP-2026-0078 — Active Directory Privilege Escalation & Token Manipulation Chain — LSASS to SYSTEM (T1068 / T1134 / T1003.001)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — ITDR-007 LSASS Process Handle Open By Non-System Process
# severity: high
# XDR - a non-system process opens a process handle to lsass.exe with credential-read access rights. Reading LSASS memory is the canonical credential-dumping primitive (T1003.001); pypykatz parses the resulting dump offline.

dataset = xdr_data
| filter event_type = ENUM.PROCESS
| filter action_type = ENUM.PROCESS_HANDLE
| filter lower(target_process_image_name) = "lsass.exe"
| filter actor_effective_username not in ("NT AUTHORITY\\SYSTEM", "NT AUTHORITY\\LOCAL SERVICE")
| filter requested_access_mask contains "0x10"
| fields _time, src_host, actor_process_image_name, actor_effective_username, requested_access_mask

## BIOC — ITDR-007 Abnormal DACL Write To AdminSDHolder Or Privileged Group
# severity: high
# ITDR - an abnormal write to the nTSecurityDescriptor (DACL) of AdminSDHolder or a privileged group (Domain Admins / Enterprise Admins) granting GenericAll or WriteDACL. ACL-based escalation (T1098) lets a foothold account take control of privileged objects; bloodyAD writes the malicious ACE.

dataset = ad_audit
| filter event_id = 4662
| filter lower(object_properties) contains "writedacl" or lower(object_properties) contains "ntsecuritydescriptor"
| filter lower(object_name) contains "adminsdholder" or lower(object_name) contains "domain admins" or lower(object_name) contains "enterprise admins"
| filter actor_effective_username not in ("Administrator", "svc-adsync")
| fields _time, src_host, actor_effective_username, object_name, object_properties

## BIOC — ITDR-007 Kerberos Relay To LDAP From Local Host (KrbRelayUp)
# severity: high
# ITDR - a Kerberos authentication is relayed from the local host to LDAP/LDAPS on a domain controller, immediately followed by a write to the local computer object's msDS-AllowedToActOnBehalfOfOtherIdentity (RBCD). This self-relay to obtain a SYSTEM ticket is the KrbRelayUp local-privilege-escalation fingerprint (T1550 / T1068).

dataset = xdr_data
| filter event_type = ENUM.NETWORK
| filter dst_port in (389, 636)
| filter lower(app_id) contains "kerberos" or lower(auth_protocol) contains "kerberos"
| filter src_host = dst_host
| fields _time, src_host, dst_host, dst_port, actor_process_image_name

## BIOC — ITDR-007 SeImpersonate Named-Pipe Privilege Escalation To SYSTEM
# severity: high
# XDR - a service account holding SeImpersonatePrivilege (IIS w3wp.exe, MSSQL sqlservr.exe, or a 'potato' tool) spawns a child process running as NT AUTHORITY\SYSTEM via named-pipe token impersonation. This is the PrintSpoofer / potato-family local escalation (T1134).

dataset = xdr_data
| filter event_type = ENUM.PROCESS
| filter action_type = ENUM.PROCESS_START
| filter actor_effective_username = "NT AUTHORITY\\SYSTEM"
| filter lower(causality_actor_process_image_name) in ("w3wp.exe", "sqlservr.exe", "printspoofer64.exe", "printspoofer.exe")
| fields _time, src_host, causality_actor_process_image_name, action_process_image_name, actor_effective_username

## BIOC — ITDR-007 Access Token Theft And Impersonation Via Token Duplication
# severity: high
# XDR - a process duplicates and impersonates the access token of a privileged/SYSTEM process (e.g. winlogon.exe) so it runs in that security context. DuplicateTokenEx + ImpersonateLoggedOnUser against a high-privilege parent is the access-token-theft fingerprint (T1134); Tokenvator automates it.

dataset = xdr_data
| filter event_type = ENUM.PROCESS
| filter action_type = ENUM.PROCESS_TOKEN
| filter lower(target_process_image_name) in ("winlogon.exe", "lsass.exe", "services.exe")
| filter actor_effective_username not in ("NT AUTHORITY\\SYSTEM")
| fields _time, src_host, actor_process_image_name, actor_effective_username, target_process_image_name

## VALIDATION — ITDR-007 Validate LSASS Credential Access By Non-System Process
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS
| filter action_type = ENUM.PROCESS_HANDLE
| filter lower(target_process_image_name) = "lsass.exe"
| filter actor_effective_username not in ("NT AUTHORITY\\SYSTEM")
| comp count() as lsass_handles by src_host, actor_process_image_name, actor_effective_username
| filter lsass_handles >= 1
| fields src_host, actor_process_image_name, actor_effective_username, lsass_handles

## VALIDATION — ITDR-007 Validate Abnormal Privileged DACL Modification
# purpose: validation
# dataset: ad_audit

dataset = ad_audit
| filter _time > to_timestamp(current_time() - 1800)
| filter event_id = 4662
| filter lower(object_properties) contains "writedacl" or lower(object_properties) contains "ntsecuritydescriptor"
| filter lower(object_name) contains "adminsdholder" or lower(object_name) contains "domain admins" or lower(object_name) contains "enterprise admins"
| comp count() as dacl_writes by src_host, actor_effective_username, object_name
| filter dacl_writes >= 1
| fields src_host, actor_effective_username, object_name, dacl_writes

## VALIDATION — ITDR-007 Validate SYSTEM Token Spawned From Service Account Process
# purpose: validation
# dataset: msft_windows_security

dataset = msft_windows_security
| filter _time > to_timestamp(current_time() - 1800)
| filter event_id = 4688
| filter lower(new_process_token_user) contains "system"
| filter lower(creator_process_name) in ("w3wp.exe", "sqlservr.exe", "printspoofer64.exe", "printspoofer.exe")
| comp count() as system_spawns by src_host, creator_process_name, new_process_name
| filter system_spawns >= 1
| fields src_host, creator_process_name, new_process_name, system_spawns

## VALIDATION — ITDR-007 Validate Local Privilege Escalation Chain To SYSTEM
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS
| filter action_type = ENUM.PROCESS_START
| filter actor_effective_username = "NT AUTHORITY\\SYSTEM"
| filter lower(causality_actor_process_image_name) not in ("services.exe", "wininit.exe", "smss.exe", "system")
| comp count_distinct(action_process_image_name) as system_children by src_host, causality_actor_process_image_name
| filter system_children >= 1
| fields src_host, causality_actor_process_image_name, system_children

