# TTP-2026-0028 — Cloud App — Microsoft Admin-Consent-Required Scope Request (T1078.004)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — CLOUD-002 Pre-Flight Microsoft Provider Supported
# severity: informational
# Pre-flight: provider list includes microsoft. Confirms the oauth_grant_emulator params schema advertises the microsoft provider before any grant is emitted.

dataset = saas_audit_logs
| filter event_type = "eal_plugin_describe" or action contains "oauth_grant_emulator"
| filter app_name = "oauth_grant_emulator"
| fields _time, user, app_name, action

## BIOC — CLOUD-002 Microsoft Application ReadWrite All In Same Grant Body
# severity: critical
# Cloud App — Application.ReadWrite.All in same grant body. The highest-risk app-management Graph scope appears in the authorize request, enabling rogue service-principal creation for tenant persistence.

dataset = msft_o365_audit
| filter oauth_scopes contains "Application.ReadWrite.All"
| filter consent_type != "admin"
| filter client_id != null
| fields _time, user, app_name, client_id, oauth_scopes, consent_type, source_ip

## VALIDATION — CLOUD-002 Microsoft Directory ReadWrite All Admin-Consent Scope Request
# purpose: validation
# dataset: msft_o365_audit

dataset = msft_o365_audit
| filter _time > to_timestamp(current_time() - 1800)
| filter consent_type != "admin"
| filter oauth_scopes contains_any ("Directory.ReadWrite.All", ".default")
| filter client_id != null
| fields _time, user, app_name, client_id, oauth_scopes, consent_type, source_ip, geo

## VALIDATION — CLOUD-002 NGFW Microsoft v2 Authorize Admin-Consent Egress
# purpose: validation
# dataset: saas_audit_logs

dataset = saas_audit_logs
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host = "login.microsoftonline.com"
| filter uri_path contains "/oauth2/v2.0/authorize"
| filter oauth_scopes contains_any ("Directory.ReadWrite.All", "Application.ReadWrite.All")
| fields _time, user, dst_host, uri_path, oauth_scopes, source_ip

## VALIDATION — CLOUD-002 Microsoft Repeat Admin-Consent Persistence Attempt
# purpose: validation
# dataset: msft_o365_audit

dataset = msft_o365_audit
| filter _time > to_timestamp(current_time() - 1800)
| filter consent_type != "admin"
| filter oauth_scopes contains_any ("Directory.ReadWrite.All", "Application.ReadWrite.All")
| comp count() as attempts by user, client_id, app_name
| filter attempts >= 2
| fields user, client_id, app_name, attempts

