# TTP-2026-0067 — TIM IOC Feed Match — TAXII-Fed C2 Indicator + Outbound NDR Session Stitch (T1071.001 / T1568)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — TIM — Outbound Session to TAXII-Fed IOC Domain Carrying Simulation Header
# severity: high
# NGFW EAL — outbound HTTP to a planted TIM IOC subdomain (.internal C2 zone) carrying the X-Simulation-Run-ID operator header. Behavioral leg that ties the simulated beacon to a feed-listed destination so the DC can isolate POV sessions.

dataset = panw_ngfw_traffic_raw
| filter app in ("web-browsing", "http")
| filter dst_host contains_any ("c2-beacon.", "exfil-drop.", "payload-delivery.", "dga-1a2b3c.", "cryptominer-pool.")
| filter dst_host contains ".internal"
| filter http_req_headers contains "X-Simulation-Run-ID"
| filter action = "allow"
| fields _time, src_ip, dst_ip, dst_host, app, uri, http_user_agent, http_req_headers

## VALIDATION — TIM Pre-flight — TAXII Feed Indicators Ingested Into Threat Intel
# purpose: validation
# dataset: threat_intel

dataset = threat_intel
| filter _time > to_timestamp(current_time() - 86400)
| filter feed_source = "mocktaxii" or feed_name contains "mocktaxii"
| filter indicator_type = "domain-name" or indicator_type = "ipv4-addr"
| comp count() as indicators by feed_source
| filter indicators >= 1
| fields feed_source, indicators

## VALIDATION — TIM IOC Match — Outbound Session to TAXII-Fed C2 Domain
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter app in ("web-browsing", "http", "dns", "ssl")
| filter dst_host contains_any ("c2-beacon.", "exfil-drop.", "payload-delivery.", "dga-1a2b3c.", "cryptominer-pool.")
| join type=inner (dataset = threat_intel | filter feed_source = "mocktaxii" | filter indicator_type = "domain-name" | fields indicator_value) as feed feed.indicator_value = dst_host
| comp count() as ioc_hits, count_distinct(dst_host) as matched_indicators by src_ip
| filter ioc_hits >= 1
| fields src_ip, matched_indicators, ioc_hits

## VALIDATION — TIM — Periodic Beacon to Feed-Listed IOC Domain (NDR leg)
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter app in ("web-browsing", "http")
| filter dst_host contains "c2-beacon." and dst_host contains ".internal"
| filter action = "allow"
| comp count() as beacon_count, count_distinct(http_user_agent) as ua_variants, avg(bytes_sent) as avg_bytes_sent by src_ip, dst_ip, dst_host
| filter beacon_count >= 8
| fields src_ip, dst_ip, dst_host, beacon_count, ua_variants, avg_bytes_sent

## VALIDATION — TIM Stitch — IOC Feed Match Joined to NDR Session on Source Host
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host contains ".internal"
| join type=inner (dataset = threat_intel | filter feed_source = "mocktaxii" | filter indicator_type = "domain-name" | fields indicator_value) as feed feed.indicator_value = dst_host
| comp count_distinct(dst_host) as matched_iocs, count() as sessions, min(_time) as first_seen, max(_time) as last_seen by src_ip
| filter matched_iocs >= 1 and sessions >= 8
| fields src_ip, matched_iocs, sessions, first_seen, last_seen

## VALIDATION — TIM — Any Host Resolving a DGA-Style Feed-Listed Subdomain (T1568)
# purpose: hunt
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 86400)
| filter app = "dns" or dns_query_name != null
| filter dns_query_name contains "dga-1a2b3c." and dns_query_name contains ".internal"
| comp count() as resolutions by src_ip, dns_query_name
| fields src_ip, dns_query_name, resolutions

