# TTP-2026-0022 — Container Enumeration via DEEPCE and LinPEAS (T1613)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — CDR-001 Package Manager Execution Inside Running Container
# severity: medium
# Package manager execution inside running container — unusual install pattern indicates post-exploitation activity. apt-get/apk/yum runs interactively in a container where image content should already be baked.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name in ("apt-get", "apt", "apk", "yum", "dnf")
| filter action_process_image_command_line contains_any ("install", "add", "update")

## BIOC — CDR-001 DEEPCE Container Enumeration Script Execution
# severity: high
# DEEPCE container enumeration script execution — known tool signature matched by CDR BIOC rule. bash runs deepce.sh inside a container to fingerprint the runtime for escape vectors.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name in ("bash", "sh")
| filter action_process_image_command_line contains "deepce"

## BIOC — CDR-001 Curl Pipe Bash Download Execute In Container
# severity: high
# Suspicious curl download followed by bash execution in container context (curl-pipe-bash pattern). A container process curls a remote script and immediately executes it through a shell.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name in ("curl", "wget")
| filter action_process_image_command_line contains_any (".sh", "raw/main", "releases/latest")
| filter causality_actor_process_image_name in ("bash", "sh")

## BIOC — CDR-001 Container Capability Mask Read From Proc1 Status
# severity: high
# Container privileged mode enumeration — /proc/1/status capability read indicating escape preparation. A container process reads the init process capability mask to determine whether it runs privileged.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter container_id != null
| filter action_file_path in ("/proc/1/status", "/proc/self/status")
| filter actor_process_image_name in ("cat", "grep", "bash", "sh", "deepce.sh")

## BIOC — CDR-001 Container Device Enumeration With Capability Inspection
# severity: medium
# Suspicious device enumeration and capability inspection sequence in container. A container process lists /dev block devices alongside reading capability/mount state to map escape preconditions.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name in ("ls", "mount", "env")
| filter action_process_image_command_line contains_any ("/dev/", "overlay", "docker", "k8s", "kube")

## BIOC — CDR-001 Service Account Token Access From Container
# severity: high
# Service account token access from within container — credential harvesting behavior. A container process reads the projected Kubernetes service-account token from the secrets mount.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter container_id != null
| filter action_file_path contains "serviceaccount/token"
| filter actor_process_image_name in ("cat", "find", "bash", "sh", "cp")

## BIOC — CDR-001 Broad Filesystem Credential Search In Container
# severity: medium
# Broad filesystem credential search pattern (find / -name token) in container context. find sweeps the whole container filesystem for token/key/pem files.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name = "find"
| filter action_process_image_command_line contains_any ("-name token", ".pem", ".key")

## BIOC — CDR-001 LinPEAS Privilege Escalation Tool In Container
# severity: high
# LinPEAS execution in container — post-exploitation privilege escalation tool signature. bash runs linpeas.sh inside a container to enumerate privilege-escalation and escape vectors.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name in ("bash", "sh", "linpeas.sh")
| filter action_process_image_command_line contains "linpeas"

## BIOC — CDR-001 Automated Discovery Command Burst In Container
# severity: medium
# Multiple system enumeration commands executed in sequence — automated discovery behavior. A burst of distinct discovery binaries fires from one container lineage in a short window.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name in ("uname", "id", "hostname", "ls", "cat", "mount", "env", "find")
| comp count_distinct(actor_process_image_name) as discovery_breadth by container_id, causality_actor_process_instance_id
| filter discovery_breadth >= 4

## VALIDATION — CDR-001 Validate DEEPCE Or LinPEAS Execution In Container
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter action_process_image_command_line contains_any ("deepce", "linpeas")
| fields _time, agent_hostname, container_id, actor_process_image_name, actor_effective_username, action_process_image_command_line

## VALIDATION — CDR-001 Validate Service Account Token Read In Container
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.FILE
| filter container_id != null
| filter action_file_path contains "serviceaccount/token"
| fields _time, agent_hostname, container_id, actor_process_image_name, action_file_path

## VALIDATION — CDR-001 Validate Capability And Device Recon In Container
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter action_process_image_command_line contains_any ("/proc/1/status", "/proc/self/status", "CapEff", "/dev/")
| fields _time, agent_hostname, container_id, actor_process_image_name, action_process_image_command_line

