# TTP-2026-0016 — AIRS — Unbounded Consumption / Token-Exhaustion DoS (LLM10)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## VALIDATION — AIRS LLM10 Preflight Endpoint Accepts Unbounded Max Tokens
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_port = 8089 and uri_path contains "/healthz"
| filter http_rsp_code = 200
| fields _time, src_ip, dst_ip, dst_port, uri_path, http_rsp_code

## VALIDATION — AIRS LLM10 Token Usage Rolling Sum Exceeds Per User Budget
# purpose: validation
# dataset: cortexsim_airs_raw

dataset = cortexsim_airs_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter event_action = "airs_probe_attempt" and owasp_id = "LLM10"
| alter token_total = to_number(json_extract_scalar(detector_results, "$.token_total"))
| comp sum(token_total) as rolling_token_total by src_host
| filter rolling_token_total >= 8000
| fields src_host, rolling_token_total

## VALIDATION — AIRS LLM10 P95 Latency On Chat Endpoint Exceeds Threshold Under Load
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_port = 8089 and uri_path contains "/owasp/llm10/chat" and http_method = "POST"
| comp percentile(response_time_ms, 95) as p95_latency_ms, count() as request_count by dst_host
| filter request_count >= 25
| fields dst_host, request_count, p95_latency_ms

## VALIDATION — AIRS LLM10 NGFW Sustained POST Burst Flagged Anomalous App Traffic
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_port = 8089 and uri_path contains "/owasp/llm10/chat" and http_method = "POST"
| comp count() as post_count by src_ip, dst_host
| filter post_count >= 25
| fields src_ip, dst_host, post_count

## VALIDATION — AIRS LLM10 Circuit Breaker Rejects Oversized Request With 429
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_port = 8089 and uri_path contains "/owasp/llm10/chat"
| filter http_rsp_code = 429 or http_rsp_code = 503
| fields _time, src_ip, dst_host, uri_path, http_rsp_code

