# TTP-2026-0144 — The Gentlemen 'GentleKiller' ThrottleStop.sys BYOVD EDR-Kill — Cortex EDR Behavioral Anomaly (ABIOC) (T1562.001 / T1543.003 / T1068)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — GentleKiller Vulnerable Driver Service Created (ThrottleStop.sys BYOVD)
# severity: high
# A kernel-driver service is registered (registry ImagePath under Services) pointing at ThrottleStop.sys — the signed-but-vulnerable OEM driver (CVE-2025-7771) The Gentlemen abuse for BYOVD EDR-kill. The service-creation write is the earliest citable forensic artifact of the chain and precedes the actual driver load.

dataset = xdr_data
| filter event_type = ENUM.REGISTRY and event_sub_type = ENUM.REGISTRY_SET_VALUE
| filter action_registry_key_name contains "\\Services\\" and action_registry_value_name = "ImagePath"
| filter lowercase(action_registry_data) contains "throttlestop.sys"
| filter actor_process_image_name not in ("TrustedInstaller.exe", "msiexec.exe")
| fields agent_hostname, actor_process_image_name, action_registry_key_name, action_registry_data

## BIOC — Volume Shadow Copy Deletion via vssadmin/wmic (Pre-Encryption)
# severity: high
# vssadmin, wmic, wbadmin or diskshadow deletes or resizes Volume Shadow Copies to inhibit recovery ahead of ransomware encryption — the destructive stage that follows the blinded-host recon and C2 in The Gentlemen chain. A high-fidelity, citable impact artifact for the POV report.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_name in ("vssadmin.exe", "wmic.exe", "wbadmin.exe", "diskshadow.exe")
| filter lowercase(action_process_image_command_line) contains "delete shadows" or lowercase(action_process_image_command_line) contains "shadowcopy delete" or lowercase(action_process_image_command_line) contains "resize shadowstorage"
| comp count() as shadow_ops by agent_hostname, actor_effective_username, action_process_image_name, action_process_image_command_line
| filter shadow_ops >= 1
| fields agent_hostname, actor_effective_username, action_process_image_name, action_process_image_command_line, shadow_ops

## ABIOC — BYOVD EDR-Kill Behavioral Anomaly — Anomalous Signed Vulnerable Driver Load (GentleKiller) (behavioral-ML, causality-anchored)
# severity: critical
# behavioral_profile: machine-learning
# causality_anchor: Learned per-host driver-load baseline (a stable set of signed drivers loaded only by services.exe/wininit.exe) -> registry ImagePath write for ThrottleStop.sys -> the signed-vulnerable driver loaded by a non-standard process -> the host's Cortex sensor telemetry stream collapsing within seconds, anchored as one t0-tamper causality chain.
# The terminal ABIOC of the chain. A signed but vulnerable OEM driver (ThrottleStop.sys, CVE-2025-7771) — validly code-signed, so no known-bad-hash IOC applies — is loaded into the kernel by a non-standard loader process on a host whose learned driver-load baseline has never carried it. The ABIOC fires on the deviation (rare vulnerable driver + unexpected loader + first-seen-on-host) and anchors it to the causality chain driver-service-create -> vulnerable-driver-load -> sensor-telemetry-loss, catching the EDR-kill that the signature layer cannot.

dataset = xdr_data
| filter event_type = ENUM.LOAD_IMAGE and action_module_signature_status = "SIGNED"
| filter lowercase(action_module_path) contains "throttlestop.sys"
| filter actor_process_image_name not in ("services.exe", "wininit.exe", "smss.exe", "TrustedInstaller.exe")
| comp count() as anomalous_driver_loads by agent_hostname, action_module_path, actor_process_image_name
| filter anomalous_driver_loads >= 1
| fields agent_hostname, action_module_path, actor_process_image_name, anomalous_driver_loads

## ABIOC — Post-BYOVD Hands-on-Keyboard Burst on a Blinded Host — Recon and SystemBC C2 (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Sensor-telemetry gap on the blinded host -> a burst of distinct discovery/staging utilities (Advanced IP Scanner) plus a non-standard-port SystemBC beacon whose breadth and cadence exceed the host's learned process/network baseline, anchored to the causality process spawned after the BYOVD tamper.
# Immediately after the sensor-telemetry gap, the same host exhibits a rapid, out-of-baseline behavioral cluster the learned profile never produced: Advanced IP Scanner internal sweeps, an outbound beacon to a non-standard port matching SystemBC's cadence, and shadow-storage tampering. The ABIOC fires on the breadth-and-cadence deviation of this burst, anchored to the tamper event that immediately precedes it — no single tool here is a known-bad IOC.

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 900)
| filter (event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START and action_process_image_name in ("advanced_ip_scanner.exe", "advanced_port_scanner.exe")) or (event_type = ENUM.NETWORK and event_sub_type = ENUM.NETWORK_CONNECTION and action_remote_port not in (80, 443, 53, 8080) and dst_action_external_hostname != null)
| comp count_distinct(action_process_image_name) as recon_tools, count_distinct(action_remote_port) as beacon_ports, count() as burst_events by agent_hostname, actor_effective_username, causality_actor_process_image_name
| filter recon_tools >= 1 and beacon_ports >= 1
| sort desc burst_events
| fields agent_hostname, actor_effective_username, causality_actor_process_image_name, recon_tools, beacon_ports, burst_events

## VALIDATION — GentleKiller Vulnerable Driver Load Preceding EDR Telemetry Loss
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 900)
| filter event_type = ENUM.LOAD_IMAGE and lowercase(action_module_path) contains "throttlestop.sys"
| comp count() as driver_loads by agent_hostname, action_module_path, actor_process_image_name
| filter driver_loads >= 1
| fields agent_hostname, action_module_path, actor_process_image_name, driver_loads

## VALIDATION — GentleKiller Named Scheduled Task Creation (_gentlemen Pattern)
# purpose: hunt
# dataset: xdr_data

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_name = "schtasks.exe" and lowercase(action_process_image_command_line) contains "/create"
| filter lowercase(action_process_image_command_line) contains "_gentlemen"
| comp count() as task_creations by agent_hostname, actor_effective_username, action_process_image_command_line
| filter task_creations >= 1
| fields agent_hostname, actor_effective_username, action_process_image_command_line, task_creations

