# TTP-2026-0118 — GlobalProtect Authentication Bypass — Fully Connected VPN Session with No Preceding Authentication (PAN-OS CVE-2026-0257)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — GlobalProtect Gateway-Connected Session with Placeholder PoC Client Fingerprint
# severity: critical
# A successful GlobalProtect gateway-connected event whose client fingerprint matches the public CVE-2026-0257 PoC: one of the placeholder MAC addresses (aa:bb:cc:dd:ee:ff, 00:11:22:33:44:55) or one of the template machine names (WINDOWS-LAPTOP-001, DESKTOP-GP01, GP-CLIENT). A real endpoint never presents these values, so a match on an established tunnel is a high-confidence bypass indicator.

dataset = panw_ngfw_globalprotect_raw
| filter log_type = "globalprotect" and event_id = "gateway-connected" and status = "success"
| filter endpoint_mac in ("aa:bb:cc:dd:ee:ff", "00:11:22:33:44:55") or machine_name in ("WINDOWS-LAPTOP-001", "DESKTOP-GP01", "GP-CLIENT")
| fields _time, public_ip, source_user, source_user_domain, machine_name, endpoint_mac, endpoint_os_version

## BIOC — GlobalProtect Gateway-Connected Success With No Preceding Authentication Event
# severity: high
# A successful GlobalProtect gateway-connected event with no preceding successful portal/gateway authentication for the same source — a fully established VPN tunnel whose upstream authentication step never occurred. This is the durable, fingerprint-independent behavioral core of the CVE-2026-0257 bypass: it keys on the missing authentication event rather than any mutable client attribute, so it still fires after an attacker rotates the placeholder MAC, template hostname, or OS string the fingerprint BIOC matches. On this corpus the missing-auth condition is carried as preceding_auth_event = "NONE"; against a live tenant, join gateway-connected successes against portal-auth/gateway-auth successes for the same source within the session window and keep the rows with no auth match.

dataset = panw_ngfw_globalprotect_raw
| filter log_type = "globalprotect" and event_id = "gateway-connected" and status = "success"
| filter preceding_auth_event = "NONE"
| fields _time, public_ip, source_user, source_user_domain, machine_name, endpoint_mac, endpoint_os_version, preceding_auth_event

## BIOC — GlobalProtect Gateway Connection from Known CVE-2026-0257 Exploitation Infrastructure
# severity: high
# A successful GlobalProtect gateway-connected event whose public source IP matches one of the nine pre-PoC-release CVE-2026-0257 exploitation IPs Unit 42 published. Implements the vendor guidance to hunt GlobalProtect logs for successful gateway-connected events from the known attacker infrastructure.

dataset = panw_ngfw_globalprotect_raw
| filter event_id = "gateway-connected" and status = "success"
| filter public_ip in ("23.128.228.6", "104.207.144.154", "146.19.216.119", "146.19.216.120", "146.19.216.125", "179.43.172.213", "185.195.232.139", "198.12.106.60", "202.144.192.47")
| fields _time, public_ip, source_user, source_user_domain, machine_name, endpoint_mac

## VALIDATION — GlobalProtect PoC Fingerprint Session Observed
# purpose: validation
# dataset: panw_ngfw_globalprotect_raw

dataset = panw_ngfw_globalprotect_raw
| filter _time > to_timestamp(current_time() - 900)
| filter event_id = "gateway-connected"
| filter endpoint_mac in ("aa:bb:cc:dd:ee:ff", "00:11:22:33:44:55") or machine_name in ("WINDOWS-LAPTOP-001", "DESKTOP-GP01", "GP-CLIENT") or endpoint_os_version = "Microsoft Windows 10 Pro 64-bit"
| comp count() as fingerprint_sessions by public_ip, machine_name, endpoint_mac
| filter fingerprint_sessions >= 1
| fields public_ip, machine_name, endpoint_mac, fingerprint_sessions

## VALIDATION — Hunt GlobalProtect Gateway-Connected Events from CVE-2026-0257 Infrastructure
# purpose: hunt
# dataset: panw_ngfw_globalprotect_raw

dataset = panw_ngfw_globalprotect_raw
| filter _time > to_timestamp(current_time() - 2592000)
| filter event_id = "gateway-connected" and status = "success"
| filter public_ip in ("23.128.228.6", "104.207.144.154", "146.19.216.119", "146.19.216.120", "146.19.216.125", "179.43.172.213", "185.195.232.139", "198.12.106.60", "202.144.192.47")
| comp count() as connections by public_ip, source_user, machine_name
| sort desc connections
| fields public_ip, source_user, machine_name, connections

