# TTP-2026-0177 — USB Removable Media Exfiltration of Sensitive Customer Records
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — PCI and PII Data Staging
# severity: high
# PCI and PII Data Staging

preset = xdr_data | filter event_type = 'FILE_WRITE' and (action_file_name contains 'pci' or action_file_name contains 'pii') and (action_file_path contains '/tmp/' or action_file_path contains 'AppData')

## BIOC — USB Media Data Copy
# severity: high
# USB Media Data Copy

preset = xdr_data | filter event_type = 'FILE_WRITE' and (action_file_device_type = 'REMOVABLE' or action_file_path contains 'mock_usb' or action_file_path contains 'Volumes' or action_file_path contains 'media') and (action_file_name contains '.csv' or action_file_name contains '.xlsx')

## VALIDATION — Endpoint DLP Removable Media Transfer
# purpose: hunt

dataset = xdr_data | filter event_sub_type in ('FILE_CREATED', 'FILE_MODIFIED') | filter action_file_path contains 'usb' or action_file_device_type = 'REMOVABLE' | comp count() as writes by agent_hostname, actor_process_username | filter writes >= 1

