# TTP-2026-0079 — TIM Resource-Development Detection — Adversary Infrastructure Staging Surfaced From the Defender Vantage (T1583.001 / T1608.001 / T1585)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — TIM-002 Resolution of Newly-Registered Look-Alike Domain From Adversary Infrastructure Feed
# severity: high
# An estate host resolves a TAXII-fed newly-registered look-alike / staged-capability subdomain (.internal C2 zone) that TIM has armed as a Resource-Development indicator. Behavioral leg that catches the adversary's acquired domain the instant it is reached — before any payload runs.

dataset = pan_dns
| filter dns_query_name contains_any ("payload-delivery.", "dga-1a2b3c.", "cortexsim-tim-update.")
| filter dns_query_name contains ".internal"
| join type=inner (
    dataset = threat_intel
    | filter feed_source = "mocktaxii"
    | filter indicator_type = "domain-name"
    | fields indicator_value
  ) as feed on dns_query_name = feed.indicator_value
| fields _time, src_ip, dns_query_name, dns_response_ip

## VALIDATION — TIM-002 Pre-flight — Resource-Development Indicators Ingested Into Threat Intel
# purpose: validation
# dataset: threat_intel

dataset = threat_intel
| filter _time > to_timestamp(current_time() - 86400)
| filter feed_source = "mocktaxii" or feed_name contains "mocktaxii"
| filter indicator_type in ("domain-name", "ipv4-addr", "file-sha256")
| comp count() as indicators by indicator_type
| filter indicators >= 1
| fields indicator_type, indicators

## VALIDATION — TIM-002 IOC Match — Outbound Fetch From TAXII-Fed Staged-Capability Host
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter app in ("web-browsing", "http", "ssl")
| filter dst_host contains_any ("payload-delivery.", "dga-1a2b3c.", "cortexsim-tim-update.")
| join type=inner (
    dataset = threat_intel
    | filter feed_source = "mocktaxii"
    | filter indicator_type = "domain-name"
    | fields indicator_value
  ) as feed on dst_host = feed.indicator_value
| comp count() as ioc_hits, count_distinct(dst_host) as matched_indicators by src_ip
| filter ioc_hits >= 1
| fields src_ip, matched_indicators, ioc_hits

## VALIDATION — TIM-002 Newly-Registered Look-Alike Domain Resolution Surfaced (NDR DNS leg)
# purpose: validation
# dataset: pan_dns

dataset = pan_dns
| filter _time > to_timestamp(current_time() - 1800)
| filter dns_query_name contains_any ("payload-delivery.", "dga-1a2b3c.", "cortexsim-tim-update.")
| filter dns_query_name contains ".internal"
| comp count() as resolutions, count_distinct(dns_query_name) as distinct_lookalikes by src_ip
| filter resolutions >= 1
| fields src_ip, distinct_lookalikes, resolutions

## VALIDATION — TIM-002 Stitch — Resource-Development Feed Match Joined to Resolution and Session on Source Host
# purpose: validation
# dataset: network_story

dataset = network_story
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host contains ".internal"
| join type=inner (
    dataset = threat_intel
    | filter feed_source = "mocktaxii"
    | filter indicator_type = "domain-name"
    | fields indicator_value
  ) as feed on dst_host = feed.indicator_value
| comp count_distinct(dst_host) as matched_iocs, count() as sessions, min(_time) as first_seen, max(_time) as last_seen by src_ip
| filter matched_iocs >= 1
| fields src_ip, matched_iocs, sessions, first_seen, last_seen

## VALIDATION — TIM-002 Staged Second-Stage Payload Hash Seen On Estate (T1608.001)
# purpose: hunt
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 86400)
| filter event_type = ENUM.FILE
| filter action_file_sha256 in ("9f2c4b7e1a3d5f6082b4c6d8e0a2f4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6f8")
| comp count() as observed by agent_hostname, action_file_path
| fields agent_hostname, action_file_path, observed

