# TTP-2026-0152 — Auto-Revoke OAuth Tokens on Connected-App Abuse — Salesforce Bulk Export -> Playbook Revoke + Forced Re-Auth (F5)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — Connected-App OAuth Token Mass-Export Deviation Triggering Auto-Revoke (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned Connected-App integration baseline (low-volume scheduled Bulk API on a narrow object set) -> already-consented OAuth token drives a high-volume multi-object export, anchored to the connected_app + oauth_token_id that owns the grant. This anomaly is the automation trigger for the token-revoke playbook.
# A Salesforce Connected-App OAuth token whose learned baseline is low-volume, narrow-object scheduled Bulk API jobs suddenly runs a high-volume export across Account/Contact/Case/Opportunity from the automation exfil user-agent. This is the behavioral trigger the XSOAR auto-revoke playbook responds to. The ABIOC anchors the deviation to the Connected-App identity (connected_app + oauth_token_id) rather than to any known-bad string — no consent, MFA, or interactive login event exists to alert on, so the volume/object-diversity deviation on the trusted token is the signal.

dataset = cloud_audit_logs
| filter cloud_service = "salesforce" and event_type = "BulkApi" and api_type = "Bulk"
| filter operation in ("query", "queryAll")
| filter object_name in ("Account", "Contact", "Case", "Opportunity")
| comp sum(rows_processed) as run_rows, count_distinct(object_name) as run_objects by connected_app, integration_user, oauth_token_id, user_agent
| filter run_rows >= 50000 and run_objects >= 3
| sort desc run_rows
| fields connected_app, integration_user, oauth_token_id, user_agent, run_rows, run_objects

## VALIDATION — Salesforce Query-Job Deletion Anti-Forensics by Exfiltration Token
# purpose: hunt
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 3600)
| filter cloud_service = "salesforce" and api_type = "Bulk" and operation = "deleteJob"
| filter user_agent = "Python/3.11 aiohttp/3.12.15"
| comp count() as deleted_jobs by connected_app, integration_user, oauth_token_id, user_agent
| filter deleted_jobs >= 1
| sort desc deleted_jobs
| fields connected_app, integration_user, oauth_token_id, deleted_jobs

## VALIDATION — SOAR Playbook OAuth Access and Refresh Token Revocation for Connected App
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 3600)
| filter cloud_service = "salesforce" and event_type = "OAuthToken"
| filter operation in ("revokeAccessToken", "revokeRefreshToken", "revokeToken")
| filter action_source = "cortex-xsoar-playbook"
| comp count_distinct(token_type) as revoked_token_types, count() as revoke_events by connected_app, oauth_token_id, playbook_name
| filter revoked_token_types >= 2
| sort desc revoke_events
| fields connected_app, oauth_token_id, playbook_name, revoked_token_types, revoke_events

## VALIDATION — Forced Re-Authentication Requirement Applied to Affected Connected-App Admins
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 3600)
| filter cloud_service = "salesforce" and event_type = "SessionSecurity"
| filter operation = "forceReauth" and action_source = "cortex-xsoar-playbook"
| comp count() as forced_reauth_events by connected_app, affected_user
| filter forced_reauth_events >= 1
| sort desc forced_reauth_events
| fields connected_app, affected_user, forced_reauth_events

## VALIDATION — Revoked-Token Replay Returns 401 invalid_token Closed-Loop Proof
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 3600)
| filter cloud_service = "salesforce" and event_type = "ApiAuth"
| filter user_agent = "Python/3.11 aiohttp/3.12.15"
| filter response_status = 401 and error_code = "invalid_token"
| comp count() as rejected_calls, max(_time) as last_rejection by connected_app, integration_user, oauth_token_id
| filter rejected_calls >= 1
| sort desc rejected_calls
| fields connected_app, integration_user, oauth_token_id, rejected_calls, last_rejection

