# TTP-2026-0098 — Collection and Data-Staging Behavioral Anomaly — Cortex ABIOC (T1074.001 / T1560.001 / T1005)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — EDR-012 Anomalous Bulk File-Read Sweep from Non-Staging Process (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned non-staging process baseline (bounded file set, no bulk reads) -> service CGO (causality_actor_process_image_name = apache2/httpd/nginx, effective user www-data) -> bulk file-read sweep whose file diversity exceeds the learned baseline, keyed on the causality_actor and actor_process_instance_id rather than any known-bad path.
# A service process whose learned Cortex behavioral profile touches a narrow, stable set of files suddenly reads a fan-out of distinct files across the filesystem. ABIOC anchors the read-count-and-diversity deviation to the causality chain (service process -> bulk read sweep) rather than to any known-bad path, catching pre-exfil collection that a static rule keyed on a bad file or binary would miss.

dataset = xdr_data
| filter event_type = ENUM.FILE and event_sub_type = ENUM.FILE_OPEN
| filter actor_effective_username in ("www-data", "node", "nobody")
| filter causality_actor_process_image_name in ("apache2", "httpd", "nginx", "node")
| filter actor_process_image_name in ("cat", "dd", "cp", "tar", "find")
| comp count_distinct(action_file_path) as distinct_files, values(actor_process_instance_id) as proc_instances by agent_hostname, actor_effective_username, causality_actor_process_image_name
| filter distinct_files >= 5
| sort desc distinct_files
| fields agent_hostname, actor_effective_username, causality_actor_process_image_name, distinct_files, proc_instances

## ABIOC — EDR-012 Archive/Compression Staging Burst Deviating from Process Baseline (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Bulk file-read sweep under the service CGO (causality_actor_process_image_name = apache2/httpd/nginx) -> archive/compression process (tar/gzip) writing a staging artifact the process has never produced, keyed on the shared causality_actor and actor_process_instance_id that fed the archive.
# A service process whose learned baseline never produces archives spawns tar/gzip/zip to compress swept files into a single staging artifact. Every utility is legitimate; the ABIOC fires on the archive-creation deviation from the process's learned behavior, anchored to the bulk-read sweep that fed it — the pre-exfil staging moment.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_effective_username in ("www-data", "node", "nobody")
| filter causality_actor_process_image_name in ("apache2", "httpd", "nginx", "node")
| filter action_process_image_name in ("tar", "gzip", "zip", "7z", "xz", "bzip2")
| filter action_process_command_line contains "-c" or action_process_command_line contains "tmp"
| comp count() as archive_ops, values(actor_process_instance_id) as proc_instances by agent_hostname, actor_effective_username, causality_actor_process_image_name, action_process_image_name
| filter archive_ops >= 1
| fields agent_hostname, actor_effective_username, causality_actor_process_image_name, action_process_image_name, archive_ops, proc_instances

## VALIDATION — EDR-012 Service Process Non-Staging Baseline Learned
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 600)
| filter actor_effective_username = "www-data"
| comp count_distinct(action_process_image_name) as baseline_tools by agent_hostname
| filter baseline_tools >= 1
| fields agent_hostname, baseline_tools

## VALIDATION — EDR-012 Staging Deviation Surfaced on Process Baseline
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 600)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_effective_username = "www-data"
| filter action_process_image_name in ("tar", "gzip", "zip")
| comp count() as staging_ops by agent_hostname
| filter staging_ops >= 1
| fields agent_hostname, staging_ops

