# TTP-2026-0124 — AzureHound Cloud-Identity Enumeration Stitch: Token Theft -> Non-Interactive Entra Sign-In -> Bulk Microsoft Graph Discovery (SIM-MP-014)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — MP-014 Browser Session-Token and Cookie Theft by Non-Browser Process
# severity: high
# A non-browser process reads multiple browser credential stores (saved-login and cookie/session-token databases). Infostealers such as Raccoon Stealer or Redline sweep these stores to lift session tokens later replayed against Entra ID; the browser reading its own store is normal, a non-browser process sweeping several stores in one burst is the endpoint anchor of the AzureHound chain.

dataset = xdr_data
| filter event_type = ENUM.FILE and event_sub_type = ENUM.FILE_OPEN
| filter action_file_path contains "Login Data" or action_file_path contains "cookies.sqlite" or action_file_path contains "logins.json" or action_file_path contains "key4.db"
| filter actor_process_image_name not in ("chrome", "chromium", "google-chrome", "msedge", "firefox", "firefox-bin", "cortex-agent")
| comp count_distinct(action_file_path) as stores_read by agent_hostname, actor_effective_username, actor_process_image_name, actor_process_instance_id
| filter stores_read >= 2
| fields agent_hostname, actor_effective_username, actor_process_image_name, actor_process_instance_id, stores_read

## BIOC — MP-014 AzureHound Microsoft Graph Reachability Probe
# severity: medium
# AzureHound issues a GET /v1.0/organization reachability probe against graph.microsoft.com before the bulk enumeration begins. Paired with the azurehound User-Agent this is an early, low-volume tell of the enumeration about to start.

dataset = cloud_audit_logs
| filter lowercase(user_agent) contains "azurehound"
| filter request_uri contains "/v1.0/organization" or request_uri contains "graph.microsoft.com/v1.0/organization"
| comp count() as probe_calls by identity_name, caller_ip, user_agent
| filter probe_calls >= 1
| fields identity_name, caller_ip, user_agent, probe_calls

## ABIOC — MP-014 Non-Interactive Entra Sign-In from Unusual Geo Post Token Theft (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-identity Entra sign-in baseline (interactive, in-region, known apps) -> stolen-token replay produces a non-interactive, out-of-region sign-in (impossible travel) that diverges from the baseline, anchored to the user_principal_name and signin_activity_id.
# A non-interactive Entra ID sign-in (stolen session/refresh-token replay) lands on a user principal from a geography that deviates from that identity's learned sign-in baseline (impossible travel). The ABIOC anchors the deviation to the cloud-identity profile (non-interactive token replay diverging from the user's usual interactive, in-region sign-ins) rather than to any single bad value.

dataset = msft_azure_ad_signin
| filter is_interactive = false
| comp count() as noninteractive_signins, values(signin_activity_id) as signin_activity_ids, count_distinct(location_country) as geo_count by user_principal_name, ip_address, app_display_name
| filter geo_count >= 2
| fields user_principal_name, ip_address, app_display_name, noninteractive_signins, geo_count, signin_activity_ids

## ABIOC — MP-014 AzureHound Bulk Microsoft Graph Enumeration Burst (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-identity Microsoft Graph read cadence -> AzureHound enumeration burst (>500 GET/hour across users/groups/roles) that exceeds the identity's learned volume, anchored to identity_name + caller_ip and correlated to the sign-in via signin_activity_id.
# A single identity drives a high-volume burst of Microsoft Graph GET enumeration (users, groups, roleManagement) carrying the azurehound User-Agent, far exceeding that identity's learned Graph read cadence. Every call is a legitimate Graph read; the ABIOC fires on the volumetric-and-cadence deviation from the identity's learned baseline, anchored to the caller identity and session.

dataset = cloud_audit_logs
| filter http_method = "GET"
| filter request_uri contains "graph.microsoft.com/v1.0/users" or request_uri contains "graph.microsoft.com/v1.0/groups" or request_uri contains "graph.microsoft.com/v1.0/roleManagement" or lowercase(user_agent) contains "azurehound"
| bin _time span = 60m
| comp count() as graph_calls by identity_name, user_agent, caller_ip, _time
| filter graph_calls > 500
| sort desc graph_calls
| fields identity_name, user_agent, caller_ip, graph_calls

## VALIDATION — MP-014 AzureHound User-Agent Present in Cloud Audit Logs
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 3600)
| filter lowercase(user_agent) contains "azurehound"
| comp count() as azurehound_calls by identity_name, caller_ip, user_agent
| filter azurehound_calls >= 1
| fields identity_name, caller_ip, user_agent, azurehound_calls

## VALIDATION — MP-014 High-Volume Graph Enumeration Above 500 Calls Per Hour
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 3600)
| filter http_method = "GET"
| filter request_uri contains "graph.microsoft.com"
| bin _time span = 60m
| comp count() as api_call_count by identity_name, user_agent, caller_ip, _time
| filter api_call_count > 500
| sort desc api_call_count
| fields identity_name, user_agent, caller_ip, api_call_count

## VALIDATION — MP-014 Cross-Plane Stitch Single Incident Spanning Endpoint and Cloud Identity
# purpose: metric
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 3600)
| comp count_distinct(_product) as plane_count, count_distinct(incident_id) as incident_count by causality_actor_primary_username
| filter plane_count >= 2 and incident_count = 1
| fields causality_actor_primary_username, plane_count, incident_count

