# TTP-2026-0047 — C2 Beacon Callback — NGFW + XDR Causality Stitch (T1071.001)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — MP-001 Interactive Shell Spawned From www-data Service Context
# severity: high
# XDR — interactive bash spawned from www-data service context. A non-login web service identity spawns an interactive shell, the endpoint leg of the C2 chain.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("bash", "sh")
| filter actor_effective_username in ("www-data", "nobody", "apache", "nginx")
| filter causality_actor_process_image_name in ("apache2", "nginx", "php-fpm", "node", "httpd")

## BIOC — MP-001 Curl Beacon With Suspicious User-Agent From www-data
# severity: high
# XDR — curl executed from www-data with suspicious user-agent. The endpoint process that opens the outbound HTTP beacon socket, providing the lineage leg the NGFW session lacks.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("curl", "wget")
| filter action_process_image_command_line contains_any ("CortexSimBeacon", "-A ", "--user-agent")
| filter actor_effective_username in ("www-data", "nobody", "apache", "nginx")
| filter causality_actor_process_image_name in ("apache2", "nginx", "php-fpm", "node", "httpd")

## BIOC — MP-001 Curl Wrote Second-Stage File To Tmp From Service Account
# severity: medium
# XDR — file written to /tmp/ by curl from service account. Ingress tool transfer: curl downloads a second stage into a world-writable path under a service identity.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter event_sub_type in (ENUM.FILE_CREATE_NEW, ENUM.FILE_WRITE)
| filter actor_process_image_name in ("curl", "wget")
| filter action_file_path contains "/tmp/"
| filter actor_effective_username in ("www-data", "nobody", "apache", "nginx")
| filter causality_actor_process_image_name in ("apache2", "nginx", "php-fpm", "node", "httpd")

## VALIDATION — MP-001 NGFW Repetitive HTTP Beacon To testmynids
# purpose: validation
# dataset: pan_ngfw_traffic

dataset = pan_ngfw_traffic
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host = "testmynids.org" and bytes_sent > 0
| comp count() as beacon_hits, count_distinct(dst_port) as ports by source_ip
| filter beacon_hits >= 5
| fields source_ip, beacon_hits, ports

## VALIDATION — MP-001 Stitch NGFW Session And XDR Process By Src Host
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter (event_type = ENUM.NETWORK and action_external_hostname = "testmynids.org") or (event_type = ENUM.PROCESS and actor_process_image_name = "curl")
| comp count_distinct(_product) as plane_count, count_distinct(incident_id) as incident_count by action_local_ip
| filter plane_count >= 2 and incident_count = 1
| fields action_local_ip, plane_count, incident_count

## VALIDATION — MP-001 NGFW DNS TXT High Entropy Burst
# purpose: validation
# dataset: pan_dns

dataset = pan_dns
| filter _time > to_timestamp(current_time() - 1800)
| filter dns_query_type = "TXT" and dns_query_name contains ".testmynids.org"
| comp count() as txt_queries, count_distinct(dns_query_name) as distinct_labels by source_ip
| filter txt_queries >= 10
| fields source_ip, txt_queries, distinct_labels

## VALIDATION — MP-001 Repetitive Dig TXT From Service Account
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("dig", "nslookup", "host")
| filter action_process_image_command_line contains "TXT"
| comp count() as dig_count by agent_hostname, actor_effective_username
| filter dig_count >= 10
| fields agent_hostname, actor_effective_username, dig_count

## VALIDATION — MP-001 Stitch DNS Exfil With Process Lineage
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter (event_type = ENUM.PROCESS and actor_process_image_name = "dig") or (event_type = ENUM.NETWORK and action_external_port = 53)
| comp count_distinct(_product) as plane_count, count_distinct(incident_id) as incident_count by action_local_ip
| filter plane_count >= 2 and incident_count = 1
| fields action_local_ip, plane_count, incident_count

## VALIDATION — MP-001 NGFW Download From IOC Listed Domain
# purpose: validation
# dataset: pan_ngfw_traffic

dataset = pan_ngfw_traffic
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host = "testmynids.org" and url contains "/uid/index.html"
| filter app in ("web-browsing", "http", "ssl")
| comp count() as download_hits by source_ip, dst_host
| fields source_ip, dst_host, download_hits

