# TTP-2026-0154 — AWS S3 Mass-Object Exfiltration by a Suspicious Identity — Cortex Analytics Behavioral IOC (ABIOC) (T1530)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — Suspicious identity downloaded multiple objects from a bucket (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-identity S3 object-access baseline (a few reads on known buckets) -> suspicious identity -> high-volume s3:GetObject read burst on one bucket from a source IP/user-agent new for this identity, anchored to that identity.
# A single IAM identity whose learned Cortex object-access baseline is a small, steady read of a handful of S3 objects suddenly issues a high-volume burst of s3:GetObject calls on one bucket, from a source new for that identity. The ABIOC anchors the mass-download deviation to the causality chain (suspicious identity -> GetObject read burst on one bucket) rather than to any single API name, catching bulk cloud-storage theft a static rule keyed on GetObject would drown in noise on.

dataset = cloud_audit_logs
| filter eventSource = "s3.amazonaws.com"
| filter eventName = "GetObject"
| filter isnull(errorCode)
| filter _time > to_timestamp(current_time() - 300)
| comp count() as object_downloads by userIdentityArn, bucket_name, sourceIPAddress
| filter object_downloads >= 50
| sort desc object_downloads
| fields userIdentityArn, bucket_name, sourceIPAddress, object_downloads

## ABIOC — An identity performed a suspicious download of multiple cloud storage objects (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Assumed/IAM identity -> high-volume s3:GetObject read burst on one bucket, anchored to the identity that first exhibited the mass download.
# An identity issues an anomalously high volume of s3:GetObject reads on one bucket, far above its learned per-bucket access volume. Every read is a legitimate call; the ABIOC fires on the read-volume deviation from the identity's learned cloud-storage behavior, anchored to the high-volume download burst on the same bucket.

dataset = cloud_audit_logs
| filter eventSource = "s3.amazonaws.com"
| filter eventName = "GetObject"
| filter isnull(errorCode)
| filter _time > to_timestamp(current_time() - 600)
| comp count() as objects_read by userIdentityArn, bucket_name
| filter objects_read >= 50
| sort desc objects_read
| fields userIdentityArn, bucket_name, objects_read

## VALIDATION — SIM-CDR-019 S3 GetObject Burst Surfaced in Cloud Audit Log
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 900)
| filter eventSource = "s3.amazonaws.com"
| filter eventName = "GetObject"
| comp count() as s3_read_events by userIdentityArn, bucket_name
| filter s3_read_events >= 1
| sort desc s3_read_events
| fields userIdentityArn, bucket_name, s3_read_events

## VALIDATION — SIM-CDR-019 Suspicious-Identity Download Fan-Out By Bucket
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 900)
| filter eventSource = "s3.amazonaws.com"
| filter eventName = "GetObject"
| comp count() as object_downloads by userIdentityArn, bucket_name, sourceIPAddress
| filter object_downloads >= 1
| sort desc object_downloads
| fields userIdentityArn, bucket_name, sourceIPAddress, object_downloads

