# TTP-2026-0119 — ASPX Web Shell Reflectively Loads a Fileless .NET IIS Backdoor into w3wp.exe (Phantom Taurus NET-STAR) (T1505.003 / T1620 / T1071.001)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — IIS Worker Process w3wp.exe Spawns a Command Interpreter
# severity: high
# The IIS worker process w3wp.exe should never parent an interactive command interpreter under normal operation. When it does, it is the durable, non-fileless seam of a web shell running operator commands. Fires on w3wp.exe as the causality actor spawning cmd/powershell/net/whoami/sqlcmd/csc — the command lineage NET-STAR's run_code / executeSQLQuery / bypassPrecompiledApp commands produce even though the backdoor assembly itself is in memory.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter causality_actor_process_image_name = "w3wp.exe" or actor_process_image_name = "w3wp.exe"
| filter action_process_image_name in ("cmd.exe", "powershell.exe", "pwsh.exe", "net.exe", "net1.exe", "whoami.exe", "sqlcmd.exe", "csc.exe")
| fields agent_hostname, actor_process_image_name, action_process_image_name, action_process_image_command_line

## BIOC — OutlookEN ASPX Web Shell Written to IIS Web Root
# severity: high
# Creation of an .aspx file (OutlookEN.aspx and its kin) under the IIS web root by the worker process or an interactive shell — the on-disk delivery artifact that seeds the fileless chain. This is the one file NET-STAR must drop before everything else goes memory-resident, so it is the earliest reliable catch.

dataset = xdr_data
| filter event_type = ENUM.FILE and event_sub_type in (ENUM.FILE_CREATE_NEW, ENUM.FILE_WRITE)
| filter action_file_extension = "aspx" or action_file_name contains ".aspx"
| filter action_file_path contains "inetpub" or action_file_path contains "wwwroot"
| filter actor_process_image_name in ("w3wp.exe", "cmd.exe", "powershell.exe", "pwsh.exe")
| fields agent_hostname, actor_process_image_name, action_file_name, action_file_path

## BIOC — Reflective Fileless .NET Assembly Load in IIS Worker Process
# severity: high
# IIServerCore and the AssemblyExecuter helpers are reflectively loaded into w3wp.exe from memory, so the loaded module has no backing file on disk (unsigned / no module path) or carries the NET-STAR build names. Fires on module-load events in w3wp.exe whose module is unbacked or named ServerCore/ExecuteAssembly/AssemblyExecuter — the reflective code-loading seam.

dataset = xdr_data
| filter event_type = ENUM.MODULE and event_sub_type = ENUM.MODULE_LOAD
| filter actor_process_image_name = "w3wp.exe"
| filter action_module_path = "" or action_module_signature_status = "UNSIGNED" or action_module_name contains "ServerCore" or action_module_name contains "ExecuteAssembly" or action_module_name contains "AssemblyExecuter"
| fields agent_hostname, actor_process_image_name, action_module_name, action_module_path, action_module_signature_status

## BIOC — AMSI and CLR In-Memory Execution Modules Co-Loaded in IIS Worker
# severity: medium
# In-memory .NET execution inside w3wp.exe co-loads the CLR (clr.dll / clrjit.dll) alongside amsi.dll, and AssemblyExecuter V2 patches AMSI/ETW to blind the scanner. An IIS worker that suddenly hosts the CLR plus amsi.dll is the fingerprint of reflectively executed .NET where none belongs. Fires when w3wp.exe loads two or more of these execution/evasion modules within one process instance.

dataset = xdr_data
| filter event_type = ENUM.MODULE and event_sub_type = ENUM.MODULE_LOAD
| filter actor_process_image_name = "w3wp.exe"
| filter action_module_name in ("amsi.dll", "clr.dll", "clrjit.dll", "mscoree.dll", "coreclr.dll")
| comp count_distinct(action_module_name) as exec_modules by agent_hostname, actor_process_instance_id
| filter exec_modules >= 2
| fields agent_hostname, actor_process_instance_id, exec_modules

## BIOC — ASPX Web Root File Timestomped via changeLastModified
# severity: medium
# NET-STAR's changeLastModified command forges file modification times on web-root artifacts to match legitimate neighbours, and forges compile timestamps to random future dates. Fires when a web-root file's modification time predates its creation time or is set in the future — the timestomp anti-forensic seam.

dataset = xdr_data
| filter event_type = ENUM.FILE and event_sub_type = ENUM.FILE_TIMES_MODIFIED
| filter action_file_extension = "aspx" or action_file_path contains "wwwroot" or action_file_path contains "inetpub"
| filter action_file_modification_time < action_file_creation_time or action_file_modification_time > current_time()
| fields agent_hostname, actor_process_image_name, action_file_name, action_file_path, action_file_creation_time, action_file_modification_time

## VALIDATION — Web Shell Command Execution Lineage Under w3wp.exe
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 900)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter causality_actor_process_image_name = "w3wp.exe" or actor_process_image_name = "w3wp.exe"
| comp count() as child_processes by agent_hostname, action_process_image_name
| sort desc child_processes
| fields agent_hostname, action_process_image_name, child_processes

## VALIDATION — Cookie-Based STAR-Delimited C2 to IIS Host
# purpose: validation
# dataset: network_story

dataset = network_story
| filter _time > to_timestamp(current_time() - 900)
| filter request_cookies contains "STAR" or request_headers contains "STAR"
| filter uri_path contains ".aspx" or app_id_transitions contains "web-browsing"
| comp count() as star_requests by agent_hostname, dst_ip, dst_port
| filter star_requests >= 1
| fields agent_hostname, dst_ip, dst_port, star_requests

