# TTP-2026-0018 — Prisma Browser — Drive-by Download from Phishing Page (T1189)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — Prisma Browser — auto-download initiated by JS without user gesture
# severity: high
# Prisma Browser — auto-download initiated by JS without user gesture. A file download begins programmatically (no click / no user gesture) from a page the managed browser rendered.

dataset = prisma_browser_events
| filter action = "download"
| filter user_gesture = false
| filter file_name != null
| filter origin not in ("drive.google.com", "onedrive.live.com", "box.com")

## VALIDATION — Pre-flight: plugin metadata visible to operator
# purpose: validation
# dataset: prisma_browser_events

dataset = prisma_browser_events
| filter _time > to_timestamp(current_time() - 1800)
| filter campaign_id = "BC-BROWSER-002"
| filter action in ("navigate", "download")
| fields _time, campaign_id, action, origin, url, file_name
| sort asc _time

## VALIDATION — Prisma Browser — downloaded artifact MIME application/x-msdownload from non-SaaS origin
# purpose: validation
# dataset: prisma_browser_events

dataset = prisma_browser_events
| filter _time > to_timestamp(current_time() - 1800)
| filter action = "download"
| filter file_mime_type in ("application/x-msdownload", "application/x-dosexec", "application/octet-stream")
| filter origin not in ("drive.google.com", "onedrive.live.com", "box.com")
| fields _time, user, origin, url, file_name, file_mime_type, file_sha256
| sort desc _time

## VALIDATION — NGFW EAL — file-type download policy matches downloaded artifact
# purpose: validation
# dataset: panw_ngfw_threat_raw

dataset = panw_ngfw_threat_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter log_subtype = "file" or sub_type = "data"
| filter file_type in ("PE", "msdownload", "dll")
| filter dst_host = "phish.cortexsim-test.invalid" or url contains "q3-earnings-update"
| fields _time, src_ip, dst_host, app, file_name, file_type, action
| sort desc _time

## VALIDATION — PB → WildFire submission within download-policy MTTD
# purpose: validation
# dataset: prisma_browser_events

dataset = prisma_browser_events
| filter _time > to_timestamp(current_time() - 1800)
| filter action = "download" and wildfire_submitted = true
| fields _time, user, origin, file_name, file_sha256, wildfire_verdict
| sort desc _time

