# TTP-2026-0085 — Insecure Deployment Runtime Detonation — Busybox Pod Fetches Malware ELFs — Cortex Cloud CDR (T1610 / T1496)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — CDR-013 Busybox Container Fetches and Executes ELF
# severity: critical
# A minimal/busybox container wget-s an ELF binary from a public code-hosting repository and stages it executable (chmod +x), the insecure-deployment runtime-detonation shape the lab's busybox sidecars produce (T1610 Deploy Container into an insecure deployment). The fetch-from-public-repo + chmod-ELF combination distinguishes a malware drop from a normal image pull.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_container_info != null
| filter actor_process_image_name in ("wget", "curl", "busybox", "sh")
| filter action_process_image_command_line contains ".elf" or action_process_image_command_line contains "chmod +x"
| comp count() as elf_stage_events by agent_hostname, actor_process_image_name
| filter elf_stage_events >= 1
| sort desc elf_stage_events
| fields agent_hostname, actor_process_image_name, elf_stage_events

## VALIDATION — CDR-013 Container Workload Projection
# purpose: hunt
# dataset: xdr_data

dataset = xdr_data
| fields actor_container_info as container_info
| filter container_info != null
| alter pod_namespace = json_extract_scalar(container_info, "$.pod_namespace")
| alter pod_name = json_extract_scalar(container_info, "$.pod_name")
| alter image_name = json_extract_scalar(container_info, "$.image_name")
| alter image_id = json_extract_scalar(container_info, "$.image_id")
| alter container_id = json_extract_scalar(container_info, "$.id")
| alter privileged = json_extract_scalar(container_info, "$.privileged")
| filter actor_process_image_name in ("wget", "curl", "busybox")

## VALIDATION — CDR-013 Malware ELF Retrieval from Public Repository
# purpose: validation
# dataset: network_story

dataset = network_story
| filter _time > to_timestamp(current_time() - 600)
| filter dst_host = "raw.githubusercontent.com" or action_external_hostname = "raw.githubusercontent.com"
| filter actor_process_image_name in ("wget", "curl", "busybox")
| comp count() as elf_pulls by agent_hostname, actor_process_image_name
| filter elf_pulls >= 1
| sort desc elf_pulls
| fields agent_hostname, actor_process_image_name, elf_pulls

