# TTP-2026-0070 — Internet-Exposed Attack-Surface Discovery & Enumeration (T1595 / T1046 / T1190)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — ASM EAL — Active-Scan Port Fan-Out Against Exposed Host
# severity: high
# A single source IP opens connections to an unusually large number of distinct destination ports on the exposed surface host within a short window — the nmap/nuclei active-scanning egress shape (T1595/T1046).

dataset = panw_ngfw_traffic_raw
| filter dst_port in (80, 443, 2222, 6379, 9001, 9200) or app in ("web-browsing", "ssl", "redis", "elasticsearch")
| filter src_ip != null and dst_ip != null
| bin _time span=5m
| comp count_distinct(dst_port) as scanned_ports, count() as session_count by src_ip, dst_ip, _time
| filter scanned_ports >= 5
| fields _time, src_ip, dst_ip, scanned_ports, session_count

## VALIDATION — ASM-001 Ground-Truth Manifest Capture Bookkeeping
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 1800)
| filter cloud_provider = "AWS"
| filter resource_tags contains "CortexSimASMFinding"
| comp count_distinct(resource_id) as planted_resources by resource_type
| fields resource_type, planted_resources

## VALIDATION — ASM Exposed-Service Discovery Findings By Port
# purpose: validation
# dataset: asm_findings

dataset = asm_findings
| filter _time > to_timestamp(current_time() - 86400)
| filter finding_type in ("exposed_service", "open_port", "weak_tls", "non_standard_port", "public_cloud_storage")
| filter tags contains "CortexSimASMFinding" or asset_external_ip = "${ASM_TARGET_HOST}"
| comp count() as findings by finding_type, service_port, service_name
| fields finding_type, service_port, service_name, findings

## VALIDATION — ASM EAL — Active-Scan Port Fan-Out (1 src to many ports on exposed host)
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_ip = "${ASM_TARGET_HOST}"
| filter dst_port in (80, 443, 2222, 6379, 9001, 9200)
| comp count_distinct(dst_port) as scanned_ports, count() as sessions by src_ip, dst_ip
| filter scanned_ports >= 5
| fields src_ip, dst_ip, scanned_ports, sessions

## VALIDATION — ASM High-Risk Exposure Roll-Up — Weak TLS, EOL Banner, Unauth Data Store
# purpose: hunt
# dataset: asm_findings

dataset = asm_findings
| filter _time > to_timestamp(current_time() - 86400)
| filter (finding_type = "weak_tls" and (tls_key_bits <= 1024 or tls_self_signed = true))
    or (finding_type = "vulnerable_service" and service_version contains "1.7.0")
    or (finding_type = "exposed_service" and service_name in ("redis", "elasticsearch") and service_auth = "none")
| comp count() as high_risk_findings by finding_type, service_name, service_version, risk_score
| sort desc risk_score
| fields finding_type, service_name, service_version, risk_score, high_risk_findings

