# TTP-2026-0097 — Ransomware Pre-Encryption Behavioral Anomaly on a Host — Cortex Analytics Behavioral IOC (ABIOC) (T1486 / T1490 / T1083)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — EDR-011 Anomalous Pre-Encryption File-Modification Burst Deviating from Host Baseline (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned host file-I/O baseline (few processes, modest low-entropy cadence) -> file enumeration -> single-process high-entropy mass rewrite whose rate exceeds the learned profile, anchored to the enumerating process lineage.
# A single process produces a rapid burst of high-entropy file writes/renames with a uniform new extension at a rate far above the host's learned file-modification profile. Every write uses legitimate syscalls and the encryptor may be a fresh, unhashed Akira build, so a signature BIOC misses it; the ABIOC fires on the rate-and-entropy deviation from the learned endpoint baseline, anchored to the enumeration-then-mass-rewrite causality chain rather than any known-bad extension or hash.

dataset = xdr_data
| filter event_type = ENUM.FILE and event_sub_type in (ENUM.FILE_WRITE, ENUM.FILE_RENAME)
| filter actor_process_image_name not in ("tar", "gzip", "rsync", "dpkg", "apt", "logrotate")
| comp count() as file_ops, count_distinct(action_file_extension) as ext_spread by agent_hostname, actor_process_instance_id, actor_process_image_name
| filter file_ops >= 200
| sort desc file_ops
| fields agent_hostname, actor_process_image_name, actor_process_instance_id, file_ops, ext_spread

## ABIOC — EDR-011 Recovery-Inhibition Snapshot Deletion Deviating from Host Baseline (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: High-entropy mass-rewrite burst on the host -> deletion of snapshot/backup artefacts the learned backup routine never removes, anchored to the co-occurring encryptor process.
# A process deletes snapshot/backup artefacts on a host whose learned backup routine only CREATES snapshots on a schedule and never bulk-deletes them. The deletion co-occurs with the high-entropy file-modification burst. The ABIOC fires on the recovery-inhibition deviation from the host's learned backup behavior, anchored to the mass-rewrite that immediately precedes it.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_name in ("rm", "shred", "btrfs", "lvremove", "vgremove", "unlink")
| filter action_process_command_line contains "snapshot" or action_process_command_line contains "backup" or action_process_command_line contains ".img"
| comp count() as recovery_inhibit_ops by agent_hostname, actor_effective_username
| filter recovery_inhibit_ops >= 1
| fields agent_hostname, actor_effective_username, recovery_inhibit_ops

## VALIDATION — EDR-011 Host File-Modification Baseline Learned
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 900)
| filter event_type = ENUM.FILE
| comp count() as file_ops by agent_hostname, actor_process_image_name
| filter file_ops >= 1
| sort desc file_ops
| fields agent_hostname, actor_process_image_name, file_ops

## VALIDATION — EDR-011 Pre-Encryption File Burst Surfaced on Host
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 900)
| filter event_type = ENUM.FILE and event_sub_type in (ENUM.FILE_WRITE, ENUM.FILE_RENAME)
| comp count() as burst_ops by agent_hostname, actor_process_image_name
| filter burst_ops >= 50
| sort desc burst_ops
| fields agent_hostname, actor_process_image_name, burst_ops

