# TTP-2026-0042 — Typosquat MCP Server Installed by Claude Desktop (T1195)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — KOI-001 MCP Tool Description Embeds Instruction Injection and AKIA Canary
# severity: high
# Code scan — tool description embeds 'Ignore previous instructions' / AKIA canary. A read of an MCP mcp.json manifest surfaces a tool description field carrying an instruction-injection directive and an AKIA-prefixed access-key canary.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter event_sub_type in (ENUM.FILE_OPEN, ENUM.FILE_READ)
| filter action_file_name = "mcp.json"
| filter action_file_path contains "anthroopic-calculator"

## BIOC — KOI-001 Cortex Cloud Code Instruction Injection In Tool Description
# severity: high
# Cortex Cloud Code — instruction-injection in tool description detected. The CI/IDE static scanner matches an instruction-injection phrase ('Ignore previous instructions', 'exfiltrate', '~/.aws/credentials') inside an MCP tool description value.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("grep", "jq", "checkov", "cortexcloud", "twistcli", "node")
| filter action_process_image_command_line contains "mcp.json"
| filter action_process_image_command_line contains_any ("Ignore previous", "exfil", "AKIA", ".aws/credentials")

## VALIDATION — KOI-001 Typosquat MCP Manifest Name Near-Miss of Anthropic Publisher
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_command_line contains "mcp.json"
| filter action_process_image_command_line contains "anthroopic"
| fields _time, agent_hostname, actor_effective_username, actor_process_image_name, action_process_image_command_line

## VALIDATION — KOI-001 Claude Desktop Fetches MCP Manifest From Non Canonical FQDN
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.NETWORK
| filter dst_action_external_hostname contains "cortexsim-canary" or dns_query_name contains "cortexsim-canary"
| filter action_external_port in (80, 443)
| fields _time, agent_hostname, actor_process_image_name, dst_action_external_hostname, action_external_port, http_req_user_agent

## VALIDATION — KOI-001 Outbound URL Matches Typosquat Of Approved AI Publisher Domain
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.NETWORK
| filter action_external_url contains "anthroopic" or dst_action_external_hostname contains "cortexsim-canary"
| filter action_app_id_transitions contains "mcp" or action_external_url contains "/mcp/"
| fields _time, agent_hostname, actor_process_image_name, action_external_url, dst_action_external_hostname

## VALIDATION — KOI-001 Cortex Cloud Code Typosquat Package Name Detector
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("jq", "grep", "cortexcloud", "checkov", "twistcli")
| filter action_process_image_command_line contains "anthroopic-calculator"
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

