# TTP-2026-0143 — ITDR — Closed-Loop Auto-Disable of a Compromised Account (Impossible-Travel + Privilege Anomaly → SOAR Suspend + Session Revoke)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — ITDR-016 Impossible-Travel Sign-In Deviation on Target Identity (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-identity sign-in baseline (single region, stable ASN set) -> a valid-account session pair from distant geographies/ASNs inside a travel-impossibility window, anchored to the target identity as the shared entity that carries into the escalation and remediation signals.
# The compromised identity succeeds at two sign-ins from geographically distant locations / distinct ASNs inside a travel-impossibility window, deviating from the single-region, stable-ASN sign-in profile Cortex learned for the account. The credentials are valid and each session in isolation is benign; the ABIOC fires on the geo/ASN-velocity deviation from the learned baseline, anchored to the session pair from one stolen-credential intrusion — the first of the two signals that trips the account-takeover correlation.

dataset = okta_sso
| filter _time > to_timestamp(current_time() - 1800)
| filter eventType = "user.session.start" and auth_outcome = "SUCCESS"
| comp count_distinct(src_geo_country) as geo_count, count_distinct(src_asn) as asn_count, values(src_geo_city) as cities, earliest(_time) as first_seen, latest(_time) as last_seen by actor_effective_username
| alter window_minutes = divide(subtract(last_seen, first_seen), 60000000)
| filter geo_count >= 2 and asn_count >= 2 and window_minutes <= 300
| sort desc geo_count
| fields actor_effective_username, geo_count, asn_count, cities, window_minutes, first_seen, last_seen

## ABIOC — ITDR-016 Anomalous Privilege Grant and MFA Reset on the Compromised Identity (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Impossible-travel valid-account auth on the target identity -> an anomalous privileged-role grant and/or MFA-factor reset on the SAME identity that diverges from its learned governance baseline, anchored to the compromise session as the shared entity.
# The same identity that just tripped the impossible-travel deviation is granted an anomalous privileged role (admin/privileged-role assignment) and/or has an MFA factor reset — the escalation-and-persistence move Muddled Libra uses after takeover. Every action uses a legitimate Okta administrative API; the ABIOC fires on the deviation from the identity's learned governance baseline, anchored to the impossible-travel sign-in that preceded it, and supplies the second signal the account-takeover correlation fuses.

dataset = okta_sso
| filter _time > to_timestamp(current_time() - 1800)
| filter eventType in ("user.account.privilege.grant", "user.mfa.factor.reset") and auth_outcome = "SUCCESS"
| comp count() as privilege_events, count_distinct(eventType) as distinct_actions, values(eventType) as actions, values(actor_effective_username) as actor by actor_effective_username
| filter privilege_events >= 1
| sort desc privilege_events
| fields actor_effective_username, privilege_events, distinct_actions, actions, actor

## VALIDATION — ITDR-016 Containment Playbook Remediation Events Fired
# purpose: validation
# dataset: okta_sso

dataset = okta_sso
| filter _time > to_timestamp(current_time() - 1800)
| filter eventType in ("user.lifecycle.suspend", "user.session.clear")
| comp count() as remediation_events, count_distinct(eventType) as distinct_actions, values(eventType) as actions, values(actor_effective_username) as remediation_actor by actor_effective_username
| filter distinct_actions >= 2
| fields actor_effective_username, remediation_events, distinct_actions, actions, remediation_actor

## VALIDATION — ITDR-016 Closed-Loop Remediation SLA Measurement
# purpose: metric
# dataset: okta_sso

dataset = okta_sso
| filter _time > to_timestamp(current_time() - 3600)
| filter eventType in ("user.account.privilege.grant", "user.mfa.factor.reset", "user.lifecycle.suspend", "user.session.clear")
| comp latest(if(eventType in ("user.account.privilege.grant", "user.mfa.factor.reset"), _time, null)) as alert_ts, latest(if(eventType in ("user.lifecycle.suspend", "user.session.clear"), _time, null)) as remediation_ts by actor_effective_username
| filter alert_ts != null and remediation_ts != null
| alter sla_seconds = divide(subtract(remediation_ts, alert_ts), 1000000)
| filter sla_seconds >= 0 and sla_seconds <= 300
| fields actor_effective_username, alert_ts, remediation_ts, sla_seconds

## VALIDATION — ITDR-016 Impossible-Travel Compromise Signal Surfaced
# purpose: validation
# dataset: okta_sso

dataset = okta_sso
| filter _time > to_timestamp(current_time() - 1800)
| filter eventType = "user.session.start" and auth_outcome = "SUCCESS"
| comp count_distinct(src_geo_country) as geo_count, count_distinct(src_asn) as asn_count by actor_effective_username
| filter geo_count >= 2 and asn_count >= 2
| fields actor_effective_username, geo_count, asn_count

