# TTP-2026-0004 — DCSync — Domain Replication Abuse for Credential Extraction (T1003.006)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — DRSUAPI Replication Request From Non-DC Host
# severity: critical
# A host that is NOT a domain controller initiates a DRSUAPI (MS-DRSR) RPC call to a DC requesting directory changes — the network signature of DCSync.

preset = xdr_data
| filter event_type = ENUM.NETWORK
| filter event_sub_type = ENUM.NETWORK_RPC
| filter rpc_interface_uuid = "e3514235-4b06-11d1-ab04-00c04fc2dcd2"
| filter rpc_opnum in (0,3)  // DRSBind, DRSGetNCChanges
| filter dst_host in (active_directory.domain_controllers)
| filter src_host not in (active_directory.domain_controllers)

## BIOC — Windows Event 4662 — Replicating Directory Changes by Non-DC Principal
# severity: critical
# DC audit log shows access to the directory replication GUID by a principal that is not a DC computer account.

dataset = msft_windows_security
| filter event_id = 4662
| filter properties contains "1131f6aa-9c07-11d1-f79f-00c04fc2dcd2"
| filter subject_user_name not_match "^[A-Z0-9-]+\\$$"  // strip computer accounts
| filter subject_user_name not in (active_directory.dc_computer_accounts)

## BIOC — Mimikatz dcsync Command-Line Pattern
# severity: critical
# Process start with command line containing `dcsync` or `lsadump::dcsync`.

preset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_command_line contains_any ("dcsync", "lsadump::dcsync")

## VALIDATION — Confirm DRSUAPI replication request seen from non-DC in last 30m
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.NETWORK and event_sub_type = ENUM.NETWORK_RPC
| filter rpc_interface_uuid = "e3514235-4b06-11d1-ab04-00c04fc2dcd2"
| fields _time, src_host, dst_host, rpc_opnum, src_user_name

## VALIDATION — Confirm 4662 replication event on DC
# purpose: validation
# dataset: msft_windows_security

dataset = msft_windows_security
| filter _time > to_timestamp(current_time() - 1800)
| filter event_id = 4662 and properties contains "1131f6aa-9c07-11d1-f79f-00c04fc2dcd2"
| fields _time, hostname, subject_user_name, object_name

## VALIDATION — Accounts granted replication rights in last 30d (latent DCSync risk)
# purpose: hunt

dataset = msft_windows_security
| filter event_id in (5136, 4670)
| filter attribute_ldap_display_name in ("nTSecurityDescriptor")
| filter properties contains_any ("Replicating Directory Changes", "DS-Replication-Get-Changes")
| fields _time, subject_user_name, target_user_name

