# TTP-2026-0008 — AI Access — AWS Access Key Leaked to Anthropic API
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — AIACC-002 Pre-flight Secret Payload Contains AKIA Canary
# severity: informational
# Pre-flight: secret payload contains AKIA-prefixed canary. Confirms the secret payload renders the AKIA0000CORTEXSIMCANARY marker on the worker before any egress; matches the python self-check process invocation.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("python", "python3")
| filter action_process_image_command_line contains "_render_payload"
| filter action_process_image_command_line contains "AKIA0000CORTEXSIMCANARY"

## VALIDATION — AIACC-002 POST to Anthropic From Non-Sanctioned User Context
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host = "api.anthropic.com" or tls_sni = "api.anthropic.com"
| filter http_method = "POST" and uri_path contains "/v1/messages"
| filter request_body ~= "AKIA[0-9A-Z]{16}"
| fields _time, source_user, src_ip, dst_host, uri_path, bytes_sent, app

## VALIDATION — AIACC-002 NGFW Generative AI App-ID Outbound HTTPS to Anthropic
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host = "api.anthropic.com" or tls_sni = "api.anthropic.com"
| filter app in ("anthropic-api", "claude", "generative-ai", "ai-ml-application")
| fields _time, source_user, src_ip, dst_host, app, app_category, bytes_sent, action

## VALIDATION — AIACC-002 Repeated Secret Egress to Anthropic Block Policy Trigger
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host = "api.anthropic.com"
| filter http_method = "POST" and uri_path contains "/v1/messages"
| filter request_body ~= "AKIA[0-9A-Z]{16}"
| comp count() as attempts, count_distinct(action) as action_kinds by source_user, src_ip
| filter attempts >= 2
| fields source_user, src_ip, attempts, action_kinds

