# TTP-2026-0096 — Hands-on-Keyboard Behavioral Anomaly on a Service Account — Cortex Analytics Behavioral IOC (ABIOC) (T1059.004 / T1078.003 / T1046)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — EDR-010 Anomalous Interactive Shell Lineage from Automation Account (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned automation-identity baseline (scheduled cron jobs, no interactive shell) -> service-account authentication -> interactive shell lineage that diverges from the baseline, anchored to the originating auth.
# A service account whose learned Cortex behavioral profile is scheduled, non-interactive automation suddenly parents an interactive shell (login-style bash with a controlling tty). ABIOC anchors the deviation to the causality chain (service-account auth -> interactive shell) rather than to any known-bad binary, catching hands-on-keyboard use of a legitimate account that a static rule keyed on a bad command string would miss.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_effective_username in ("svc-backup", "www-data", "nobody")
| filter action_process_image_name in ("bash", "sh", "zsh")
| filter action_process_command_line contains "-i" or action_process_command_line contains "login"
| comp count() as interactive_shells by agent_hostname, actor_effective_username, causality_actor_process_image_name
| filter interactive_shells >= 1
| fields agent_hostname, actor_effective_username, causality_actor_process_image_name, interactive_shells

## ABIOC — EDR-010 Living-off-the-Land Discovery Burst Deviating from Account Baseline (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Interactive shell under the automation account -> rapid fan-out of distinct discovery/staging utilities that exceeds the account's learned process diversity, anchored to the spawning shell.
# An automation account whose learned baseline is a narrow, repetitive process set runs a rapid burst of discovery/staging utilities (whoami, id, uname, hostname, ss, curl). Every utility is legitimate; the ABIOC fires on the cadence-and-diversity deviation from the account's learned behavior, anchored to the interactive shell that spawned them.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_effective_username in ("svc-backup", "www-data", "nobody")
| filter action_process_image_name in ("whoami", "id", "uname", "hostname", "ss", "netstat", "curl", "wget")
| comp count_distinct(action_process_image_name) as distinct_tools by agent_hostname, actor_effective_username, actor_process_instance_id, causality_actor_process_image_name
| filter distinct_tools >= 4
| sort desc distinct_tools
| fields agent_hostname, actor_effective_username, actor_process_instance_id, causality_actor_process_image_name, distinct_tools

## VALIDATION — EDR-010 Automation Account Baseline Learned
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 900)
| filter actor_effective_username = "svc-backup"
| comp count_distinct(action_process_image_name) as baseline_tools by agent_hostname
| filter baseline_tools >= 1
| fields agent_hostname, baseline_tools

## VALIDATION — EDR-010 Interactive Deviation Surfaced on Automation Account
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 900)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_effective_username = "svc-backup"
| filter action_process_image_name in ("bash", "sh")
| comp count() as interactive_spawns by agent_hostname
| filter interactive_spawns >= 1
| fields agent_hostname, interactive_spawns

