# TTP-2026-0156 — AWS IAM & S3 Enumeration Sequence — Cloud Discovery Recon (SIM-CDR-021)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — AWS Cloud-Discovery Volume Anomaly on a Learned Identity Baseline (behavioral-ML, causality-anchored)
# severity: medium
# behavioral_profile: machine-learning
# causality_anchor: The principal's learned CloudTrail discovery-API baseline (the stable set of enumeration calls, their rate and breadth per caller ARN). The ABIOC anchors the volume/breadth deviation to that per-identity baseline and the caller-ARN causality chain, not to any single API call.
# PANW-authored, auto-tuned behavioral-ML detection. Cortex learns each AWS principal's normal CloudTrail discovery-API profile (which enumeration calls it makes, how often, and how broad). This ABIOC fires when a principal's discovery-call volume and API breadth spike far above its learned baseline within a short window — the mass-enumeration deviation an attacker produces while mapping IAM trust and S3 exposure. No single ListRoles / ListBuckets call is a known-bad IOC; the catch is the deviation from the learned per-identity baseline, anchored to the identity's CloudTrail causality chain. The body below is the XQL-shaped proxy the ABIOC evaluates against the modeled baseline.

dataset = cloud_audit_logs
| filter eventType = "AwsApiCall"
| filter eventName in ("ListUsers", "ListRoles", "ListPolicies", "GetAccountAuthorizationDetails", "ListAttachedRolePolicies", "ListBuckets", "GetBucketAcl", "GetBucketPolicy", "ListObjects")
| filter _time > to_timestamp(current_time() - 1800)
| comp count() as discovery_calls, count_distinct(eventName) as distinct_apis by userIdentity.arn, sourceIPAddress
| filter discovery_calls >= 8 and distinct_apis >= 5
| fields userIdentity.arn, sourceIPAddress, discovery_calls, distinct_apis

## VALIDATION — AWS IAM Enumeration Sequence
# purpose: hunt
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter eventSource = "iam.amazonaws.com"
| filter eventName in ("ListUsers", "ListRoles", "ListPolicies", "ListGroups", "GetAccountAuthorizationDetails", "ListAttachedRolePolicies", "ListAttachedUserPolicies")
| filter _time > to_timestamp(current_time() - 900)
| comp count_distinct(eventName) as distinct_enum_calls, count() as iam_events by userIdentity.arn, sourceIPAddress
| filter distinct_enum_calls >= 4
| fields userIdentity.arn, sourceIPAddress, distinct_enum_calls, iam_events

## VALIDATION — AWS S3 Buckets Enumeration Activity
# purpose: hunt
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter eventSource = "s3.amazonaws.com"
| filter eventName in ("ListBuckets", "ListObjects", "ListObjectsV2", "GetBucketAcl", "GetBucketPolicy", "GetBucketLocation")
| filter _time > to_timestamp(current_time() - 900)
| comp count_distinct(eventName) as distinct_s3_calls, count() as s3_events by userIdentity.arn, sourceIPAddress
| filter distinct_s3_calls >= 3
| fields userIdentity.arn, sourceIPAddress, distinct_s3_calls, s3_events

## VALIDATION — SIM-CDR-021 Emitted CloudTrail Landing Validation
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 900)
| filter cortexsim_run_id != null
| filter eventSource in ("iam.amazonaws.com", "s3.amazonaws.com")
| comp count() as emitted_records by eventSource, eventName
| sort desc emitted_records
| fields eventSource, eventName, emitted_records

