# TTP-2026-0159 — Compute Activity in a Dormant Cloud Region (Cryptomining) — CDR (SIM-CDR-024)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — Suspicious Heavy Allocation of Compute Resources - Possible Mining Activity (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Per-principal compute-allocation baseline: the ML model learns each principal's normal instance-type mix and volume; a burst of GPU/high-core types with an outsized requested count anchors the mining-shaped deviation.
# ABIOC (is_ml=true) — the XSIAM Cloud Storage & Compute analytics alert 'Suspicious heavy allocation of compute resources - possible mining activity'. Auto-tuned behavioral-ML anchored on a learned per-principal compute-allocation baseline: a short-window burst of large GPU / high-core instance types (a mining-shaped fleet) far above the principal's normal allocation profile.

dataset = cloud_audit_logs
| filter eventSource = "ec2.amazonaws.com" and eventName = "RunInstances"
| filter instance_type in ("p4d.24xlarge", "p5.48xlarge", "g5.48xlarge", "g6e.48xlarge")
| comp count() as gpu_launches, sum(instances_requested) as total_requested by userIdentity.arn, awsRegion
| filter gpu_launches >= 3 or total_requested >= 20
| fields userIdentity.arn, awsRegion, gpu_launches, total_requested

## VALIDATION — Compute Activity in Dormant Cloud Region
# purpose: hunt
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter eventSource = "ec2.amazonaws.com" and eventName = "RunInstances"
| filter region_dormant_days > 90
| comp count() as instances_launched by userIdentity.arn, awsRegion, recipientAccountId
| filter instances_launched >= 1
| fields userIdentity.arn, awsRegion, recipientAccountId, instances_launched

## VALIDATION — Dormant-Region and Heavy-Allocation RunInstances Landing Check
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 3600)
| filter eventName = "RunInstances" and eventSource = "ec2.amazonaws.com"
| filter dormant_region_marker = true or heavy_compute_allocation_marker = true
| comp count() as observed_records by awsRegion, instance_type
| sort desc observed_records
| fields awsRegion, instance_type, observed_records

