# TTP-2026-0071 — Inbound Vulnerability-Scanning Reconnaissance Against Perimeter (T1595.002 / T1595.001)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — ASM EAL — Inbound Vulnerability-Scan URI Fan-Out Against Perimeter Asset
# severity: high
# A single source issues an abnormally high number of distinct URI paths against a perimeter web asset within a short window — the application-layer vulnerability-scanner fingerprint (T1595.002), distinct from a port sweep.

dataset = panw_ngfw_traffic_raw
| filter app in ("web-browsing", "ssl", "http-proxy") and dst_port in (80, 443, 9001)
| filter src_ip != null and dst_ip != null and uri_path != null
| bin _time span=5m
| comp count_distinct(uri_path) as scanned_uris, count() as requests by src_ip, dst_ip, _time
| filter scanned_uris >= 20
| fields _time, src_ip, dst_ip, scanned_uris, requests

## BIOC — ASM EAL — Known Vulnerability-Scanner User-Agent On Perimeter Asset
# severity: medium
# Inbound web request to a perimeter asset carrying a recognised vulnerability-scanner user-agent (Nikto / nuclei / masscan-derived) — direct evidence of automated vulnerability-scanning reconnaissance.

dataset = panw_ngfw_traffic_raw
| filter dst_port in (80, 443, 9001)
| filter http_user_agent contains_any ("Nikto", "nuclei", "masscan", "sqlmap", "WPScan")
| fields _time, src_ip, dst_ip, http_user_agent, uri_path

## VALIDATION — ASM-002 Vulnerability-Scan URI Fan-Out (1 src -> many URIs on exposed host)
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_ip = "${ASM_TARGET_HOST}" and dst_port in (80, 443, 9001)
| comp count_distinct(uri_path) as scanned_uris, count() as requests by src_ip, dst_ip
| filter scanned_uris >= 20
| fields src_ip, dst_ip, scanned_uris, requests

## VALIDATION — ASM-002 Scanner User-Agent And 4xx Response Burst
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_ip = "${ASM_TARGET_HOST}"
| filter http_user_agent contains_any ("Nikto", "nuclei", "masscan") or http_rsp_code in (401, 403, 404)
| comp count() as scan_requests, count_distinct(uri_path) as probed_paths by src_ip, http_user_agent
| filter scan_requests >= 5
| fields src_ip, http_user_agent, scan_requests, probed_paths

## VALIDATION — ASM-002 Xpanse Active-Scan Observation Tied To Exposed Asset
# purpose: validation
# dataset: asm_findings

dataset = asm_findings
| filter _time > to_timestamp(current_time() - 86400)
| filter finding_type in ("active_scan_observed", "vulnerable_service", "exposed_panel")
| filter tags contains "CortexSimASMFinding" or asset_external_ip = "${ASM_TARGET_HOST}"
| comp count() as observations by finding_type, scanning_source_ip
| fields finding_type, scanning_source_ip, observations

## VALIDATION — ASM-002 Sensitive-Path Probe Roll-Up (.git/.env/admin/backup)
# purpose: hunt
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 86400)
| filter dst_ip = "${ASM_TARGET_HOST}"
| filter uri_path contains_any ("/.git/", "/.env", "/admin", "/wp-login.php", "/server-status", "/.aws/credentials", ".bak")
| comp count() as probes by src_ip, uri_path, http_rsp_code
| sort desc probes
| fields src_ip, uri_path, http_rsp_code, probes

