# TTP-2026-0135 — CL-UNK-1068 Web-Shell w3wp CGO to python.exe Side-Load Mimikatz, SAM-Hive Theft and FRP Tunnel (T1505.003 / T1003 / T1574.001)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — CL-UNK-1068 IIS Worker w3wp Spawns Command Shell Web Shell CGO
# severity: high
# The IIS worker process w3wp.exe spawns an interactive command shell (cmd.exe / powershell.exe) — the web-shell code-execution event that makes w3wp.exe the Causality Group Owner of the intrusion. A legitimate IIS app pool almost never shells out; this is the root node every downstream detection stitches back to.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter causality_actor_process_image_name = "w3wp.exe"
| filter actor_process_image_name = "w3wp.exe"
| filter action_process_image_name in ("cmd.exe", "powershell.exe", "pwsh.exe")
| comp count() as shell_spawns by agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, action_process_image_name
| filter shell_spawns >= 1
| fields agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, action_process_image_name, shell_spawns

## BIOC — CL-UNK-1068 SAM and SYSTEM Registry Hive Save Under Web Shell Causality
# severity: high
# reg.exe writes the HKLM\SAM and HKLM\SYSTEM hives to disk ('reg save') for offline credential cracking, and the process is owned by the w3wp.exe web-shell causality rather than an admin console. Keying on causality_actor_process_instance_id ties the hive theft to the same web shell that spawned the shell, distinguishing malicious offline-cracking prep from legitimate backup tooling.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter causality_actor_process_image_name = "w3wp.exe"
| filter action_process_image_name = "reg.exe"
| filter action_process_command_line contains "save" and (action_process_command_line contains "hklm\\sam" or action_process_command_line contains "hklm\\system")
| comp count() as hive_saves by agent_hostname, causality_actor_process_instance_id, actor_process_image_name, action_process_command_line
| filter hive_saves >= 1
| fields agent_hostname, causality_actor_process_instance_id, actor_process_image_name, action_process_command_line, hive_saves

## BIOC — CL-UNK-1068 certutil Encode Fileless Loot Staging Under Web Shell Causality
# severity: medium
# certutil.exe is abused with '-encode' to base64 the collected WinRAR loot archive for fileless exfil back through the web shell. The staging process is owned by the w3wp.exe causality, so this is not an admin using certutil for certificate work — it is the collection/exfil-prep stage of the same intrusion.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter causality_actor_process_image_name = "w3wp.exe"
| filter action_process_image_name = "certutil.exe"
| filter action_process_command_line contains "encode"
| comp count() as encode_ops by agent_hostname, causality_actor_process_instance_id, actor_process_image_name, action_process_command_line
| filter encode_ops >= 1
| fields agent_hostname, causality_actor_process_instance_id, actor_process_image_name, action_process_command_line, encode_ops

## ABIOC — CL-UNK-1068 python DLL Side Load In Memory Credential Theft Under Web Shell Causality (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-host module baseline (this python.exe only ever loads its own install-tree DLLs) -> a python20.dll load from a web-writable path -> the loading python.exe's causality_actor_process chain resolves to the w3wp.exe web shell, anchoring the side-load as web-shell-owned in-memory credential theft rather than benign Python use.
# A legitimately-signed python.exe / pythonw.exe loads a non-standard python20.dll from a web-writable path (inetpub / temp / programdata) rather than its own install tree — the DLL-side-load that deobfuscates and runs Mimikatz shellcode entirely in memory. This is the crucial causality nuance: the LOLBin's actor_process_image_name is the trusted 'python.exe', so an image-name rule misses it; the ABIOC anchors the anomaly to causality_actor_process_image_name / causality_actor_process_instance_id tracing python.exe back to the w3wp.exe web shell, and to the learned baseline that this host's python.exe never loads python20.dll. Auto-tuned behavioral ML, not a static signature.

dataset = xdr_data
| filter event_type = ENUM.MODULE and event_sub_type = ENUM.MODULE_LOAD
| filter causality_actor_process_image_name = "w3wp.exe"
| filter action_process_image_name in ("python.exe", "pythonw.exe")
| filter action_module_name = "python20.dll"
| filter action_module_path contains "\\inetpub" or action_module_path contains "\\temp" or action_module_path contains "\\programdata"
| comp count() as sideloads by agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, action_process_image_name, action_module_path
| filter sideloads >= 1
| fields agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, action_process_image_name, action_module_path, sideloads

## VALIDATION — CL-UNK-1068 FRP Reverse Tunnel Endpoint Network Egress Stitch
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter event_type = ENUM.NETWORK
| filter causality_actor_process_image_name = "w3wp.exe"
| filter action_process_image_name in ("32.exe", "frpc.exe", "nginx.exe", "httpd")
| comp count() as tunnel_sessions, sum(action_total_download) as bytes_in by agent_hostname, causality_actor_process_instance_id, action_process_image_name, action_remote_ip
| filter tunnel_sessions >= 1
| sort desc bytes_in
| fields agent_hostname, causality_actor_process_instance_id, action_process_image_name, action_remote_ip, tunnel_sessions, bytes_in

## VALIDATION — CL-UNK-1068 Web Shell Causality Chain Full Reconstruction
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter causality_actor_process_image_name = "w3wp.exe"
| filter action_process_image_name in ("cmd.exe", "reg.exe", "python.exe", "pythonw.exe", "certutil.exe", "32.exe", "frpc.exe")
| comp count_distinct(action_process_image_name) as chain_stages by agent_hostname, causality_actor_process_instance_id
| filter chain_stages >= 3
| sort desc chain_stages
| fields agent_hostname, causality_actor_process_instance_id, chain_stages

