# TTP-2026-0052 — Cryptojacking — Stratum Mining Pool Connection via App-ID (T1496)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — NGFW EAL — repeated short-lived TCP sessions to mining pool port
# severity: high
# NGFW EAL — repeated short-lived TCP sessions to mining pool port

dataset = panw_ngfw_traffic_raw
| filter dst_port in (3333, 4444, 5555, 7777, 14444, 45700)
| filter action = "allow"
| comp count() as session_count, avg(bytes_sent + bytes_received) as avg_bytes by src_ip, dst_ip, dst_port
| filter session_count >= 4
| fields src_ip, dst_ip, dst_port, session_count, avg_bytes

## VALIDATION — Pre-flight: sinkhole port 3333 reachable
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_ip = "10.50.0.42" and dst_port = 3333
| comp count() as sessions by src_ip, dst_ip, dst_port
| fields src_ip, dst_ip, dst_port, sessions

## VALIDATION — NGFW App-ID — Stratum/cryptocurrency-mining identified on outbound TCP
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter app in ("stratum", "cryptocurrency-mining", "bitcoin", "mining-pool") or dst_port in (3333, 4444, 5555, 14444)
| filter dst_ip = "10.50.0.42"
| comp count() as mining_sessions by src_ip, dst_ip, dst_port, app
| filter mining_sessions >= 1
| fields src_ip, dst_ip, dst_port, app, mining_sessions

