# TTP-2026-0172 — Trusted-Relationship Abuse — A Compromised Vendor's Consented Integration Pivots Into the Tenant With No Sign-In Anomaly
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — Consented Integration Deviating From Its Own Learned Call-Rate and Scope-Usage Baseline (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: The consented application identity (app_id) owns this chain. There is no process to anchor on and no interactive principal to blame — the integration IS the actor, which is exactly why per-application baselining rather than per-user baselining is the only workable frame here.
# The primary claim, and the only thing left to detect on. No consent event, no interactive sign-in and no credential theft exists in this chain, so the anomaly must be the integration's behaviour against the integration's own history: request volume above its learned profile combined with the first-ever exercise of scopes it was granted long ago and never used. A scope granted is not a scope used, and the gap between the two is the most under-instrumented surface in a SaaS tenant.

dataset = msft_o365_audit
| filter cortexsim_run_tag = "CLOUD010"
| filter auth_type = "app_only" and is_interactive = false
| comp count() as api_calls, count_distinct(scope_used) as scopes_exercised, count_distinct(target_mailbox) as mailboxes by app_id, app_display_name
| filter api_calls >= 40 and scopes_exercised >= 3
| sort desc api_calls
| fields app_id, app_display_name, scopes_exercised, mailboxes, api_calls

## ABIOC — Vendor Integration Touching Object Classes It Has Never Touched Before (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Same consented application identity, joined to the call-rate deviation on app_id so the two deltas form one incident rather than two unrelated anomalies.
# The second delta, chosen because it survives the obvious evasion of the first. An adversary who paces the call rate to stay inside the learned profile still has to read record types the integration never read, because the point of the pivot is to reach data the vendor's own function never needed. Object-class novelty is therefore the harder-to-evade half of the pair, and it is meaningless without the call-rate half — together they are specific, apart they are noise.

dataset = msft_o365_audit
| filter cortexsim_run_tag = "CLOUD010"
| filter object_class_first_seen = true
| comp count_distinct(object_class) as novel_classes, count() as accesses by app_id, app_display_name, publisher_name
| filter novel_classes >= 2
| sort desc novel_classes
| fields app_id, app_display_name, publisher_name, novel_classes, accesses

## VALIDATION — Negative Control — No Credential Theft, Impossible Travel or Anomalous Interactive Sign-In Precedes the Integration Activity
# purpose: validation
# dataset: msft_azure_ad_signin

dataset = msft_azure_ad_signin
| filter _time > to_timestamp(current_time() - 7200)
| filter cortexsim_run_tag = "CLOUD010"
| filter is_interactive = true or risk_event_type in ("impossibleTravel", "leakedCredentials", "anonymizedIPAddress")
| comp count() as identity_anomalies by user_principal_name, risk_event_type
| fields user_principal_name, risk_event_type, identity_anomalies

## VALIDATION — Bulk Mailbox Item Access by the Vendor Integration Across Distinct Mailboxes
# purpose: validation
# dataset: msft_o365_audit

dataset = msft_o365_audit
| filter _time > to_timestamp(current_time() - 7200)
| filter cortexsim_run_tag = "CLOUD010"
| filter operation = "MailItemsAccessed" and auth_type = "app_only"
| comp count() as accesses, count_distinct(target_mailbox) as mailboxes by app_id, app_display_name
| filter mailboxes >= 5
| sort desc mailboxes
| fields app_id, app_display_name, mailboxes, accesses

## VALIDATION — Integration Egress to a Destination Outside Its Publisher's Declared Endpoints
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 7200)
| filter cortexsim_run_tag = "CLOUD010"
| filter publisher_declared_endpoint = false
| comp count() as transfers, sum(bytes_sent) as bytes_out, count_distinct(dest_ip) as destinations by app_id, publisher_name
| filter transfers >= 1
| sort desc bytes_out
| fields app_id, publisher_name, destinations, transfers, bytes_out

## VALIDATION — Blast-Radius Control — Peer Integrations With Comparable Scopes Stay Inside Their Baselines
# purpose: validation
# dataset: msft_o365_audit

dataset = msft_o365_audit
| filter _time > to_timestamp(current_time() - 7200)
| filter cortexsim_run_tag = "CLOUD010" and cortexsim_label = "benign"
| filter auth_type = "app_only" and within_baseline = true
| comp count() as api_calls, count_distinct(scope_used) as scopes_exercised by app_id, app_display_name
| filter api_calls >= 1
| sort desc api_calls
| fields app_id, app_display_name, scopes_exercised, api_calls

## VALIDATION — Consented Application Inventory Ranked by Baseline Deviation
# purpose: hunt
# dataset: msft_o365_audit

dataset = msft_o365_audit
| filter _time > to_timestamp(current_time() - 86400)
| filter auth_type = "app_only"
| comp count() as api_calls, count_distinct(scope_used) as scopes_exercised, count_distinct(object_class) as object_classes by app_id, app_display_name, publisher_name
| sort desc api_calls
| limit 100
| fields app_id, app_display_name, publisher_name, scopes_exercised, object_classes, api_calls

