# TTP-2026-0080 — Sock-Shop Microservices Behavioral Anomaly — Cortex Analytics Behavioral IOC (ABIOC) (T1610 / T1611 / T1046)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — CDR-009 Anomalous East-West Connection Spike from Baselined Microservice (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Privileged kubectl exec into the catalogue pod -> shell child process -> burst of east-west connections to peers absent from the learned service-mesh profile for this container.
# A Sock-Shop microservice that Cortex has profiled to a stable set of east-west peers suddenly fans out connections to services it has never contacted in the learned baseline window. ABIOC anchors the deviation to the causality chain (privileged exec into the pod -> shell child -> new east-west peers), distinguishing a real behavioral anomaly from normal mesh traffic.

dataset = network_story
| filter action_local_ip != null and action_remote_ip != null
| filter actor_process_image_name in ("sh", "bash", "nc", "curl")
| filter causality_actor_process_image_name in ("sh", "bash")
| comp count_distinct(action_remote_ip) as distinct_peers by actor_effective_username, causality_actor_process_image_name, container_id, agent_hostname
| filter distinct_peers >= 5
| sort desc distinct_peers
| fields agent_hostname, container_id, causality_actor_process_image_name, actor_effective_username, distinct_peers

## ABIOC — CDR-009 Anomalous Container Process-Tree Deviation from Learned Baseline (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-container process baseline (single service process) -> exec-spawned shell -> network/packaging child processes that diverge from the baseline, anchored to the originating exec.
# A container whose learned per-process baseline is a single long-running service binary suddenly hosts a shell process tree spawning network and packaging tooling. ABIOC fires on the single deviation event with the causality chain that ties the anomalous children back to the exec, rather than on a static known-bad process name.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("sh", "bash")
| filter action_process_image_name in ("curl", "nc", "nmap", "python3", "apt", "apk", "ps")
| filter causality_actor_process_image_name in ("sh", "bash")
| comp count() as anomalous_children by agent_hostname, container_id, causality_actor_process_image_name, actor_process_instance_id
| filter anomalous_children >= 1
| fields agent_hostname, container_id, causality_actor_process_image_name, actor_process_instance_id, anomalous_children

## VALIDATION — CDR-009 Sock-Shop Baseline Service-Mesh Learned
# purpose: validation
# dataset: network_story

dataset = network_story
| filter _time > to_timestamp(current_time() - 1500)
| filter agent_hostname contains "sock-shop" or action_local_ip != null
| comp count_distinct(action_remote_ip) as peers by actor_effective_username
| filter peers >= 1
| fields actor_effective_username, peers

## VALIDATION — CDR-009 Behavioral Deviation Surfaced in Endpoint Telemetry
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 1500)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("sh", "bash")
| comp count() as shell_spawns by agent_hostname
| filter shell_spawns >= 1
| fields agent_hostname, shell_spawns

