# TTP-2026-0011 — AI Access — Cross-Provider Rotation (OpenAI → Gemini → Anthropic)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## VALIDATION — AIACC-005 First Egress to OpenAI User Active in Provider Matrix
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host = "api.openai.com" or tls_sni = "api.openai.com"
| filter http_method = "POST" and uri_path contains "/v1/chat/completions"
| comp min(_time) as first_seen by source_user, src_ip, dst_host
| fields source_user, src_ip, dst_host, first_seen

## VALIDATION — AIACC-005 Same User Second Provider Gemini Within Rotation Window
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host in ("api.openai.com", "generativelanguage.googleapis.com")
| filter http_method = "POST"
| comp count_distinct(dst_host) as provider_count, min(_time) as first_seen, max(_time) as last_seen by source_user, src_ip
| filter provider_count >= 2
| fields source_user, src_ip, provider_count, first_seen, last_seen

## VALIDATION — AIACC-005 Three Providers Within Five Minutes Provider Hopping
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host in ("api.openai.com", "generativelanguage.googleapis.com", "api.anthropic.com")
| filter http_method = "POST"
| comp count_distinct(dst_host) as provider_count, min(_time) as first_seen, max(_time) as last_seen by source_user, src_ip
| alter window_seconds = timestamp_diff(last_seen, first_seen, "SECOND")
| filter provider_count = 3 and window_seconds <= 300
| fields source_user, src_ip, provider_count, window_seconds

## VALIDATION — AIACC-005 XSIAM Stitch Single User Three Provider Sessions
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host in ("api.openai.com", "generativelanguage.googleapis.com", "api.anthropic.com")
| filter http_method = "POST"
| comp count() as sessions, values(dst_host) as providers by source_user
| filter array_length(providers) = 3
| fields source_user, sessions, providers

## VALIDATION — AIACC-005 NGFW Generative AI App-ID Across Three FQDNs Shared Run ID
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host in ("api.openai.com", "generativelanguage.googleapis.com", "api.anthropic.com")
| filter app_category in ("generative-ai", "ai-ml-application")
| filter http_request_headers contains "x-simulation-run-id"
| comp count_distinct(dst_host) as fqdn_count by src_ip
| filter fqdn_count = 3
| fields src_ip, fqdn_count

