# TTP-2026-0054 — Shadow-AI Asset Discovery & Inventory — Cortex Cloud AI-SPM (T1526)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## VALIDATION — AISPM-001 Ground Truth Manifest Capture Bookkeeping
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 1800)
| filter operation_name in ("terraform.output", "GetResources") and cloud_provider = "AWS"
| filter resource_tags contains "CortexSimAISPMFinding"
| fields _time, operation_name, resource_type, resource_tags

## VALIDATION — AISPM-001 AI Asset Scan Cycle Discovery
# purpose: validation
# dataset: ai_spm_findings

dataset = ai_spm_findings
| filter _time > to_timestamp(current_time() - 1800)
| filter finding_type = "asset_discovered"
| filter asset_type in ("ai_endpoint", "ai_model", "ai_data_store", "ai_function_integration")
| comp count() as discovered by asset_type
| fields asset_type, discovered

## VALIDATION — AISPM-001 Inventory API AI Tagged Assets Count
# purpose: validation
# dataset: cortex_cloud_posture

dataset = cortex_cloud_posture
| filter _time > to_timestamp(current_time() - 1800)
| filter asset_type in ("ai_endpoint", "ai_model", "ai_data_store", "ai_function_integration")
| filter tags contains "CortexSimAISPMFinding"
| comp count() as discovered_count by asset_type, ai_service
| filter discovered_count >= 1
| fields asset_type, ai_service, discovered_count

## VALIDATION — AISPM-001 Asset Discovery Coverage Reconciliation
# purpose: validation
# dataset: cortex_cloud_posture

dataset = cortex_cloud_posture
| filter _time > to_timestamp(current_time() - 1800)
| filter tags contains "CortexSimAISPMFinding"
| filter asset_type in ("ai_endpoint", "ai_model", "ai_data_store", "ai_function_integration")
| comp count_distinct(asset_id) as discovered_assets
| filter discovered_assets >= 6
| fields discovered_assets

