# TTP-2026-0158 — Cloud Instance-Credential (IMDS) Theft and Off-Instance Reuse — Cloud Storage & Compute (SIM-CDR-023)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — Cloud Unusual Instance Metadata Service (IMDS) access (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: The EC2 instance-profile role session (assumed-role ARN + instance_id, where roleSessionName == instance_id); the ML deviation is that same instance-profile credential surfacing on API calls from a source IP outside the instance's learned egress.
# PANW behavioral-ML ABIOC. Learns the per-instance baseline that an EC2 instance-profile role session (roleSessionName == instance_id) is normally exercised only from that instance's own egress. Fires when that instance role session appears on API calls (GetCallerIdentity, ListAttachedRolePolicies) from a source IP outside the learned egress set within the causality window — the CloudTrail-observable footprint of an IMDS-harvested credential being reused off-instance. The learned anchor is the instance role session (assumed-role ARN + instance_id); the deviation is the source-IP set diverging from the instance's own egress. The IMDS read itself is not in CloudTrail, so the ABIOC keys on the credential's use, not on a phantom fetch event.

dataset = cloud_audit_logs
| filter cloud_provider = "AWS" and management_event = true
| filter identity_type = "AssumedRole" and role_session_name = instance_id
| filter event_name in ("GetCallerIdentity", "ListAttachedRolePolicies")
| comp count() as api_calls, values(event_name) as api_actions, values(source_ip) as source_ips by role_session_name, instance_id
| filter api_calls >= 1
| fields role_session_name, instance_id, source_ips, api_actions, api_calls

## VALIDATION — Suspicious usage of EC2 token
# purpose: hunt
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter cloud_provider = "AWS" and identity_type = "AssumedRole"
| filter role_session_name = instance_id and read_only = false
| comp count() as write_calls, values(event_name) as api_actions, values(source_ip) as source_ips by instance_id, role_session_name
| filter write_calls >= 1
| fields instance_id, role_session_name, source_ips, api_actions, write_calls

## VALIDATION — SIM-CDR-023 IMDS to remote-use landing validation
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 900)
| filter cortexsim_run_id != null
| filter event_name in ("GetCallerIdentity", "ListAttachedRolePolicies")
| comp count() as observed_events, values(event_name) as event_names by recipient_account_id
| filter observed_events >= 1
| fields recipient_account_id, event_names, observed_events

