# TTP-2026-0027 — Cloud App — Okta Risky OAuth Drive-Scope Grant
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — Pre-flight: oauth_grant_emulator metadata visible to operator
# severity: high
# Pre-flight: oauth_grant_emulator metadata visible to operator

// AUTO-GENERATED SKELETON — replace with real XQL before promotion.
// MITRE technique: T1550.001
dataset = okta_audit OR dataset = azure_signin OR dataset = google_workspace_audit
| filter /* TODO: predicate matching the BIOC name */
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

## BIOC — Cloud App — outbound OAuth authorize to Okta carrying drive-wide scope
# severity: high
# Cloud App — outbound OAuth authorize to Okta carrying drive-wide scope

// AUTO-GENERATED SKELETON — replace with real XQL before promotion.
// MITRE technique: T1550.001
dataset = okta_audit OR dataset = azure_signin OR dataset = google_workspace_audit
| filter /* TODO: predicate matching the BIOC name */
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

## BIOC — NGFW EAL — outbound /oauth2/v1/authorize App-ID match to *.okta.com
# severity: high
# NGFW EAL — outbound /oauth2/v1/authorize App-ID match to *.okta.com

// AUTO-GENERATED SKELETON — replace with real XQL before promotion.
// MITRE technique: T1550.001
dataset = okta_audit OR dataset = azure_signin OR dataset = google_workspace_audit
| filter /* TODO: predicate matching the BIOC name */
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

## BIOC — Cloud App — repeated risky grant attempts (3 in <60s) flagged as enumeration pattern
# severity: high
# Cloud App — repeated risky grant attempts (3 in <60s) flagged as enumeration pattern

// AUTO-GENERATED SKELETON — replace with real XQL before promotion.
// MITRE technique: T1550.001
dataset = okta_audit OR dataset = azure_signin OR dataset = google_workspace_audit
| filter /* TODO: predicate matching the BIOC name */
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

