# TTP-2026-0179 — Unsanctioned SaaS Web Upload of Confidential Financial Records
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — Financial Data Staging
# severity: high
# Financial Data Staging

preset = xdr_data | filter event_type = 'FILE_WRITE' and action_file_name contains 'financials' and (action_file_path contains '/tmp/' or action_file_path contains 'AppData')

## BIOC — DLP Unsanctioned Web Upload
# severity: high
# DLP Unsanctioned Web Upload

preset = xdr_data | filter event_type = 'NETWORK' and action_process_image_name in ('curl', 'powershell', 'chrome', 'msedge') and action_process_command_line contains 'financials.csv'

## VALIDATION — Enterprise DLP Cloud Upload Audit
# purpose: hunt

dataset = panw_dlp_raw | filter dlp_status in ('BLOCKED', 'ALERT') and file_type in ('CSV', 'XLSX') | comp count() as violations by user_id, destination_domain | filter violations >= 1

