# TTP-2026-0110 — MCP Sampling Abuse — Server-Initiated Inference for Quota Theft and Covert Tool Invocation (T1656 / T1059 / T1496)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — KOI-007 Covert writeFile Artifact tmp.txt from MCP Host Process
# severity: high
# Signature match on the exact artifact Unit 42's covert-tool-invocation PoC produces: an MCP host process (node/npx/python3/IDE) creating a file named tmp.txt in a temporary directory. This hand-authored BIOC fires on the known-bad shape; it is the deliberate contrast to the ABIOC below, which catches the same class of covert writeFile even when the filename is not tmp.txt.

dataset = xdr_data
| filter event_type = ENUM.FILE and event_sub_type in (ENUM.FILE_CREATE_NEW, ENUM.FILE_WRITE)
| filter action_file_name = "tmp.txt"
| filter action_file_path contains "/tmp/" or action_file_path contains "/var/tmp/"
| filter actor_process_image_name in ("node", "npx", "python3", "claude", "code")
| fields agent_hostname, actor_effective_username, actor_process_image_name, action_file_path, action_file_name

## ABIOC — KOI-007 Unattended MCP Tool Invocation with No User Interaction (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned baseline: on this host, tool invocations (file writes) follow a user-interaction event within the same causality chain. Deviation: an MCP host process performs a writeFile tool invocation whose causality traces to an inbound MCP sampling/createMessage request rather than a user action — anchored to the MCP-server connection, not the model's output text.
# An MCP host process writes a file via a tool invocation with no preceding user-interaction event in its causality chain — the behavioral signature of server-initiated covert tool use. Unlike the tmp.txt BIOC, this ABIOC anchors on the deviation (a writeFile tool firing without a user keystroke/interactive parent) rather than a specific filename, so it catches covert writes to any path. Auto-tuned against the host's learned tool-invocation-follows-user-action baseline.

dataset = xdr_data
| filter event_type = ENUM.FILE and event_sub_type in (ENUM.FILE_CREATE_NEW, ENUM.FILE_WRITE)
| filter actor_process_image_name = "mcp-server"
| filter action_file_path contains "/tmp/" or action_file_path contains "/var/tmp/"
| filter causality_actor_process_image_name not in ("bash", "sh", "zsh", "dash", "gnome-terminal", "sshd", "login", "tmux", "screen")
| comp count() as unattended_writes by agent_hostname, actor_effective_username, actor_process_image_name, causality_actor_process_image_name
| filter unattended_writes >= 2
| sort desc unattended_writes
| fields agent_hostname, actor_effective_username, actor_process_image_name, causality_actor_process_image_name, unattended_writes

## ABIOC — KOI-007 Sampling-Request Token Consumption Anomaly from MCP Host (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: statistical
# causality_anchor: Learned baseline: the MCP host's per-session inference request count and upload volume when the user is interactively driving the client. Deviation: a burst of server-initiated createMessage requests exceeding that baseline (quota theft), anchored to the MCP-server session that originated them.
# The MCP host emits a burst of server-initiated inference requests whose volume and byte count exceed its learned interactive sampling cadence — the quota-theft signal ('tokens consumed exceed expected output size'). ABIOC anchors the statistical outlier to the MCP-server connection that drove the createMessage calls, catching quota theft that leaves no known-bad string.

dataset = network_story
| filter actor_process_image_name = "mcp-server"
| filter dst_ip = "127.0.0.1" and dst_port = 80
| comp count() as sampling_requests, sum(action_total_upload) as bytes_uploaded, sum(action_total_download) as bytes_downloaded by agent_hostname, actor_effective_username, actor_process_image_name
| filter bytes_uploaded > (bytes_downloaded * 4)
| sort desc bytes_uploaded
| fields agent_hostname, actor_effective_username, actor_process_image_name, sampling_requests, bytes_uploaded, bytes_downloaded

## VALIDATION — KOI-007 Unattended MCP File-Write Artifact Surfaced
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 900)
| filter event_type = ENUM.FILE and event_sub_type in (ENUM.FILE_CREATE_NEW, ENUM.FILE_WRITE)
| filter action_file_path contains "/tmp/cortexsim-mcp-sampling"
| comp count() as writes by agent_hostname, actor_effective_username, action_file_name
| filter writes >= 1
| fields agent_hostname, actor_effective_username, action_file_name, writes

## VALIDATION — KOI-007 Sampling-Request Frequency and Token Hunt
# purpose: hunt
# dataset: network_story

dataset = network_story
| filter _time > to_timestamp(current_time() - 3600)
| filter actor_process_image_name in ("node", "npx", "python3", "claude", "code", "mcp-server")
| comp count() as sampling_requests, sum(action_total_upload) as bytes_uploaded by agent_hostname, actor_effective_username, actor_process_image_name
| filter sampling_requests >= 5
| sort desc sampling_requests
| fields agent_hostname, actor_effective_username, actor_process_image_name, sampling_requests, bytes_uploaded

