# TTP-2026-0077 — Web-Application Attack-Surface Enumeration & Injection Probing — Cortex ASM + NGFW (T1595.002 / T1595.003 / T1190)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — ASM-004 Web Content-Discovery Path Brute-Force Burst From Single Source
# severity: medium
# A single source IP issues a high-volume burst of distinct URI paths against the exposed nginx web surface within a short window — the signature of directory/content brute-forcing (Gobuster/Feroxbuster). The world-exposed nginx host is the static ASM finding; this BIOC fires when that surface is actively enumerated, bridging ASM discovery into NGFW/NDR runtime detection.

dataset = panw_ngfw_traffic_raw
| filter app = "web-browsing" or dst_port in (80, 443, 9001)
| filter flow_direction = "inbound"
| comp count_distinct(uri_path) as distinct_paths, count() as total_reqs by src_ip, dst_ip
| filter distinct_paths >= 50

## BIOC — ASM-004 SQL-Injection Probe Pattern In Web Request
# severity: high
# An inbound web request to the exposed surface (notably the gocortexbrokenbank app on :9001) carries a SQL-injection probe pattern in its URI or payload — the SQLmap detection bridging ASM exposure into runtime exploitation detection.

dataset = panw_ngfw_threat_raw
| filter dst_port in (80, 443, 9001)
| filter threat_category = "sql-injection" or uri_path ~= "(?i)(union(\s|\+)+select|or(\s|\+)+1=1|sleep\(|information_schema)"

## BIOC — ASM-004 OS-Command-Injection Probe Pattern In Web Request
# severity: high
# An inbound web request to the exposed surface carries an OS-command-injection probe pattern (shell metacharacters / chained commands) in a parameter — the Commix detection completing the injection-probe coverage on the exposed banking app.

dataset = panw_ngfw_threat_raw
| filter dst_port in (80, 443, 9001)
| filter threat_category = "code-injection" or uri_path ~= "(?i)(;\s*(cat|id|whoami|uname)|\|\s*(cat|id|whoami)|`.*`|\$\(.*\))"

## VALIDATION — ASM-004 Ground-Truth Manifest Capture Bookkeeping
# purpose: validation
# dataset: asm_findings

dataset = asm_findings
| filter _time > to_timestamp(current_time() - 1800)
| filter tags contains "CortexSimASMFinding"
| filter finding_class in ("multi-service-exposed-host", "multiple-exposed-ports")
| comp count_distinct(resource_id) as assets by finding_class
| fields finding_class, assets

## VALIDATION — ASM-004 Web Technology Fingerprint And CMS Enumeration Findings
# purpose: validation
# dataset: asm_findings

dataset = asm_findings
| filter _time > to_timestamp(current_time() - 1800)
| filter tags contains "CortexSimASMFinding"
| filter service in ("http", "https") and dst_port in (80, 443, 9001)
| filter detected_technology != null or finding_class = "exposed-web-application"
| comp count_distinct(detected_technology) as fingerprints by resource_id, dst_port
| filter fingerprints >= 1
| fields resource_id, dst_port, fingerprints

## VALIDATION — ASM-004 Content-Discovery Path Fan-Out 1 Src To Many URIs
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_port in (80, 443, 9001) and flow_direction = "inbound"
| comp count_distinct(uri_path) as distinct_paths, count() as reqs by src_ip, dst_ip
| filter distinct_paths >= 50
| sort desc distinct_paths
| fields src_ip, dst_ip, distinct_paths, reqs

## VALIDATION — ASM-004 Web Vulnerability-Scan Threat-Signature Burst
# purpose: validation
# dataset: panw_ngfw_threat_raw

dataset = panw_ngfw_threat_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_port in (80, 443, 9001)
| filter threat_category in ("vulnerability", "scan", "info-leak")
| comp count() as threat_hits, count_distinct(threat_name) as distinct_sigs by src_ip, dst_ip
| filter threat_hits >= 5
| fields src_ip, dst_ip, threat_hits, distinct_sigs

## VALIDATION — ASM-004 Injection-Probe Threat Signatures Against Banking App
# purpose: validation
# dataset: panw_ngfw_threat_raw

dataset = panw_ngfw_threat_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_port = 9001
| filter threat_category in ("sql-injection", "code-injection")
| comp count() as injection_hits by src_ip, dst_ip, threat_category
| filter injection_hits >= 1
| fields src_ip, dst_ip, threat_category, injection_hits

