# TTP-2026-0026 — WildFire Malware Trigger — Dropped Backdoor, C2 Beacon, Ransomware Sim (T1105)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — CDR-005 WildFire Known Bad ELF Download In Container
# severity: high
# WildFire test file download in container — known-bad file signature matched by WildFire cloud intelligence. A container process downloads an ELF that WildFire verdicts as malicious.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name in ("curl", "wget")
| filter action_process_image_command_line contains_any (".elf", "wildfire.paloaltonetworks.com", "publicapi/test")

## BIOC — CDR-005 Executable Downloaded To Tmp And Made Executable In Container
# severity: medium
# Executable file downloaded to /tmp and made executable — download-then-execute pattern in container. A binary lands in /tmp and is immediately chmod +x within the same container lineage.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name = "chmod"
| filter action_process_image_command_line contains "/tmp/"
| filter action_process_image_command_line contains_any ("+x", "0755", "755")

## BIOC — CDR-005 WildFire ELF Execution In Container
# severity: high
# WildFire test file execution — malicious ELF execution in container triggers CDR BIOC rule. The downloaded ELF binary is executed from /tmp inside the container.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter causality_actor_process_image_name in ("apache2", "nginx", "bash", "sh", "test_backdoor.elf")
| filter actor_process_image_path contains "/tmp/"
| filter actor_process_image_path contains_any (".elf", "test_backdoor", "wf_sim")

## BIOC — CDR-005 Downloaded Binary Executed By Service Account In Container
# severity: high
# Downloaded binary executed from /tmp by www-data context — high-risk execution chain in container. A service identity executes a binary that originated from a download into /tmp.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter causality_actor_process_image_name in ("apache2", "nginx", "bash", "sh")
| filter actor_process_image_path contains "/tmp/"
| filter actor_effective_username in ("www-data", "nobody", "node", "apache", "nginx")

## BIOC — CDR-005 Periodic Outbound HTTP Beacon From Container
# severity: high
# Regular periodic outbound HTTP connections from container — C2 beacon interval pattern (3 attempts to 192.0.2.1). A container process makes repeated timed HTTP requests to a single external host.

preset = xdr_data
| filter event_type = ENUM.NETWORK
| filter container_id != null
| filter dst_action_external_hostname = "192.0.2.1" or action_remote_ip = "192.0.2.1"
| filter dst_action_external_port = 80
| comp count() as beacon_count by container_id, action_remote_ip
| filter beacon_count >= 2

## BIOC — CDR-005 Post Execution C2 Network Activity In Container
# severity: medium
# C2 communication pattern following malware execution — post-execution network activity in container. Outbound network activity originates from a curl process spawned in the same container that executed the dropped binary.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter causality_actor_process_image_name in ("apache2", "nginx", "bash", "sh", "test_backdoor.elf")
| filter actor_process_image_name = "curl"
| filter action_process_image_command_line contains "192.0.2.1"
| filter action_process_image_command_line contains_any ("beacon", "User-Agent", "-A ", "MSIE")

## BIOC — CDR-005 Mass File Modification Ransomware Pattern In Container
# severity: high
# Mass file modification pattern in container — ransomware-style encryption simulation matches T1486 behavioral rule. A burst of file writes/removes in a single directory mimics ransomware impact.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter container_id != null
| filter event_sub_type in (ENUM.FILE_CREATE, ENUM.FILE_REMOVE, ENUM.FILE_RENAME)
| comp count() as file_ops by container_id, causality_actor_process_instance_id
| filter file_ops >= 5

## BIOC — CDR-005 Bulk Enc Extension Rename After Execution In Container
# severity: high
# Bulk file rename with .enc extension following malware execution — post-execution encryption behavior in container. Multiple files acquire a .enc extension shortly after the dropped binary runs.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter event_sub_type = ENUM.FILE_CREATE
| filter container_id != null
| filter action_file_extension = "enc"
| comp count() as enc_files by container_id
| filter enc_files >= 3

## VALIDATION — CDR-005 Validate Dropped ELF Execution In Container
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_path contains "/tmp/" and actor_process_image_path contains_any (".elf", "wf_sim", "test_backdoor")
| fields _time, agent_hostname, container_id, causality_id, causality_actor_process_image_name, actor_process_instance_id, actor_effective_username, actor_process_image_path, action_process_image_command_line

## VALIDATION — CDR-005 Validate C2 Beacon To Test Net Endpoint
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.NETWORK
| filter container_id != null
| filter action_remote_ip = "192.0.2.1" or dst_action_external_hostname = "192.0.2.1"
| fields _time, agent_hostname, container_id, action_remote_ip, dst_action_external_port

## VALIDATION — CDR-005 Validate Bulk Enc Rename In Container
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.FILE and event_sub_type = ENUM.FILE_CREATE
| filter container_id != null
| filter action_file_extension = "enc"
| fields _time, agent_hostname, container_id, actor_process_image_name, action_file_path

