# TTP-2026-0055 — AI Model Security Assessment — Overprivileged Role + Misconfig (T1078.004)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## VALIDATION — AISPM-002 MTTD Anchor Bookkeeping
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 1800)
| filter cloud_provider = "AWS" and resource_type = "sagemaker_endpoint"
| filter resource_name contains "aispm"
| fields _time, operation_name, resource_name

## VALIDATION — AISPM-002 Model Security Assessment Cycle Complete
# purpose: validation
# dataset: ai_spm_findings

dataset = ai_spm_findings
| filter _time > to_timestamp(current_time() - 1800)
| filter finding_type = "assessment_completed" and ai_service = "sagemaker"
| filter model_name contains "aispm"
| fields _time, ai_service, model_name, finding_type

## VALIDATION — AISPM-002 Three Model Security Findings On SageMaker Fixture
# purpose: validation
# dataset: cortex_cloud_posture

dataset = cortex_cloud_posture
| filter _time > to_timestamp(current_time() - 1800)
| filter finding_type in ("overprivileged_execution_role", "endpoint_missing_encryption", "unvalidated_model_input_surface")
| filter ai_service = "sagemaker" and tags contains "CortexSimAISPMFinding"
| comp count_distinct(finding_type) as distinct_findings by model_name
| filter distinct_findings >= 3
| fields model_name, distinct_findings

