# TTP-2026-0007 — AI Access — Source Code Paste to Public ChatGPT
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — AIACC-001 Pre-flight LLM Provider Egress Plugin Registered
# severity: informational
# Pre-flight: plugin metadata visible to operator. Confirms the llm_provider_egress EAL plugin is registered before the scenario emits any provider traffic; matches the describe/registration audit event on the simulation worker.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("python", "python3")
| filter action_process_image_command_line contains "scripts.eal_simulator.cli"
| filter action_process_image_command_line contains "describe"
| filter action_process_image_command_line contains "llm_provider_egress"

## VALIDATION — AIACC-001 Source Code Shape POST to OpenAI With Canary Marker
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host = "api.openai.com" or tls_sni = "api.openai.com"
| filter http_method = "POST" and uri_path contains "/v1/chat/completions"
| filter request_body contains "CORTEXSIM-CANARY" or request_body contains "def settle_transactions"
| fields _time, source_user, src_ip, dst_host, uri_path, bytes_sent, app

## VALIDATION — AIACC-001 DLP Source Code Structure Regex Match in LLM Prompt
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host in ("api.openai.com", "api.anthropic.com", "generativelanguage.googleapis.com")
| filter request_body ~= "(?:^|\n)\s*(?:def |class |import |from\s+\w+\s+import|#\s*CORTEXSIM-CANARY)"
| fields _time, source_user, src_ip, dst_host, uri_path, bytes_sent

## VALIDATION — AIACC-001 NGFW Generative AI App-ID Outbound HTTPS to OpenAI
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host = "api.openai.com" or tls_sni = "api.openai.com"
| filter app in ("openai-api", "chatgpt", "generative-ai", "ai-ml-application")
| fields _time, source_user, src_ip, dst_host, app, app_category, bytes_sent, action

## VALIDATION — AIACC-001 Repeated Source Paste Burst to OpenAI Single User
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host = "api.openai.com"
| filter http_method = "POST" and uri_path contains "/v1/chat/completions"
| comp count() as post_count, sum(bytes_sent) as total_bytes by source_user, src_ip
| filter post_count >= 3
| fields source_user, src_ip, post_count, total_bytes

