# TTP-2026-0105 — Cloud Posture Drift Correlated to Runtime Cause — Cortex Cloud CSPM (T1562 / T1578 / T1530)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## VALIDATION — CSPM-002 Compliant Baseline Posture Snapshot
# purpose: validation
# dataset: cortex_cloud_posture

dataset = cortex_cloud_posture
| filter _time > to_timestamp(current_time() - 3600)
| filter cloud_provider = "AWS" and resource_type in ("aws_s3_bucket", "aws_cloudtrail")
| filter tags contains "CortexSimDriftTarget"
| filter compliance_state = "compliant"
| comp count_distinct(resource_id) as compliant_baseline by resource_type
| fields resource_type, compliant_baseline

## VALIDATION — CSPM-002 S3 Public Access Block Removed Drift
# purpose: validation
# dataset: cortex_cloud_posture

dataset = cortex_cloud_posture
| filter _time > to_timestamp(current_time() - 3600)
| filter cloud_provider = "AWS" and resource_type = "aws_s3_bucket"
| filter tags contains "CortexSimDriftTarget"
| filter compliance_state = "drifted" and finding_class in ("public-access-block-removed", "bucket-policy-public")
| comp count_distinct(resource_id) as drifted_buckets by finding_class
| filter drifted_buckets >= 1
| fields finding_class, drifted_buckets

## VALIDATION — CSPM-002 CloudTrail Logging Disabled Drift
# purpose: validation
# dataset: cortex_cloud_posture

dataset = cortex_cloud_posture
| filter _time > to_timestamp(current_time() - 3600)
| filter cloud_provider = "AWS" and resource_type = "aws_cloudtrail"
| filter tags contains "CortexSimDriftTarget"
| filter compliance_state = "drifted" and finding_class = "cloudtrail-logging-disabled"
| comp count_distinct(resource_id) as drifted_trails by finding_class
| filter drifted_trails >= 1
| fields finding_class, drifted_trails

## VALIDATION — CSPM-002 Runtime Control Plane Action Causing Drift
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 3600)
| filter cloud_provider = "AWS" and event_source in ("s3.amazonaws.com", "cloudtrail.amazonaws.com")
| filter event_name in ("DeletePublicAccessBlock", "PutBucketPolicy", "PutBucketAcl", "StopLogging", "UpdateTrail")
| comp count() as drift_actions by event_name, user_identity_arn
| filter drift_actions >= 1
| sort desc drift_actions
| fields event_name, user_identity_arn, drift_actions

## VALIDATION — CSPM-002 Public Bucket Data Access Post Drift
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 3600)
| filter cloud_provider = "AWS" and event_source = "s3.amazonaws.com"
| filter event_name in ("GetObject", "ListObjects", "ListBucket")
| filter not incidr(src_ip, "10.0.0.0/8") and not incidr(src_ip, "172.16.0.0/12") and not incidr(src_ip, "192.168.0.0/16")
| comp count() as external_reads by bucket_name, src_ip
| filter external_reads >= 1
| fields bucket_name, src_ip, external_reads

## VALIDATION — CSPM-002 Posture Drift Coverage Reconciliation
# purpose: validation
# dataset: cortex_cloud_posture

dataset = cortex_cloud_posture
| filter _time > to_timestamp(current_time() - 3600)
| filter cloud_provider = "AWS"
| filter tags contains "CortexSimDriftTarget"
| filter compliance_state = "drifted"
| filter finding_class in ("public-access-block-removed", "bucket-policy-public", "cloudtrail-logging-disabled")
| comp count_distinct(finding_class) as drift_classes
| filter drift_classes >= 2
| fields drift_classes

