# TTP-2026-0025 — Kubernetes Lateral Movement via Stolen Service-Account Token (T1021)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — CDR-004 Pod API Server Enumeration With Service Account Token
# severity: high
# Kubernetes API server enumeration from within pod using mounted service account token. A container process curls the in-cluster API server with a Bearer token to list namespaces.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name in ("curl", "wget")
| filter action_process_image_command_line contains "kubernetes.default.svc"
| filter action_process_image_command_line contains_any ("Authorization: Bearer", "serviceaccount/token", "/api/v1/namespaces")

## BIOC — CDR-004 Service Account Token Used For API Discovery Audit
# severity: medium
# Service account token used for API server discovery — anomalous cluster enumeration behavior. The Kubernetes audit log records a workload service account listing namespaces or cluster resources.

dataset = cloud_audit_logs
| filter cloud_provider = "kubernetes" or log_source = "k8s_audit"
| filter verb in ("list", "get")
| filter objectRef_resource in ("namespaces", "nodes")
| filter user_username contains "system:serviceaccount"

## BIOC — CDR-004 Service Account Token Read And Copied In Pod
# severity: high
# Service account token read and copied — Kubernetes credential theft from mounted secret volume. A pod process reads the projected token and copies it elsewhere on disk.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name in ("cat", "cp", "bash", "sh")
| filter action_process_image_command_line contains "serviceaccount/token"

## BIOC — CDR-004 Service Account Token Staged To Tmp In Pod
# severity: high
# Sensitive Kubernetes credential file access pattern — token exfiltration to /tmp staging directory. The mounted token is copied to a /tmp staging path for later reuse.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter event_sub_type = ENUM.FILE_CREATE
| filter container_id != null
| filter action_file_path contains "/tmp/"
| filter action_file_path contains_any ("token", "sa_token", "stolen")

## BIOC — CDR-004 kubectl All Namespaces Enumeration From Pod
# severity: high
# kubectl --all-namespaces enumeration from within pod — cross-namespace discovery using stolen token. kubectl is run inside a container with --all-namespaces to map workloads cluster-wide.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name = "kubectl"
| filter action_process_image_command_line contains "get pods"
| filter action_process_image_command_line contains_any ("--all-namespaces", "-A")

## BIOC — CDR-004 Cluster Wide Pod Discovery Audit Anomaly
# severity: medium
# Cluster-wide pod discovery via kubectl in container — lateral movement reconnaissance pattern. The Kubernetes audit log records a list pods request scoped to all namespaces by a workload identity.

dataset = cloud_audit_logs
| filter cloud_provider = "kubernetes" or log_source = "k8s_audit"
| filter verb = "list"
| filter objectRef_resource = "pods"
| filter objectRef_namespace = null or objectRef_namespace = ""
| filter user_username contains "system:serviceaccount"

## BIOC — CDR-004 kubectl Exec Into Adjacent Pod Lateral Movement
# severity: high
# kubectl exec into pod in different namespace — lateral movement via Kubernetes API (high fidelity CDR BIOC). kubectl exec is invoked from inside one container to run a command in another pod.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name = "kubectl"
| filter action_process_image_command_line contains "exec"
| filter action_process_image_command_line contains_any ("-n ", "--namespace")

## BIOC — CDR-004 Pod Exec Subresource Create Audit Anomaly
# severity: high
# Cross-namespace pod exec from compromised container — Kubernetes lateral movement chain detected. The Kubernetes audit log records a create on the pods/exec subresource by a workload service account.

dataset = cloud_audit_logs
| filter cloud_provider = "kubernetes" or log_source = "k8s_audit"
| filter verb = "create"
| filter objectRef_resource = "pods"
| filter objectRef_subresource = "exec"
| filter user_username contains "system:serviceaccount"

## BIOC — CDR-004 Malicious CronJob Creation Via kubectl From Pod
# severity: high
# Kubernetes CronJob creation via kubectl — scheduled task persistence mechanism in cluster. kubectl apply creates a CronJob resource from inside a compromised pod.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name = "kubectl"
| filter action_process_image_command_line contains_any ("apply", "create")
| filter action_process_image_command_line contains_any ("cronjob", ".yaml", "-f ")

## BIOC — CDR-004 CronJob Resource Create Audit Anomaly
# severity: high
# CronJob creation anomaly — new batch workload created from compromised pod context, cross-namespace pattern. The Kubernetes audit log records a create on cronjobs by a workload service account.

dataset = cloud_audit_logs
| filter cloud_provider = "kubernetes" or log_source = "k8s_audit"
| filter verb = "create"
| filter objectRef_resource = "cronjobs"
| filter user_username contains "system:serviceaccount"

## VALIDATION — CDR-004 Validate kubectl Exec From Pod In Container
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name = "kubectl" and action_process_image_command_line contains "exec"
| fields _time, agent_hostname, container_id, actor_effective_username, action_process_image_command_line

## VALIDATION — CDR-004 Validate Pod Exec Or CronJob Create In K8s Audit
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 1800)
| filter verb = "create"
| filter (objectRef_resource = "pods" and objectRef_subresource = "exec") or objectRef_resource = "cronjobs"
| filter user_username contains "system:serviceaccount"
| fields _time, user_username, verb, objectRef_resource, objectRef_subresource, objectRef_namespace, sourceIPs

## VALIDATION — CDR-004 Validate Service Account Token Theft In Pod
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter container_id != null
| filter action_process_image_command_line contains "serviceaccount/token"
| filter actor_process_image_name in ("cat", "cp", "bash", "sh")
| fields _time, agent_hostname, container_id, actor_process_image_name, action_process_image_command_line

