# TTP-2026-0148 — ASM Exposure-to-RCE: Internet-Exposed WSUS (CVE-2025-59287) → Domain Recon → Webhook Exfil — Correlation (SIM-ASM-005)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — ASM-005 WSUS Deserialization RCE Update Service Spawns Interpreter Chain
# severity: critical
# Hand-authored reproduction of Unit 42's published hunting logic for CVE-2025-59287: the WSUS service (wsusservice.exe) or the wsuspool IIS worker (w3wp.exe) spawns a command interpreter (cmd.exe / powershell.exe), filtering the legitimate children a healthy WSUS host produces (svchost.exe, conhost.exe, csc.exe). Any surviving child is the deserialization payload executing as the update service.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name = "wsusservice.exe" or (actor_process_image_name = "w3wp.exe" and lowercase(actor_process_command_line) contains "wsuspool")
| filter action_process_image_name in ("cmd.exe", "powershell.exe", "pwsh.exe")
| filter action_process_image_name not in ("svchost.exe", "conhost.exe", "csc.exe", "cscript.exe")
| comp count() as payload_spawns by agent_hostname, actor_process_image_name, action_process_image_name
| filter payload_spawns >= 1
| fields agent_hostname, actor_process_image_name, action_process_image_name, payload_spawns

## ABIOC — ASM-005 WSUS Service Identity Spawns Out-of-Baseline Command Shell (behavioral-ML, causality-anchored)
# severity: critical
# behavioral_profile: machine-learning
# causality_anchor: Learned WSUS-service baseline (periodic update synchronisation, no interactive interpreter) -> internet-exposed WSUS management interface -> deserialization RCE -> out-of-baseline cmd/powershell lineage, anchored to the WSUS service as causality group owner.
# The WSUS update service identity — wsusservice.exe, or w3wp.exe running under the wsuspool application pool — whose learned Cortex behavioral profile is periodic update-synchronisation traffic and never an interactive interpreter, suddenly parents a cmd.exe/powershell.exe chain. The auto-tuned ABIOC fires on the deviation from the service identity's learned process baseline and anchors it to the causality chain (internet-exposed WSUS -> deserialization exploit -> shell), catching the CVE-2025-59287 payload without a signature for any specific command.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter causality_actor_process_image_name = "wsusservice.exe" or (causality_actor_process_image_name = "w3wp.exe" and causality_actor_process_command_line contains "wsuspool")
| filter action_process_image_name in ("cmd.exe", "powershell.exe", "pwsh.exe")
| comp count() as out_of_baseline_shells by agent_hostname, causality_actor_process_image_name, actor_effective_username
| filter out_of_baseline_shells >= 1
| fields agent_hostname, causality_actor_process_image_name, actor_effective_username, out_of_baseline_shells

## VALIDATION — ASM-005 Internet-Exposed WSUS Management Interface Discovered
# purpose: hunt
# dataset: asm_findings

dataset = asm_findings
| filter _time > to_timestamp(current_time() - 3600)
| filter dst_port in (8530, 8531)
| filter service in ("wsus", "http", "https") or finding_class = "internet-exposed-management-interface"
| comp count_distinct(resource_id) as exposed_wsus_assets by resource_id, dst_port
| filter exposed_wsus_assets >= 1
| fields resource_id, dst_port, exposed_wsus_assets

## VALIDATION — ASM-005 Domain Recon Burst Under WSUS Process Lineage
# purpose: hunt
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 900)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter causality_actor_process_image_name in ("wsusservice.exe", "w3wp.exe")
| filter action_process_image_name in ("whoami.exe", "net.exe", "net1.exe", "ipconfig.exe", "nltest.exe")
| comp count_distinct(action_process_image_name) as recon_tools by agent_hostname, causality_actor_process_instance_id
| filter recon_tools >= 2
| fields agent_hostname, causality_actor_process_instance_id, recon_tools

## VALIDATION — ASM-005 Webhook Site Exfil Egress From WSUS Host
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 900)
| filter dst_host contains "webhook.site" or uri contains "webhook.site"
| filter app in ("web-browsing", "ssl", "http")
| comp count() as exfil_sessions by src_ip, dst_host, app
| filter exfil_sessions >= 1
| fields src_ip, dst_host, app, exfil_sessions

