# TTP-2026-0107 — Identity-Weaponized MDM Mass Device Wipe — Compromised Intune Admin RemoteWipe at Tenant Scale (Cortex Identity ABIOC)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — ITDR-011 Anomalous Bulk Remote-Wipe Broadcast from Privileged Intune Identity (behavioral-ML, causality-anchored)
# severity: critical
# behavioral_profile: machine-learning
# causality_anchor: Learned admin device-action baseline (config-and-read governance, at most an occasional single-device wipe) -> phished/compromised standing-privilege admin -> burst of RemoteWipe/FactoryReset device actions across the estate that diverges from the baseline, anchored to the initiating identity and its preceding risky sign-in.
# An Intune/Global admin identity whose learned Cortex behavioral profile is config-and-read device governance suddenly issues a burst of native RemoteWipe/FactoryReset device actions across the managed estate at a volume that dwarfs its learned device-action cadence. Every action uses a legitimate Intune device-management API and is authenticated, authorized, and delivered from trusted Microsoft infrastructure, so no wiper signature exists to key on; the ABIOC fires on the burst-scale deviation from the account's learned behavior and anchors it to the causality chain (phished-admin risky sign-in -> MDM console access -> tenant-scale wipe broadcast) rather than to any known-bad principal.

dataset = msft_o365_audit
| filter category = "DeviceManagement" and activity_display_name in ("Remote Wipe device action", "RemoteWipe", "Factory reset device action", "RemoteFactoryReset")
| filter _time > to_timestamp(current_time() - 3600)
| comp count() as wipe_actions_now, count_distinct(target_device_id) as devices_targeted, earliest(_time) as first_wipe by initiating_user_principal_name
| join type=left (dataset = msft_o365_audit
| filter category = "DeviceManagement" and activity_display_name in ("Remote Wipe device action", "RemoteWipe", "Factory reset device action", "RemoteFactoryReset")
| filter _time < to_timestamp(current_time() - 3600)
| comp count() as learned_wipe_cadence by initiating_user_principal_name) as baseline baseline.initiating_user_principal_name = initiating_user_principal_name
| alter learned_wipe_cadence = coalesce(learned_wipe_cadence, 0)
| filter wipe_actions_now >= 25 and wipe_actions_now > learned_wipe_cadence * 5
| sort desc wipe_actions_now
| fields initiating_user_principal_name, wipe_actions_now, learned_wipe_cadence, devices_targeted, first_wipe

## ABIOC — ITDR-011 First-Seen Destructive Device Action on a Standing-Privilege Admin (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned standing-privilege admin baseline (device enrollment / compliance policy pushes, zero factory-resets) -> first-ever destructive device action issued by that identity, anchored to the standing-privilege account and flagged before the burst threshold is met.
# A standing-privilege Global/Intune admin whose learned device-management history contains no destructive device actions issues a RemoteWipe/FactoryReset for the first time. Because Handala/Void Manticore abuse legitimate MDM commands rather than dropping malware, the first destructive action is itself the signal: the ABIOC fires on the first-seen deviation from the account's learned config-only device baseline, anchored to the standing-privilege identity, catching the destructive cloud action before a burst threshold is even reached.

dataset = msft_o365_audit
| filter category = "DeviceManagement" and activity_display_name in ("Remote Wipe device action", "RemoteWipe", "Factory reset device action", "RemoteFactoryReset")
| filter _time > to_timestamp(current_time() - 3600)
| comp count() as destructive_actions_now, earliest(_time) as first_seen_destructive by initiating_user_principal_name
| join type=left (dataset = msft_o365_audit
| filter category = "DeviceManagement" and activity_display_name in ("Remote Wipe device action", "RemoteWipe", "Factory reset device action", "RemoteFactoryReset")
| filter _time < to_timestamp(current_time() - 3600)
| comp count() as prior_destructive_actions by initiating_user_principal_name) as history history.initiating_user_principal_name = initiating_user_principal_name
| alter prior_destructive_actions = coalesce(prior_destructive_actions, 0)
| filter destructive_actions_now >= 1 and prior_destructive_actions = 0
| sort desc destructive_actions_now
| fields initiating_user_principal_name, destructive_actions_now, prior_destructive_actions, first_seen_destructive

## VALIDATION — ITDR-011 Mass Remote-Wipe Burst Surfaced Across Managed Estate
# purpose: validation
# dataset: msft_o365_audit

dataset = msft_o365_audit
| filter _time > to_timestamp(current_time() - 1800)
| filter category = "DeviceManagement" and activity_display_name contains "Wipe"
| comp count() as wipe_actions, count_distinct(target_device_id) as devices_targeted, earliest(_time) as first_wipe by initiating_user_principal_name
| filter wipe_actions >= 1
| sort desc devices_targeted
| fields initiating_user_principal_name, wipe_actions, devices_targeted, first_wipe

## VALIDATION — ITDR-011 Phished-Admin Risky Sign-In Precursor to Wipe Broadcast
# purpose: hunt
# dataset: msft_azure_ad_signin

dataset = msft_azure_ad_signin
| filter _time > to_timestamp(current_time() - 3600)
| filter category = "SignInLogs"
| filter initiating_user_principal_name in ("intune-admin@cortexsim-canary.invalid", "global-admin@cortexsim-canary.invalid", "mdm-admin@cortexsim-canary.invalid")
| filter risk_level_during_signin in ("high", "medium") or risk_state = "atRisk"
| comp count() as risky_signins, values(ip_address) as source_ips, earliest(_time) as first_risky by initiating_user_principal_name
| filter risky_signins >= 1
| sort desc risky_signins
| fields initiating_user_principal_name, risky_signins, source_ips, first_risky

