# TTP-2026-0023 — Cryptominer Deployment — XMRig Resource Hijacking in Containers (T1496)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — CDR-002 Container Resource Limit Tuning Pre-Mining
# severity: medium
# System limit modification in container — ulimit/sysctl tuning consistent with cryptominer pre-deployment. A container process raises resource limits or enables huge pages to maximize hashing throughput.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name in ("sysctl", "ulimit", "bash", "sh")
| filter action_process_image_command_line contains_any ("transparent_hugepage", "vm.nr_hugepages", "ulimit -n", "ulimit -u")

## BIOC — CDR-002 XMRig Binary Download And Extraction In Container
# severity: high
# XMRig binary download and extraction — cryptominer tool transfer signature. A container process fetches the XMRig release tarball and extracts the miner binary.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name in ("curl", "wget", "tar")
| filter action_process_image_command_line contains_any ("xmrig", "xmrig-6", "linux-static")

## BIOC — CDR-002 Compressed Binary Extracted To Hidden Tmp In Container
# severity: medium
# Compressed binary downloaded and extracted to /tmp hidden directory in container. A tarball is unpacked into a dot-prefixed /tmp staging directory to evade casual inspection.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name = "tar"
| filter action_process_image_command_line contains "/tmp/."
| filter action_process_image_command_line contains_any (".tar.gz", "-xz", "--strip-components")

## BIOC — CDR-002 Known Mining Pool In Config File In Container
# severity: high
# Known cryptomining pool domain/IP in config file — pool.minexmr.com association. A config file written in the container references a known public stratum mining pool.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter container_id != null
| filter action_file_extension = "json"
| filter action_file_path contains "config"
| filter actor_process_image_name in ("bash", "sh", "cat", "tee", "python3")

## BIOC — CDR-002 XMRig Process Execution In Container
# severity: critical
# Cryptominer binary execution — XMRig process tree detected by CDR runtime BIOC. The xmrig binary launches inside a container, optionally with --config pointing at a pool.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name = "xmrig" or action_process_image_command_line contains_any ("xmrig", "--config", "stratum+tcp", "--max-threads-hint")
| filter causality_actor_process_image_name in ("bash", "sh", "runc", "containerd-shim", "cron", "crond")
| fields _time, container_id, actor_effective_username, causality_actor_process_image_name, causality_actor_process_instance_id, action_process_image_command_line

## BIOC — CDR-002 Sustained High CPU Mining Workload In Container
# severity: high
# Sustained CPU spike from container process consistent with cryptomining workload. A long-lived container process drives high CPU utilization characteristic of hashing.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter container_id != null
| filter actor_process_image_name in ("xmrig", "kdevtmpfsi", "kinsing")
| filter action_total_cpu_pct >= 80

## BIOC — CDR-002 Crontab Modification To Persist Cryptominer In Container
# severity: high
# Crontab modification to persist cryptominer — scheduled task creation from container. crontab is invoked to install a recurring job that re-launches the miner.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name = "crontab"
| filter causality_actor_process_image_name in ("bash", "sh", "runc", "containerd-shim")
| filter action_process_image_command_line contains_any ("xmrig", "-", "/tmp/.xmr")
| fields _time, container_id, actor_effective_username, causality_actor_process_image_name, causality_actor_process_instance_id, action_process_image_command_line

## BIOC — CDR-002 Cryptominer Added To Cron Schedule In Container
# severity: high
# Cryptominer binary added to cron schedule — multi-stage malware persistence behavior. A cron spool/tab file is written that references the miner binary path.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter container_id != null
| filter action_file_path contains_any ("/var/spool/cron", "/etc/cron", "crontab")
| filter actor_process_image_name in ("crontab", "bash", "sh", "tee")

## VALIDATION — CDR-002 Validate XMRig Execution In Container
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name = "xmrig" or action_process_image_command_line contains "xmrig"
| fields _time, agent_hostname, container_id, actor_effective_username, actor_process_image_name, action_process_image_command_line

## VALIDATION — CDR-002 Validate Mining Pool Config Or Download In Container
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter container_id != null
| filter action_process_image_command_line contains_any ("pool.minexmr.com", "stratum+tcp", "xmrig-6", "linux-static")
| fields _time, agent_hostname, container_id, actor_process_image_name, action_process_image_command_line

## VALIDATION — CDR-002 Validate Cron Persistence Of Miner In Container
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter container_id != null
| filter actor_process_image_name = "crontab" and action_process_image_command_line contains "xmrig"
| fields _time, agent_hostname, container_id, action_process_image_command_line

