# TTP-2026-0104 — Identity to Endpoint to Network Hands-on-Keyboard Campaign — Cross-Plane XSIAM Stitch (T1078 / T1059 / T1071)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — MP-008 Identity Sign-In Anomaly on a Privileged Account (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-identity sign-in baseline (stable geography, low MFA-prompt volume) -> a successful authentication from an improbable geography coupled with an MFA-challenge burst, anchored to the identity so the takeover is the root of the causality chain.
# A privileged/service account whose learned Cortex sign-in profile is a narrow, stable geography authenticates successfully from an improbable second country while a burst of MFA challenges is pushed at it. The ABIOC anchors the impossible-travel-plus-MFA-fatigue deviation to the account's learned baseline rather than to any single failed logon, catching the social-engineered takeover front-end of a Scattered Spider / Octo Tempest intrusion.

dataset = okta_sso
| filter eventType = "user.authentication.sso" or eventType = "user.mfa.factor.activate" or eventType = "user.mfa.factor.challenge"
| filter actor_alternate_id in ("svc-backup", "www-data", "nobody")
| comp count_distinct(client_geo_country) as countries, count() as mfa_prompts by actor_alternate_id
| filter countries >= 2 and mfa_prompts >= 5
| sort desc mfa_prompts
| fields actor_alternate_id, countries, mfa_prompts

## ABIOC — MP-008 Hands-on-Keyboard Endpoint Behavioral Deviation (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Anomalous account sign-in -> interactive shell under the same account on a reachable host (the causality_actor_process / CGO) -> rapid fan-out of distinct discovery utilities exceeding the account's learned process diversity, anchored to that owning shell's causality_actor_process_instance_id and the dropped actor_effective_username (svc-backup), not any single child image.
# Immediately after the anomalous sign-in, the same account, whose learned endpoint baseline is narrow non-interactive automation, parents an interactive shell (the causality-group-owner of the burst) and runs a rapid living-off-the-land discovery burst. Every utility is a legitimate admin tool; the ABIOC fires on the interactive-lineage-plus-diversity deviation, keyed on the causality_actor_process (the owning shell) and its instance_id plus actor_effective_username (the dropped svc-account identity) rather than on any single child image, so the whole fan-out threads to one process-lineage owner.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_effective_username in ("svc-backup", "www-data", "nobody")
| filter causality_actor_process_image_name in ("bash", "sh", "zsh", "sshd")
| filter action_process_image_name in ("whoami", "id", "uname", "hostname", "ss", "netstat", "cat", "curl")
| comp count_distinct(action_process_image_name) as distinct_tools, count() as burst by agent_hostname, actor_effective_username, causality_actor_process_image_name, causality_actor_process_instance_id
| filter distinct_tools >= 4
| sort desc distinct_tools
| fields agent_hostname, actor_effective_username, causality_actor_process_image_name, causality_actor_process_instance_id, distinct_tools, burst

## VALIDATION — MP-008 C2 Egress Session Burst From the Compromised Host
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 900)
| filter app in ("web-browsing", "ssl", "http")
| comp count() as sessions by source_ip, dest_ip
| filter sessions >= 5
| sort desc sessions
| fields source_ip, dest_ip, sessions

## VALIDATION — MP-008 Cross-Plane Stitch Convergence Check
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 900)
| comp count_distinct(_product) as plane_count, count_distinct(incident_id) as incident_count by agent_hostname
| filter plane_count >= 3 and incident_count = 1
| fields agent_hostname, plane_count, incident_count

