# TTP-2026-0162 — Unusual exec Into a Kubernetes Pod + Unusual Service-Account API Call (SIM-CDR-025)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — Unusual exec into a Kubernetes Pod (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-principal exec baseline: which user/service-account normally opens pods/exec into which pod (objectRef.name) from which sourceIP. The deviation anchors to the pod's container image and the acting identity's exec history.
# PANW-authored behavioral-ML detection over the Kubernetes API-server audit feed. It learns, per principal, the pods that identity normally execs into and raises when a create pods/exec subresource request deviates from that baseline (a principal execing into a pod it has never touched, or a service-account principal execing at all). Keyed on the kubernetes_audit_logs dataset.

dataset = kubernetes_audit_logs
| filter verb = "create" and objectRef_resource = "pods" and objectRef_subresource = "exec"
| comp count() as exec_events by user_username, objectRef_name, sourceIPs
| filter exec_events >= 1
| fields user_username, objectRef_name, sourceIPs, exec_events

## ABIOC — A Kubernetes service account executed an unusual API call (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-service-account API baseline: the verb+resource pairs (user.username -> verb/objectRef.resource) the account exercises normally. The deviation anchors to the compromised service account identity and the RBAC-write resource it has no baseline for.
# PANW-authored behavioral-ML detection over the Kubernetes API-server audit feed. It learns, per service account, the verb+resource pairs that account exercises in baseline and raises when a service-account principal issues an out-of-profile RBAC-write (creating a ClusterRoleBinding / ClusterRole it never touches). Keyed on the kubernetes_audit_logs dataset.

dataset = kubernetes_audit_logs
| filter user_username contains "system:serviceaccount:"
| filter verb in ("create", "update", "patch") and objectRef_resource in ("clusterrolebindings", "rolebindings", "clusterroles")
| comp count() as rbac_writes by user_username, verb, objectRef_resource, objectRef_name
| filter rbac_writes >= 1
| fields user_username, verb, objectRef_resource, objectRef_name, rbac_writes

## VALIDATION — SIM-CDR-025 Kubernetes Audit Emission Validation
# purpose: validation
# dataset: kubernetes_audit_logs

dataset = kubernetes_audit_logs
| filter _time > to_timestamp(current_time() - 900)
| filter cortexsim_run_id != null
| filter pod_exec_marker = true or unusual_sa_api_call_marker = true
| comp count() as audit_records by user_username, verb, objectRef_resource, objectRef_subresource
| filter audit_records >= 1
| fields user_username, verb, objectRef_resource, objectRef_subresource, audit_records

