# TTP-2026-0101 — Low-and-Slow Jittered C2 Beacon Behavioral Anomaly — Cortex Network Analytics Behavioral IOC (ABIOC) (T1071 / T1571)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — NDR-008 Periodic Low-and-Slow Beacon Deviating from Host Egress Baseline (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned host egress baseline (bursty, high-volume, many destinations) -> a single rare destination contacted at a tight periodic interval with small stable payloads, anchored to the originating source host.
# A source host that Cortex has learned emits bursty, high-volume web traffic suddenly produces a tight, periodic trickle of small sessions to a single destination — the Cobalt Strike / Sliver low-and-slow beacon shape. Every destination is legitimate-looking and rotates, so no IOC matches; the ABIOC fires on the periodicity-and-small-payload deviation from the host's learned egress baseline, anchored to the destination causality chain rather than to a known-bad indicator.

dataset = panw_ngfw_traffic_raw
| filter app in ("web-browsing", "http", "ssl", "unknown-tcp")
| filter action = "allow"
| comp count() as beacon_count, avg(bytes_sent) as avg_bytes, count_distinct(uri) as uri_variants by src_ip, dst_ip, dst_host
| filter beacon_count >= 8 and avg_bytes < 2048
| sort desc beacon_count
| fields src_ip, dst_ip, dst_host, beacon_count, avg_bytes, uri_variants

## ABIOC — NDR-008 Jittered Beacon to Rare Destination With Non-Standard Port Deviation (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Periodic low-and-slow beacon under the source host -> a rare destination reached on a non-standard port the host never used at that cadence, anchored to the beacon flow that generated the sessions.
# A host contacts a destination that is rare for it over a non-standard port at a jittered but still statistically periodic cadence — the sleep-with-jitter profile Malleable C2 and Sliver use to evade fixed-interval rules. The ABIOC fires on the rare-destination-plus-non-standard-port deviation from the learned baseline, anchored to the periodic beacon that spawned the flows, catching the beacon after infrastructure rotation defeats any IOC.

dataset = panw_ngfw_traffic_raw
| filter action = "allow"
| filter dst_port not in (80, 443, 53)
| comp count() as sessions, count_distinct(dst_ip) as dst_cardinality, avg(bytes_sent) as avg_bytes by src_ip, dst_host, dst_port
| filter sessions >= 6 and dst_cardinality = 1 and avg_bytes < 2048
| sort desc sessions
| fields src_ip, dst_host, dst_port, sessions, dst_cardinality, avg_bytes

## VALIDATION — NDR-008 Beacon Periodicity Surfaced Against Host Egress Baseline
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 900)
| filter app in ("web-browsing", "http", "ssl", "unknown-tcp")
| filter action = "allow"
| comp count() as beacon_count, avg(bytes_sent) as avg_bytes by src_ip, dst_ip, dst_host
| filter beacon_count >= 8 and avg_bytes < 2048
| fields src_ip, dst_ip, dst_host, beacon_count, avg_bytes

## VALIDATION — NDR-008 Rare Destination and Non-Standard Port Deviation Surfaced
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 900)
| filter action = "allow"
| filter dst_port not in (80, 443, 53)
| comp count() as sessions by src_ip, dst_host, dst_port
| filter sessions >= 6
| fields src_ip, dst_host, dst_port, sessions

