# TTP-2026-0036 — Linux Lateral Movement — SSH Abuse, Tunneling and Internal Recon (T1021.004)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — EDR-005 Port Scan Via Bash devtcp
# severity: high
# Port scanning via bash /dev/tcp — network service discovery from web service account. A bash loop probes multiple ports through /dev/tcp.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("bash", "sh")
| filter action_process_image_command_line contains "/dev/tcp/"
| filter actor_effective_username in ("www-data", "nobody", "node", "postgres", "apache", "nginx")

## BIOC — EDR-005 Batch Mode SSH From Service Account
# severity: high
# SSH connection attempt from service account — lateral movement via remote service. ssh runs with BatchMode=yes and StrictHostKeyChecking=no under a service identity.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name = "ssh"
| filter action_process_image_command_line contains_any ("BatchMode=yes", "StrictHostKeyChecking=no")
| filter actor_effective_username in ("www-data", "nobody", "node", "postgres", "apache", "nginx")

## BIOC — EDR-005 SSH Tunnel Creation With Forward Flags
# severity: high
# SSH tunnel creation (-L/-D flags) — protocol tunneling for covert channel establishment. ssh is invoked with -L local forward, -D SOCKS, or -R remote forward.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name = "ssh"
| filter action_process_image_command_line contains_any (" -L ", " -D ", " -R ", " -w ")
| filter action_process_image_command_line contains " -N"

## VALIDATION — EDR-005 Analytics Network Interface And Routing Enumeration
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("ip", "ifconfig", "route", "arp")
| filter actor_effective_username != "root"
| fields _time, agent_hostname, actor_effective_username, action_process_image_command_line

## VALIDATION — EDR-005 Analytics Sequential Port Connection Attempts
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("bash", "sh") and action_process_image_command_line contains "/dev/tcp/"
| comp count() as probe_attempts by agent_hostname, causality_actor_process_instance_id
| filter probe_attempts >= 3

## VALIDATION — EDR-005 Analytics Batch SSH StrictHostKey Disabled
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name = "ssh"
| filter action_process_image_command_line contains "StrictHostKeyChecking=no"
| fields _time, agent_hostname, actor_effective_username, action_process_image_command_line

## VALIDATION — EDR-005 Analytics SSH Port Forwarding From Service Account
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name = "ssh"
| filter action_process_image_command_line contains_any (" -L ", " -D ", " -R ")
| fields _time, agent_hostname, actor_effective_username, action_process_image_command_line

## VALIDATION — EDR-005 Analytics DNS And Host File Enumeration
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_command_line contains_any ("/etc/hosts", "resolv.conf", "nslookup", "dig", "getent hosts", "hostname -f")
| filter actor_effective_username != "root"
| fields _time, agent_hostname, actor_effective_username, action_process_image_command_line

