# TTP-2026-0134 — Muddled Libra Okta Admin Takeover to Rogue Federated IdP to Cross-Cloud Resource Exfiltration (SIM-MP-016)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — MP-016 AWS Data-Movement Service Abuse Burst
# severity: critical
# A single federated principal drives a burst across two or more AWS data-movement services in one window — Transfer Family server/user creation (CreateServer / CreateUser), DataSync task execution and S3 location creation (StartTaskExecution / CreateLocationS3), and Secrets Manager mass secret reads (GetSecretValue / BatchGetSecretValue). These are legitimate managed services abused to exfiltrate at scale rather than malware; the BIOC keys on the multi-service abuse shape under one identity, emitting the normalized actor so the Cloud App burst equi-joins the ITDR takeover on the shared identity. This is the exploit_impact leg of the chain.

dataset = cloud_audit_logs
| filter cloud_provider = "AWS"
| filter event_name in ("CreateServer", "CreateUser", "StartTaskExecution", "CreateLocationS3", "GetSecretValue", "BatchGetSecretValue")
| alter normalized_actor = lowercase(coalesce(saml_subject, user_identity_arn))
| alter svc = if(event_source = "transfer.amazonaws.com", "transfer", if(event_source = "datasync.amazonaws.com", "datasync", if(event_source = "secretsmanager.amazonaws.com", "secrets", "other")))
| comp count() as api_calls, count_distinct(svc) as services_abused, count_distinct(event_name) as distinct_apis by normalized_actor, source_ip
| filter services_abused >= 2 and api_calls >= 10
| fields normalized_actor, services_abused, distinct_apis, api_calls, source_ip

## ABIOC — MP-016 Help-Desk MFA Reset Then Rapid Privileged Okta Sign-In (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-account factor-reset cadence + sign-in device/geo baseline -> an MFA reset immediately followed by a privileged admin-console sign-in for the same identity, anchored to that identity and emitted as causality_actor_primary_username (normalized_actor) so the Cloud App and cloud data-plane legs equi-join it across planes.
# A privileged Okta account experiences an MFA factor reset (help-desk / admin-driven) and then, within the same short window, a successful privileged admin-console sign-in for the SAME identity — the reset->sign-in lineage of an account takeover. The ABIOC anchors to the account's learned factor-reset cadence and sign-in device/geo baseline rather than any static IP list, and keys on the target admin identity (emitted as normalized_actor / causality_actor_primary_username) so the endpoint- and cloud-plane legs equi-join it. This is malicious signal 1 of the chain.

dataset = okta_sso
| filter eventType in ("user.session.start", "user.authentication.sso", "user.mfa.factor.reset_all")
| alter normalized_actor = lowercase(coalesce(target_user_email, actor_alternate_id))
| alter is_reset = if(eventType = "user.mfa.factor.reset_all", 1, 0)
| alter is_privsignin = if(admin_console_access = true and auth_result = "SUCCESS", 1, 0)
| comp sum(is_reset) as resets, sum(is_privsignin) as priv_signins, min(_time) as first_seen, max(_time) as last_seen, count_distinct(client_geo_country) as countries by normalized_actor
| alter reset_to_signin_seconds = last_seen - first_seen
| filter resets >= 1 and priv_signins >= 1 and reset_to_signin_seconds <= 1800
| fields normalized_actor, resets, priv_signins, countries, reset_to_signin_seconds

## ABIOC — MP-016 Rogue Federated Identity Provider Added With Impersonation (behavioral-ML, causality-anchored)
# severity: critical
# behavioral_profile: machine-learning
# causality_anchor: Learned per-admin administrative-action baseline -> a rare IdP-lifecycle create/activate with JIT/impersonation linking by the just-taken-over admin, anchored to that identity and emitted as causality_actor_primary_username (normalized_actor) so it equi-joins the takeover and the downstream cross-cloud legs.
# A recently-compromised Okta admin creates or activates a NEW federated identity provider with JIT provisioning / automatic account-link (impersonation) enabled — a tenant-trust modification that lets the actor mint sessions impersonating arbitrary downstream users and survives a password/MFA reset of the original account. The ABIOC keys on the rarity of IdP-administration for this actor against its learned admin-action baseline, not on the raw event, and emits the same normalized_actor so it stitches to signal 1. This is the exposure_exploit persistence pivot and malicious signal 2 of the chain.

dataset = okta_sso
| filter eventType in ("system.idp.lifecycle.create", "system.idp.lifecycle.activate", "system.idp.lifecycle.update")
| filter outcome_result = "SUCCESS"
| alter normalized_actor = lowercase(actor_alternate_id)
| alter impersonation_enabled = if(idp_jit_enabled = true or idp_account_link_action = "AUTO", 1, 0)
| comp count() as idp_changes, values(idp_display_name) as new_idps, sum(impersonation_enabled) as impersonation_flags by normalized_actor, client_ip_address
| filter idp_changes >= 1 and impersonation_flags >= 1
| fields normalized_actor, new_idps, idp_changes, impersonation_flags, client_ip_address

## ABIOC — MP-016 Federated SSO AssumeRole Burst Across Cloud Accounts (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-principal cross-account SSO baseline -> a fan-out of federated role assumptions into >= 2 cloud accounts inside one window, anchored to the shared federated subject identity and emitted as causality_actor_primary_username (normalized_actor) so the cloud legs stitch to the ITDR takeover.
# A single federated subject performs a burst of SSO role assumptions — AssumeRoleWithSAML / AssumeRole / AssumeRoleWithWebIdentity — into multiple AWS accounts and Azure subscriptions in one window, the fan-out that follows a rogue-IdP add. The ABIOC anchors to the principal's learned cross-account SSO baseline and keys on the shared federated subject identity (normalized_actor) so the assumption burst equi-joins the identity-plane takeover. This is the shared_entity pivot and malicious signal 3 of the chain.

dataset = cloud_audit_logs
| filter event_name in ("AssumeRoleWithSAML", "AssumeRole", "AssumeRoleWithWebIdentity")
| filter cloud_provider in ("AWS", "AZURE")
| alter normalized_actor = lowercase(coalesce(saml_subject, principal_email, user_identity_arn))
| comp count() as role_assumptions, count_distinct(recipient_account_id) as accounts, count_distinct(assumed_role_arn) as roles, min(_time) as first_seen, max(_time) as last_seen by normalized_actor, source_ip
| alter burst_seconds = last_seen - first_seen
| filter role_assumptions >= 5 and accounts >= 2
| fields normalized_actor, role_assumptions, accounts, roles, burst_seconds, source_ip

## VALIDATION — MP-016 Privileged Okta Factor Reset From Help-Desk Flow
# purpose: hunt
# dataset: okta_sso

dataset = okta_sso
| filter eventType in ("user.mfa.factor.reset_all", "user.mfa.factor.deactivate", "system.mfa.factor.deactivate")
| filter target_admin_role = true
| alter normalized_actor = lowercase(target_user_email)
| comp count() as reset_events, values(actor_alternate_id) as reset_by by normalized_actor, client_ip_address
| filter reset_events >= 1
| fields normalized_actor, reset_by, reset_events, client_ip_address

## VALIDATION — MP-016 Azure Managed-Disk Snapshot Copied To External Subscription
# purpose: hunt
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter cloud_provider = "AZURE"
| filter event_name in ("MICROSOFT.COMPUTE/SNAPSHOTS/WRITE", "MICROSOFT.COMPUTE/DISKS/BEGINGETACCESS/ACTION", "MICROSOFT.COMPUTE/SNAPSHOTS/BEGINGETACCESS/ACTION")
| alter normalized_actor = lowercase(caller_principal_id)
| alter external_target = if(target_subscription_id != home_subscription_id, 1, 0)
| comp count() as snapshot_ops, sum(external_target) as external_copies, count_distinct(resource_id) as disks by normalized_actor, source_ip
| filter snapshot_ops >= 1 and external_copies >= 1
| fields normalized_actor, snapshot_ops, external_copies, disks, source_ip

## VALIDATION — MP-016 Cross-Cloud Takeover Stitched To One Identity
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 3600)
| alter normalized_actor = lowercase(coalesce(saml_subject, caller_principal_id, user_identity_arn))
| comp count_distinct(cloud_provider) as clouds, count_distinct(event_name) as distinct_apis, count() as api_calls by normalized_actor
| filter clouds >= 1 and distinct_apis >= 3
| fields normalized_actor, clouds, distinct_apis, api_calls

