# TTP-2026-0059 — AI Security Dashboard & Posture — Aggregate Rollup Across All AI Findings (T1526)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## VALIDATION — AISPM-006 Expected Aggregate Counts Bookkeeping
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 1800)
| filter operation_name = "terraform.output" and resource_tags contains "CortexSimAISPMFinding"
| fields _time, operation_name, resource_tags

## VALIDATION — AISPM-006 Dashboard Summary Aggregate Across All Risk Categories
# purpose: validation
# dataset: cortex_cloud_posture

dataset = cortex_cloud_posture
| filter _time > to_timestamp(current_time() - 1800)
| filter tags contains "CortexSimAISPMFinding"
| filter risk_category in ("model_security", "supply_chain", "static_analysis", "data_governance")
| comp count() as findings by risk_category, severity
| filter findings >= 1
| fields risk_category, severity, findings

## VALIDATION — AISPM-006 Dashboard Trend Series Per Risk Category
# purpose: validation
# dataset: ai_spm_findings

dataset = ai_spm_findings
| filter _time > to_timestamp(current_time() - 86400)
| filter risk_category in ("model_security", "supply_chain", "static_analysis", "data_governance")
| comp count() as data_points by risk_category, bin(_time, 1h) as time_bucket
| comp count_distinct(time_bucket) as buckets by risk_category
| filter buckets >= 1
| fields risk_category, buckets

