# TTP-2026-0100 — Anomalous Privileged Role / Consent Grant Deviating from Admin Learned Baseline — Cortex Identity ABIOC (T1098 / T1484)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — ITDR-010 Anomalous Privileged Directory Role Assignment by Non-Governance Identity (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned governance-identity baseline (read-and-sync directory activity, no privileged role assignments) -> compromised sync/automation account -> privileged directory-role assignment that diverges from the baseline, anchored to the initiating identity.
# A directory-sync / identity-automation account whose learned Cortex behavioral profile is read-and-sync governance suddenly assigns a privileged directory role (Global Administrator / Privileged Role Administrator). ABIOC anchors the deviation to the causality chain (compromised sync account -> privileged role assignment) rather than to any known-bad principal or role id, catching hybrid-cloud identity abuse that a static rule keyed on a specific bad actor would miss.

dataset = msft_azure_ad_signin
| filter category = "RoleManagement" and activity_display_name in ("Add member to role", "Add eligible member to role", "Add member to role in PIM requested (permanent)")
| filter initiating_user_principal_name in ("svc-backup@cortexsim-canary.invalid", "sync_svc@cortexsim-canary.invalid", "adconnect@cortexsim-canary.invalid")
| filter target_role in ("Global Administrator", "Privileged Role Administrator", "Application Administrator")
| comp count() as privileged_grants by initiating_user_principal_name, target_role
| filter privileged_grants >= 1
| sort desc privileged_grants
| fields initiating_user_principal_name, target_role, privileged_grants

## ABIOC — ITDR-010 High-Risk OAuth Consent and App Credential Grant Deviating from Baseline (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Privileged directory-role assignment by the sync/automation identity -> high-risk OAuth consent / service-principal credential grant carrying tenant-wide scopes that exceeds the account's learned consent baseline, anchored to the preceding role grant.
# A sync/automation identity whose learned baseline never consents to tenant-wide application scopes grants a high-risk OAuth consent or adds service-principal credentials carrying Directory.ReadWrite.All-class scopes. Every action uses legitimate Entra ID application APIs; the ABIOC fires on the deviation from the account's learned consent behavior, anchored to the privileged-role grant that preceded it in the same identity causality chain.

dataset = msft_azure_ad_signin
| filter category in ("ApplicationManagement", "UserManagement") and activity_display_name in ("Consent to application", "Add app role assignment grant to user", "Add service principal credentials", "Update application - Certificates and secrets management")
| filter initiating_user_principal_name in ("svc-backup@cortexsim-canary.invalid", "sync_svc@cortexsim-canary.invalid", "adconnect@cortexsim-canary.invalid")
| filter oauth_scope contains "Directory.ReadWrite.All" or oauth_scope contains "RoleManagement.ReadWrite.Directory" or oauth_scope contains "full_access_as_app"
| comp count() as risky_grants by initiating_user_principal_name, oauth_scope
| filter risky_grants >= 1
| sort desc risky_grants
| fields initiating_user_principal_name, oauth_scope, risky_grants

## VALIDATION — ITDR-010 Privileged Role Assignment Surfaced Outside Governance Workflow
# purpose: validation
# dataset: msft_azure_ad_signin

dataset = msft_azure_ad_signin
| filter _time > to_timestamp(current_time() - 1800)
| filter category = "RoleManagement" and activity_display_name contains "Add member to role"
| filter target_role in ("Global Administrator", "Privileged Role Administrator")
| comp count() as grants, values(target_role) as roles, earliest(_time) as first_seen by initiating_user_principal_name
| filter grants >= 1
| fields initiating_user_principal_name, roles, grants, first_seen

## VALIDATION — ITDR-010 Sync Account Governance Baseline Learned
# purpose: validation
# dataset: msft_azure_ad_signin

dataset = msft_azure_ad_signin
| filter _time > to_timestamp(current_time() - 1800)
| filter initiating_user_principal_name = "svc-backup@cortexsim-canary.invalid"
| comp count_distinct(activity_display_name) as baseline_activities by initiating_user_principal_name
| filter baseline_activities >= 1
| fields initiating_user_principal_name, baseline_activities

