# TTP-2026-0115 — Telegram Bot API Abused as Allowlisted-SaaS C2 — LampoRAT (Boggy Serpens) — Cortex Network ABIOC (T1102.002 / T1036.005)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — NDR-011 Telegram Bot API C2 Egress Deviating from Host SaaS Baseline (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-host SaaS-egress baseline (the SaaS destinations a workload role normally reaches, and their cadence/payload profile) -> a new allowlisted-SaaS destination (api.telegram.org) contacted at a tight periodic poll cadence with small stable request/response payloads, anchored to the originating source workload.
# A source workload whose learned Cortex SaaS-egress baseline never included this destination begins a periodic, small request-response poll to it — the LampoRAT Bot API poll/exfil C2 shape (modeled as the standard getUpdates/sendMessage request-response cadence; Unit 42 documents the dispatcher behavior, not the specific Bot API methods). The destination is discovered as new/rare by anti-joining src_ip against the host's learned per-host SaaS-destination baseline — it is NOT named in the query, so a globally allowlisted SaaS endpoint like api.telegram.org is caught the same way any never-before-seen SaaS destination would be; reputation and IOC matching are structurally blind. The ABIOC fires on the new-SaaS-destination-plus-poll-cadence deviation from the host's learned SaaS-egress baseline, anchored to the source workload causality chain rather than to a known-bad indicator.

dataset = panw_ngfw_traffic_raw
| filter action = "allow"
| filter app in ("telegram-base", "ssl", "web-browsing-ssl")
| filter dst_host not in host_saas_baseline.egress_dsts[src_ip]
| comp count() as poll_sessions, avg(bytes_received) as avg_resp_bytes, avg(bytes_sent) as avg_req_bytes by src_ip, dst_host
| filter poll_sessions >= 6 and avg_resp_bytes < 4096 and avg_req_bytes < 2048
| sort desc poll_sessions
| fields src_ip, dst_host, poll_sessions, avg_resp_bytes, avg_req_bytes

## ABIOC — NDR-011 avp.exe Masquerade Spawning Command Shell Stitched to Telegram C2 (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Masqueraded avp.exe (Kaspersky process name running outside the real Kaspersky install path, unsigned) -> spawns cmd.exe with the LampoRAT dispatcher string /e:ON /v:OFF /d /c -> same host concurrently beaconing to api.telegram.org, anchored to the masquerading parent process.
# On the same host that is polling the Bot API, a process named avp.exe (the Kaspersky Anti-Virus process name) runs OUTSIDE the real Kaspersky install path and spawns a command interpreter with LampoRAT's signature dispatcher argument string (cmd.exe /e:ON /v:OFF /d /c). Every name involved is legitimate, so a signature keyed on avp.exe or cmd.exe alone misfires; the ABIOC fires on the masquerade-plus-command-dispatch deviation from the host's learned process baseline, anchored to the masquerading parent and the concurrent Telegram C2 egress.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name = "avp.exe"
| filter causality_actor_process_image_name = "avp.exe"
| filter actor_process_image_path not contains "Kaspersky Lab" and actor_process_signature_status != "SIGNED"
| filter action_process_image_name = "cmd.exe"
| filter action_process_command_line contains "/e:ON" and action_process_command_line contains "/v:OFF" and action_process_command_line contains "/d /c"
| comp count() as dispatch_events by agent_hostname, causality_actor_process_image_name, actor_process_image_path, actor_process_instance_id, causality_actor_process_instance_id
| filter dispatch_events >= 1
| sort desc dispatch_events
| fields agent_hostname, causality_actor_process_image_name, actor_process_image_path, actor_process_instance_id, causality_actor_process_instance_id, dispatch_events

## VALIDATION — NDR-011 Telegram Bot API Poll and Exfil Shape Surfaced on Non-Baseline Workload
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 900)
| filter action = "allow"
| filter app in ("telegram-base", "ssl", "web-browsing-ssl")
| filter dst_host = "api.telegram.org"
| comp count() as poll_sessions, avg(bytes_received) as avg_resp_bytes by src_ip, dst_host
| filter poll_sessions >= 6
| sort desc poll_sessions
| fields src_ip, dst_host, poll_sessions, avg_resp_bytes

## VALIDATION — NDR-011 avp.exe to cmd.exe Masquerade Dispatcher Surfaced
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 900)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name = "avp.exe"
| filter action_process_image_name = "cmd.exe"
| filter action_process_command_line contains "/d /c"
| comp count() as dispatch_events by agent_hostname, actor_process_image_path
| filter dispatch_events >= 1
| fields agent_hostname, actor_process_image_path, dispatch_events

