# TTP-2026-0034 — Linux Persistence — Cron, Systemd, Backdoor User and SSH Keys (T1053.003)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — EDR-003 Cron Job Creation With Suspicious Command Path
# severity: high
# Cron job creation with suspicious command path — persistence mechanism via scheduled task. crontab installs an entry, or a cron file is written referencing a hidden/temp binary.

preset = xdr_data
| filter (event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START and actor_process_image_name = "crontab") or (event_type = ENUM.FILE and action_file_path contains_any ("/etc/cron", "/var/spool/cron"))
| filter action_process_image_command_line contains_any ("/tmp/", "/dev/shm/", "/.", "curl", "wget") or action_file_path contains "cron"

## BIOC — EDR-003 Systemd Unit With Suspicious ExecStart
# severity: high
# Systemd service unit creation with suspicious ExecStart path — persistence via system service. A .service file is written with Restart=always and an ExecStart in /tmp or /dev/shm.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter event_sub_type in (ENUM.FILE_CREATE, ENUM.FILE_WRITE)
| filter action_file_path contains ".service"
| filter action_file_path contains_any ("/etc/systemd/system", "/usr/lib/systemd/system", "/.config/systemd", "/tmp/")

## BIOC — EDR-003 Local Account Created With Sudo Group
# severity: critical
# Local account creation with sudo group membership — backdoor account for persistent access. useradd/usermod adds an account to sudo/wheel/admin.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("useradd", "usermod", "adduser")
| filter action_process_image_command_line contains_any ("sudo", "wheel", "admin", "root")

## BIOC — EDR-003 SSH Key Generation Then Authorized Keys Write
# severity: high
# SSH key generation followed by authorized_keys write — key-based persistence installation. ssh-keygen runs and an authorized_keys file is written.

preset = xdr_data
| filter (event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START and actor_process_image_name = "ssh-keygen") or (event_type = ENUM.FILE and event_sub_type in (ENUM.FILE_CREATE, ENUM.FILE_WRITE) and action_file_path contains "authorized_keys")

## BIOC — EDR-003 Shell Profile Modified With Background Execution
# severity: high
# Shell profile modification with nohup background execution — login-triggered persistence. A shell init file is written containing nohup/disown background launch.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter event_sub_type in (ENUM.FILE_CREATE, ENUM.FILE_WRITE)
| filter action_file_path contains_any (".bashrc", ".bash_profile", ".profile", "/etc/profile", ".zshrc")
| filter actor_process_image_name in ("bash", "sh", "echo", "tee", "cat", "vi", "vim", "sed")

## VALIDATION — EDR-003 Analytics Crontab Modification Non-Interactive
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name = "crontab" or action_process_image_command_line contains "crontab"
| fields _time, agent_hostname, actor_effective_username, action_process_image_command_line, causality_actor_process_image_name

## VALIDATION — EDR-003 Analytics Service Unit Restart Always Hidden Path
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.FILE and action_file_path contains ".service"
| fields _time, agent_hostname, actor_process_image_name, action_file_path

## VALIDATION — EDR-003 Analytics User Account Creation Non-Login Session
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("useradd", "adduser", "chpasswd")
| fields _time, agent_hostname, actor_effective_username, action_process_image_command_line

## VALIDATION — EDR-003 Analytics ssh-keygen Non-Interactive Persistence
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name = "ssh-keygen"
| fields _time, agent_hostname, actor_effective_username, action_process_image_command_line

## VALIDATION — EDR-003 Analytics Shell Init File Modification
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.FILE and event_sub_type in (ENUM.FILE_CREATE, ENUM.FILE_WRITE)
| filter action_file_path contains_any (".bashrc", ".profile", ".bash_profile", ".zshrc")
| fields _time, agent_hostname, actor_process_image_name, action_file_path

