# TTP-2026-0017 — Prisma Browser — Credential Paste into Untrusted Origin (T1552)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — Prisma Browser — credential-shape paste into non-sanctioned origin (DLP rule)
# severity: high
# Prisma Browser — credential-shape paste into non-sanctioned origin (DLP rule). A paste action carrying a credential-classified payload lands in a password/secret field on an origin that is not on the sanctioned SaaS allowlist.

dataset = prisma_browser_events
| filter action = "paste"
| filter data_classification in ("credential", "secret", "password")
| filter origin not in ("login.corp.example.com", "okta.corp.example.com", "login.microsoftonline.com")
| filter target_selector contains "password" or url contains "signin" or url contains "login"

## VALIDATION — Pre-flight: plugin metadata visible to operator
# purpose: validation
# dataset: prisma_browser_events

dataset = prisma_browser_events
| filter _time > to_timestamp(current_time() - 1800)
| filter campaign_id = "BC-BROWSER-001"
| filter action in ("navigate", "paste")
| fields _time, campaign_id, action, origin, url, user
| sort asc _time

## VALIDATION — Prisma Browser — paste source vs. destination origin mismatch
# purpose: validation
# dataset: prisma_browser_events

dataset = prisma_browser_events
| filter _time > to_timestamp(current_time() - 1800)
| filter action = "paste"
| filter data_classification in ("credential", "secret", "password")
| filter origin not in ("login.corp.example.com", "okta.corp.example.com", "login.microsoftonline.com")
| fields _time, user, origin, url, action, data_classification, cortex_canary
| sort desc _time

## VALIDATION — PB → XSIAM — alert with origin URL + paste DLP rule fires within MTTD target
# purpose: validation
# dataset: prisma_browser_events

dataset = prisma_browser_events
| filter _time > to_timestamp(current_time() - 1800)
| filter action = "paste" and cortex_canary = "CANARY-CRED-001"
| fields _time, user, origin, url, dlp_rule_name, data_classification, cortex_canary
| sort desc _time

