# TTP-2026-0081 — XDM Container Telemetry Normalization — Modeling-Rule Substrate Proof (T1610 / T1613)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — CDR-XDM Privileged Container Start on Modeled Field
# severity: medium
# Fires on a container start where the modeled privileged field (normalized from the raw actor_container_info blob by the modeling rule) is true. This BIOC only works BECAUSE the modeling rule made privileged addressable — proving the raw-source to modeled-field to detection chain.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_container_info != null
| alter privileged = json_extract_scalar(actor_container_info, "$.privileged")
| filter privileged = "true"
| fields agent_hostname, actor_process_image_name, privileged
| comp count() as privileged_starts by agent_hostname
| filter privileged_starts >= 1

## VALIDATION — CDR-XDM Modeled Container Fields Populated
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 600)
| filter actor_container_info != null
| alter pod_namespace = json_extract_scalar(actor_container_info, "$.pod_namespace")
| alter privileged = json_extract_scalar(actor_container_info, "$.privileged")
| filter pod_namespace != null
| comp count() as modeled_events by pod_namespace, privileged
| filter modeled_events >= 1
| fields pod_namespace, privileged, modeled_events

