# TTP-2026-0083 — Kubernetes-Goat Container Escape Chain — Cortex Cloud CDR (T1611 / T1610)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — CDR-011 Container Escape via DIND nsenter or Host Namespace
# severity: high
# A containerized process invokes nsenter against PID 1 namespaces or runs the Docker client with the host root bind-mounted (docker run -v /:/host), the canonical DIND/privileged-container escape primitives Kubernetes-Goat exposes (T1611 Escape to Host).

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_container_info != null
| filter action_process_image_name in ("nsenter", "docker", "runc")
| filter action_process_image_command_line contains "-t 1" or action_process_image_command_line contains "/:/host" or action_process_image_command_line contains "--privileged"
| comp count() as escape_attempts by agent_hostname, action_process_image_name
| filter escape_attempts >= 1
| fields agent_hostname, action_process_image_name, escape_attempts

## BIOC — CDR-011 Host Path Mount Access from Container
# severity: high
# A process inside a container reads or writes a mounted host-path directory (/host/etc, /host/root, /host/proc), the host-filesystem-breakout primitive used after a privileged or hostPath-mounted goat pod is reached (T1611 Escape to Host).

dataset = xdr_data
| filter event_type = ENUM.FILE
| filter actor_container_info != null
| filter action_file_path contains "/host/etc" or action_file_path contains "/host/root" or action_file_path contains "/host/proc"
| comp count() as host_path_touches by agent_hostname, actor_process_image_name
| filter host_path_touches >= 1
| sort desc host_path_touches
| fields agent_hostname, actor_process_image_name, host_path_touches

## VALIDATION — CDR-011 Container Workload Projection
# purpose: hunt
# dataset: xdr_data

dataset = xdr_data
| fields actor_container_info as container_info
| filter container_info != null
| alter pod_namespace = json_extract_scalar(container_info, "$.pod_namespace")
| alter pod_name = json_extract_scalar(container_info, "$.pod_name")
| alter image_name = json_extract_scalar(container_info, "$.image_name")
| alter image_id = json_extract_scalar(container_info, "$.image_id")
| alter container_id = json_extract_scalar(container_info, "$.id")
| alter privileged = json_extract_scalar(container_info, "$.privileged")
| filter actor_process_image_name in ("nsenter", "docker", "runc", "sh", "bash")

## VALIDATION — CDR-011 Container Escape to Host Process Activity
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 900)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("nsenter", "docker", "runc")
| filter action_process_image_name in ("sh", "bash", "chroot", "id", "cat")
| comp count() as host_proc_events by agent_hostname, actor_process_image_name
| filter host_proc_events >= 1
| sort desc host_proc_events
| fields agent_hostname, actor_process_image_name, host_proc_events

