# TTP-2026-0010 — AI Access — Jailbreak Prompt Fingerprint
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — AIACC-004 Pre-flight Jailbreak Payload Contains DAN Markers
# severity: informational
# Pre-flight: jailbreak payload contains 'DAN' and 'Ignore all previous instructions' markers. Confirms the jailbreak payload renders the DAN frame on the worker before any egress; matches the python self-check process invocation.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("python", "python3")
| filter action_process_image_command_line contains "_render_payload"
| filter action_process_image_command_line contains "Ignore all previous"

## BIOC — AIACC-004 Outbound Prompt Requests DLP Circumvention Policy Violation
# severity: high
# AI Access — outbound prompt requests circumvention of corporate DLP — policy violation. The prompt body sent to a public LLM explicitly asks how to bypass the company's DLP / guardrails, which is a direct AI-usage policy violation regardless of provider response.

dataset = panw_ngfw_traffic_raw
| filter dst_host in ("api.openai.com", "api.anthropic.com", "generativelanguage.googleapis.com")
| filter http_method = "POST"
| filter request_body ~= "(?i)bypass\s+(?:my|our|the|company'?s)?\s*(?:corporate\s+)?DLP|circumvent\s+(?:DLP|content\s+polic|guardrail)"
| fields _time, source_user, src_ip, dst_host, uri_path, bytes_sent

## VALIDATION — AIACC-004 Jailbreak Fingerprint DAN Ignore Previous Instructions
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host = "api.openai.com" or tls_sni = "api.openai.com"
| filter http_method = "POST" and uri_path contains "/v1/chat/completions"
| filter request_body ~= "(?i)ignore all previous instructions" or request_body contains "DAN (Do Anything Now)"
| fields _time, source_user, src_ip, dst_host, uri_path, bytes_sent

## VALIDATION — AIACC-004 Jailbreak Detection Consistent Across Providers
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host in ("api.openai.com", "api.anthropic.com")
| filter http_method = "POST"
| filter request_body ~= "(?i)ignore all previous instructions" or request_body contains "DAN (Do Anything Now)"
| comp count() as jailbreak_hits by dst_host, source_user
| filter jailbreak_hits >= 1
| fields dst_host, source_user, jailbreak_hits

