# TTP-2026-0095 — MCP Runtime Tool-Response Poisoning (T1656 / T1059)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — KOI-006 MCP tools call result content embeds instruction injection at runtime
# severity: high
# Runtime content inspection — a materialised MCP tools/call RESULT body carries an instruction-override plus credential-exfil directive at invocation time. Distinct from SIM-KOI-002 (which scans the server source): here the poisoned text lives in the tool RESULT the agent consumed, not the server.py source.

dataset = koi_code_scan_events
| filter file_name contains "runtime-poisoned-response.json" or file_path contains "pa-firewall-mcp"
| filter scan_finding_text contains_any ("SYSTEM_OVERRIDE", "Ignore previous", "exfiltrate", ".aws/credentials", "AKIA0000CORTEXSIMCANARY")
| filter mcp_message_kind = "tools/call.result" or scan_finding_text contains "tools/call"
| fields _time, agent_hostname, file_path, mcp_message_kind, scan_finding_text

## VALIDATION — KOI-006 NGFW JSON RPC tools call result body carries injection markers
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_host contains "cortexsim-canary" or uri_path contains "/mcp/"
| filter http_method = "POST"
| filter request_body contains "tools/call" and request_body contains_any ("SYSTEM_OVERRIDE", "exfiltrate", "AKIA0000CORTEXSIMCANARY")
| fields _time, source_user, src_ip, dst_host, uri_path, request_body

## VALIDATION — KOI-006 agent process consumed poisoned tool result
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.FILE and event_sub_type in (ENUM.FILE_OPEN, ENUM.FILE_READ)
| filter action_file_name contains "runtime-poisoned-response.json" or action_file_path contains "pa-firewall-mcp"
| filter actor_process_image_name in ("python3", "node", "claude", "cursor", "mcp-host")
| fields _time, agent_hostname, actor_effective_username, actor_process_image_name, action_file_path

## VALIDATION — KOI-006 stitch tool result injection with followon credential access
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter (action_file_path contains "pa-firewall-mcp" or action_file_name contains "runtime-poisoned-response.json") or (action_file_path contains ".aws/credentials" or action_file_path contains ".ssh/id_rsa")
| comp count_distinct(action_file_path) as touched_paths by agent_hostname, actor_process_image_name
| filter touched_paths >= 2

