# TTP-2026-0053 — SMB/RPC Lateral Sweep — Internal Host Discovery (T1046 / T1018 / T1021.002)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — NGFW EAL — anomalous SMB traffic outside admin baseline
# severity: high
# NGFW EAL — anomalous SMB traffic outside admin baseline

dataset = panw_ngfw_traffic_raw
| filter dst_port in (445, 139, 135) or app in ("smb", "ms-ds-smb", "msrpc", "netbios-ss")
| filter src_ip != null
| comp count_distinct(dst_ip) as dst_host_count, count() as session_count by src_ip, dst_port
| filter dst_host_count >= 8
| fields src_ip, dst_port, dst_host_count, session_count

## VALIDATION — Dry-run report shows planned host count and ports
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_port in (445, 139, 135)
| filter dst_ip in ("10.50.10.0/24")
| comp count_distinct(dst_ip) as planned_hosts by src_ip, dst_port
| fields src_ip, dst_port, planned_hosts

## VALIDATION — NGFW EAL — host sweeping pattern (1 src to many dst on TCP/445)
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_port = 445
| filter dst_ip in ("10.50.10.0/24")
| comp count_distinct(dst_ip) as swept_hosts, count() as sessions by src_ip, dst_port
| filter swept_hosts >= 8
| fields src_ip, dst_port, swept_hosts, sessions

## VALIDATION — XSIAM correlation — sweep src host stitched with workstation context
# purpose: validation
# dataset: panw_ngfw_traffic_raw

preset = network_story
| filter _time > to_timestamp(current_time() - 1800)
| filter dst_port in (445, 139, 135)
| filter dst_ip in ("10.50.10.0/24")
| join type=inner (xdr_data
    | filter event_type = ENUM.NETWORK
    | fields agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, causality_id, src_ip as ep_src_ip) as ep ep.ep_src_ip = src_ip
| comp count_distinct(dst_ip) as swept_hosts by src_ip, ep.agent_hostname, ep.causality_actor_process_image_name, ep.causality_actor_process_instance_id
| filter swept_hosts >= 8
| fields src_ip, ep.agent_hostname, ep.causality_actor_process_image_name, ep.causality_actor_process_instance_id, swept_hosts

