# TTP-2026-0021 — Prisma Browser — Screen Capture of Sensitive SaaS Page (T1113)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — Prisma Browser — page.screenshot() called against origin tagged sensitive — block + alert
# severity: medium
# Prisma Browser — page.screenshot() called against origin tagged sensitive — block + alert. A programmatic screen capture targets a page whose origin is classified sensitive; policy blocks and alerts.

dataset = prisma_browser_events
| filter action = "screen-capture"
| filter data_classification in ("sensitive", "confidential", "restricted")
| filter origin in ("crm.cortexsim-test.invalid", "crm.corp.example.com", "salesforce.com")
| filter capture_method in ("page.screenshot", "getDisplayMedia", "os-capture")

## VALIDATION — Pre-flight: plugin metadata visible to operator
# purpose: validation
# dataset: prisma_browser_events

dataset = prisma_browser_events
| filter _time > to_timestamp(current_time() - 1800)
| filter campaign_id = "BC-BROWSER-005"
| filter action in ("navigate", "screen-capture")
| fields _time, campaign_id, action, origin, url, out_path
| sort asc _time

## VALIDATION — Prisma Browser — screen-capture-attempt counter increments under sensitive-content policy
# purpose: validation
# dataset: prisma_browser_events

dataset = prisma_browser_events
| filter _time > to_timestamp(current_time() - 1800)
| filter action = "screen-capture"
| filter data_classification in ("sensitive", "confidential", "restricted")
| comp count() as capture_attempts by user, origin
| filter capture_attempts >= 1
| fields user, origin, capture_attempts

## VALIDATION — Prisma Browser — repeat screen-capture from same user counts toward elevated risk score
# purpose: validation
# dataset: prisma_browser_events

dataset = prisma_browser_events
| filter _time > to_timestamp(current_time() - 1800)
| filter action = "screen-capture"
| comp count() as captures by user
| filter captures >= 2
| fields user, captures

## VALIDATION — XSIAM — user risk score elevated, conditional-access policy triggered downstream
# purpose: validation
# dataset: prisma_browser_events

dataset = prisma_browser_events
| filter _time > to_timestamp(current_time() - 1800)
| filter action = "screen-capture"
| comp count() as captures, max(user_risk_score) as risk_score by user
| filter captures >= 2 or risk_score >= 60
| fields user, captures, risk_score

