# TTP-2026-0046 — Malicious Claude Skill With Hidden Instructions In skill.md (T1656 / T1195)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — KOI-005 Claude Skill Body Contains Instruction Injection And Exfil Directives
# severity: high
# Code scan — skill.md contains 'Ignore previous instructions' / exfil instructions in body. A read of a Claude skill.md surfaces an instruction-override plus credential-exfil and --no-verify directive in the skill body.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("grep", "head", "cat", "cortexcloud", "checkov", "node", "python3")
| filter action_process_image_command_line contains "skill.md"
| filter action_process_image_command_line contains_any ("ignore previous", "exfiltrate", ".ssh", "--no-verify", "aws_access_key")

## VALIDATION — KOI-005 Claude Skill Claims Verified Publisher With Mismatched Signature
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("jq", "grep", "cat", "cortexcloud", "checkov")
| filter action_process_image_command_line contains "code-reviewer.skill"
| filter action_process_image_command_line contains_any ("manifest", "publisher_signature", "verified-publisher")
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

## VALIDATION — KOI-005 Claude Client Fetches Skill Bundle From Non Anthropic CDN
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.NETWORK
| filter dst_action_external_hostname contains "cortexsim-canary" or dns_query_name contains "cortexsim-canary"
| filter action_external_url contains "/skills/" or action_external_url contains ".skill"
| fields _time, agent_hostname, actor_process_image_name, dst_action_external_hostname, action_external_url, http_req_user_agent

## VALIDATION — KOI-005 Skill Fetch Destination Not In Anthropic Registry Allowlist
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.NETWORK
| filter action_external_url contains "/skills/" or action_external_url contains ".skill"
| filter dst_action_external_hostname not contains "anthropic.com"
| filter dst_action_external_hostname not contains "claude.ai"
| fields _time, agent_hostname, actor_process_image_name, dst_action_external_hostname, action_external_url

## VALIDATION — KOI-005 AIRS Indirect Injection Scorer On Skill Body In Prompt
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.NETWORK
| filter action_external_url contains_any ("/v1/messages", "/v1/chat/completions", "generateContent") or action_app_id_transitions contains "airs"
| filter dst_action_external_hostname contains_any ("anthropic", "openai", "googleapis", "cortexsim-canary")
| fields _time, agent_hostname, actor_process_image_name, dst_action_external_hostname, action_external_url

## VALIDATION — KOI-005 XSIAM Stitch Skill Injection Artifact With AIRS Detection
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter action_process_image_command_line contains "code-reviewer.skill" or action_external_url contains_any ("/skills/", "/v1/messages", "/v1/chat/completions")
| comp count_distinct(event_type) as signal_planes by agent_hostname
| filter signal_planes >= 2

