# TTP-2026-0041 — ITDR — Brute-Force Causing Account Lockout (Microsoft)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — ITDR-005 Pre-Flight idp_signin_emulator Metadata Visible
# severity: informational
# Pre-flight: idp_signin_emulator metadata visible to operator. Confirms the EAL plugin is registered and exposes brute_force_lockout targets before the burst is emitted, so a null downstream result is a harness fault rather than a detection miss.

dataset = msft_azure_ad_signin
| filter auth_outcome in ("FAILURE", "SUCCESS") or _raw_log contains "brute_force_lockout"
| comp count() as preflight_events by user_name
| filter preflight_events >= 0

## BIOC — ITDR-005 Account Lock State Transition Recorded
# severity: high
# ITDR — user.account.lock state-transition event recorded. Captures the Microsoft Entra lockout result type emitted when the consecutive-failure burst crosses the lockout threshold for the target identity.

dataset = msft_azure_ad_signin
| filter result_type = "user.account.lock" or auth_status_detail contains "locked" or _raw_log contains "user.account.lock"
| fields _time, user_name, src_ip, src_geo_country, result_type, auth_status_detail

## VALIDATION — ITDR-005 Ten Consecutive Failed Sign-Ins Brute Force
# purpose: validation
# dataset: msft_azure_ad_signin

dataset = msft_azure_ad_signin
| filter _time > to_timestamp(current_time() - 1800)
| filter auth_outcome = "FAILURE"
| comp count() as fail_count, count_distinct(src_ip) as ip_count, earliest(_time) as first_seen, latest(_time) as last_seen by user_name
| alter window_minutes = divide(subtract(last_seen, first_seen), 60000000)
| filter fail_count >= 10 and window_minutes <= 30
| fields user_name, fail_count, ip_count, window_minutes

## VALIDATION — ITDR-005 Second Lockout Within One Hour Escalates Severity
# purpose: validation
# dataset: msft_azure_ad_signin

dataset = msft_azure_ad_signin
| filter _time > to_timestamp(current_time() - 3600)
| filter result_type = "user.account.lock" or auth_status_detail contains "locked" or _raw_log contains "user.account.lock"
| comp count() as lockout_count, count_distinct(src_ip) as ip_count, earliest(_time) as first_seen, latest(_time) as last_seen by user_name
| alter window_minutes = divide(subtract(last_seen, first_seen), 60000000)
| alter severity = if(lockout_count >= 2, "high", "medium")
| filter lockout_count >= 2 and window_minutes <= 60
| fields user_name, lockout_count, ip_count, window_minutes, severity

## VALIDATION — ITDR-005 XSIAM Repeat-Lockout Grouped Password Spray
# purpose: validation
# dataset: msft_azure_ad_signin

dataset = msft_azure_ad_signin
| filter _time > to_timestamp(current_time() - 3600)
| filter result_type = "user.account.lock" or auth_status_detail contains "locked" or _raw_log contains "user.account.lock"
| comp count() as lockout_events, count_distinct(src_ip) as distinct_origins, values(src_geo_country) as origin_countries by user_name
| filter lockout_events >= 1
| fields user_name, lockout_events, distinct_origins, origin_countries

