# TTP-2026-0176 — Shelf-Staged Privilege-Escalation Enumeration Under a Service Identity (T1082)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — EDR-022 Service Account Spawns Interpreter Under Web Server CGO
# severity: high
# A non-interactive service identity (www-data/apache/nginx/nobody) spawns a shell or scripting interpreter whose causality group owner is the web server itself. BEHAVIOURAL: the web tier has no operational reason to spawn an interpreter, so this fires whatever the interpreter goes on to run — it is the first link of the TC-EDR-05 chain and it survives any rename of the staged tool.

preset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_effective_username in ("www-data", "apache", "nginx", "nobody", "httpd")
| filter action_process_image_name in ("bash", "sh", "dash", "python3", "python", "perl")
| filter causality_actor_process_image_name in ("apache2", "httpd", "nginx", "php-fpm")
| fields _time, agent_hostname, causality_actor_process_image_name, causality_actor_process_instance_id, causality_id, actor_effective_username, action_process_image_command_line

## BIOC — EDR-022 Privilege Escalation Read Fan Out From One Causality Chain
# severity: high
# One causality chain reads across four or more distinct privilege-escalation-relevant paths (/etc/passwd, /etc/shadow, /etc/sudoers, /etc/crontab, /root, /proc/*/cmdline, SSH key material) inside a short window. BEHAVIOURAL: keys on the BREADTH of the read fan-out, not on any binary name, so it is the detection that must still fire when the tool is staged under an innocuous filename.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter action_file_path contains_any ("/etc/passwd", "/etc/shadow", "/etc/sudoers", "/etc/crontab", "/root/", "/proc/", "/.ssh/", "id_rsa")
| filter actor_effective_username not in ("root")
| comp count_distinct(action_file_path) as privesc_read_breadth by causality_id, actor_effective_username, agent_hostname
| filter privesc_read_breadth >= 4

## BIOC — EDR-022 Automated Discovery Binary Breadth Burst
# severity: high
# Six or more DISTINCT discovery binaries execute from one causality_actor_process_instance_id inside a short window. BEHAVIOURAL: an automated enumerator has a breadth-and-rate signature no interactive session produces, which is why this holds when the enumerator is renamed and why it is the primary evidence for TC-EDR-05 rather than any tool-name match.

preset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_name in ("id", "uname", "hostname", "whoami", "ps", "find", "mount", "getcap", "sudo", "lsmod", "netstat", "ss", "env", "df")
| filter actor_effective_username not in ("root")
| comp count_distinct(action_process_image_name) as discovery_breadth by causality_actor_process_instance_id, causality_id, agent_hostname
| filter discovery_breadth >= 6

## BIOC — EDR-022 Staging Directory Script Executed By Service Account
# severity: high
# A service identity executes a file that lives under a world-writable staging directory (/tmp, /var/tmp, /dev/shm). BEHAVIOURAL: keys on WHERE the executable came from and WHO ran it. The payload shelf stages into exactly these roots by design (adapter_loader._ALLOWED_STAGE_ROOTS), so this detection is the one a customer's coverage most needs to have and the one a rename cannot evade.

preset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_path contains_any ("/tmp/", "/var/tmp/", "/dev/shm/")
| filter actor_effective_username in ("www-data", "apache", "nginx", "nobody", "httpd")
| fields _time, agent_hostname, causality_id, actor_effective_username, action_process_image_path, action_process_image_command_line

## BIOC — EDR-022 Filename Keyed Linpeas Command Line Negative Control
# severity: medium
# NEGATIVE-CONTROL TARGET, NOT COVERAGE. Matches the literal string 'linpeas' on the command line. This fires on the canonical run and is EXPECTED NOT TO FIRE once the artifact is staged under an operator-chosen name (payload shelf FILENAME_KEYED_DETECTIONS_SUPPRESSED). It is authored so the control has something to darken. If a renamed run darkens this AND the behavioural BIOCs above, the finding is that the customer's endpoint coverage is name-keyed — never that the TTP did not run.

preset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_command_line contains "linpeas"
| fields _time, agent_hostname, causality_id, actor_effective_username, action_process_image_command_line

## BIOC — EDR-022 High Rate Proc Cmdline Sweep Across Distinct Pids
# severity: high
# One non-root process reads /proc/<pid>/cmdline or /proc/<pid>/stat for twenty or more distinct pids in a short window. BEHAVIOURAL: that is what a process-table snooper looks like in file telemetry regardless of what the binary is called, and it is the shape that catches credentials passed on a cron command line.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter action_file_path contains "/proc/"
| filter action_file_path contains_any ("/cmdline", "/stat", "/environ")
| filter actor_effective_username not in ("root")
| comp count_distinct(action_file_path) as proc_paths_read by causality_id, actor_process_image_name, agent_hostname
| filter proc_paths_read >= 20

## BIOC — EDR-022 Service Account Reads Cron Scheduling Paths
# severity: medium
# A web/service identity reads cron scheduling state (/etc/crontab, /etc/cron.d, /etc/cron.daily, /var/spool/cron) it has no operational reason to read. BEHAVIOURAL: identity plus path, no tool name.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter action_file_path contains_any ("/etc/crontab", "/etc/cron.", "/var/spool/cron")
| filter actor_effective_username in ("www-data", "apache", "nginx", "nobody", "httpd")
| fields _time, agent_hostname, causality_id, actor_effective_username, actor_process_image_name, action_file_path

## BIOC — EDR-022 Filesystem Wide Suid Sgid Sweep By Service Account
# severity: high
# A non-root service identity runs a filesystem-wide SUID/SGID sweep — `find` with -perm -4000/-2000/-u+s, or an equivalent stat walk. BEHAVIOURAL: the sweep is the signal; SUID3NUM, linpeas, LinEnum and a hand-typed find all produce it identically.

preset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_name in ("find", "stat", "getcap")
| filter action_process_image_command_line contains_any ("-perm -4000", "-perm -2000", "-perm -u+s", "-perm /6000", "-4000")
| filter actor_effective_username not in ("root")
| fields _time, agent_hostname, causality_id, actor_effective_username, action_process_image_command_line

## BIOC — EDR-022 Interpreter Executes Staging Directory Script As Service Account
# severity: medium
# A language interpreter (python3/perl/ruby) is invoked by a service identity with a script argument under a staging directory. BEHAVIOURAL: interpreter + staging path + non-interactive identity. A rename of the script changes the argument's basename and not one clause of this rule.

preset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_name in ("python3", "python", "perl", "ruby")
| filter action_process_image_command_line contains_any ("/tmp/", "/var/tmp/", "/dev/shm/")
| filter actor_effective_username in ("www-data", "apache", "nginx", "nobody", "httpd")
| fields _time, agent_hostname, causality_id, actor_effective_username, action_process_image_command_line

## VALIDATION — EDR-022 Validate Service Account Enumeration Burst In Last 30m
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_effective_username in ("www-data", "apache", "nginx", "nobody", "httpd")
| filter causality_actor_process_image_name in ("apache2", "httpd", "nginx", "php-fpm")
| comp count_distinct(action_process_image_name) as discovery_breadth by causality_id, agent_hostname
| filter discovery_breadth >= 6

## VALIDATION — EDR-022 Validate Proc Cmdline Sweep From Non Root Identity
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.FILE
| filter action_file_path contains "/proc/" and action_file_path contains "/cmdline"
| filter actor_effective_username not in ("root")
| fields _time, agent_hostname, causality_id, actor_process_image_name, action_file_path

## VALIDATION — EDR-022 Validate Suid Sweep From Service Account In Last 30m
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_command_line contains_any ("-perm -4000", "-perm -2000", "-perm -u+s")
| fields _time, agent_hostname, causality_id, actor_effective_username, action_process_image_command_line

## VALIDATION — EDR-022 Hunt Staging Directory Executions By Non Interactive Identities
# purpose: hunt
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 86400)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_path contains_any ("/tmp/", "/var/tmp/", "/dev/shm/")
| filter actor_effective_username not in ("root")
| comp count() as execs by agent_hostname, actor_effective_username, action_process_image_path
| sort desc execs

