# TTP-2026-0032 — Linux Credential Dumping — /etc/shadow and Mimipenguin (T1003.008)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — EDR-001 Shadow File Read by Non-Root Service Account
# severity: high
# Credential file access — /etc/shadow read attempt from non-root service account (www-data). A process not owned by root opens /etc/shadow, the Linux hashed-credential store.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter action_file_path = "/etc/shadow"
| filter actor_effective_username not in ("root")
| filter actor_process_image_name in ("cat", "unshadow", "head", "less", "more", "dd", "cp", "awk", "python3", "perl")

## BIOC — EDR-001 Broad Credential File Sweep Across Home Directories
# severity: high
# Broad credential file search across home directories — SSH key and history file harvesting. A find process enumerates id_rsa/id_ed25519/.bash_history/.pgpass/.my.cnf across /home and /root.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name = "find"
| filter action_process_image_command_line contains_any ("id_rsa", "id_ed25519", ".bash_history", ".pgpass", ".my.cnf", ".pem", ".key")
| filter actor_effective_username not in ("root")

## BIOC — EDR-001 Process Memory Scrape via proc environ
# severity: high
# Process memory reading via /proc — credential extraction from service process memory spaces. strings/cat reads /proc/<pid>/environ or /proc/<pid>/maps of another service process.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter action_file_path ~= "/proc/[0-9]+/(environ|maps|mem)"
| filter actor_process_image_name in ("strings", "cat", "dd", "grep", "head", "python3")

## BIOC — EDR-001 Mimipenguin Credential Dumper Execution
# severity: critical
# Mimipenguin execution — known credential dumping tool signature detected by XDR Agent. bash runs mimipenguin.sh, or a process reads /proc memory immediately after a curl-to-bash fetch.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter action_process_image_command_line contains "mimipenguin"
| filter actor_process_image_name in ("bash", "sh", "curl")

## VALIDATION — EDR-001 Analytics Non-Root Passwd Enumeration
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.FILE and action_file_path = "/etc/passwd"
| filter actor_effective_username not in ("root")
| fields _time, agent_hostname, actor_effective_username, actor_process_image_name, action_process_image_command_line

## VALIDATION — EDR-001 Analytics Unauthorized Shadow Access Pattern
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.FILE and action_file_path = "/etc/shadow"
| filter actor_effective_username != "root"
| comp count() as shadow_reads by agent_hostname, actor_effective_username, actor_process_image_name
| filter shadow_reads >= 1

## VALIDATION — EDR-001 Analytics Recursive Credential File Search
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name = "find"
| filter action_process_image_command_line contains_any ("id_rsa", "id_ed25519", ".pgpass", ".my.cnf", ".bash_history")
| fields _time, agent_hostname, actor_effective_username, action_process_image_command_line

## VALIDATION — EDR-001 Analytics Sequential Proc Environ Access
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.FILE and action_file_path ~= "/proc/[0-9]+/environ"
| comp count_distinct(action_file_path) as proc_targets by agent_hostname, actor_process_image_name
| filter proc_targets >= 2

## VALIDATION — EDR-001 Analytics Curl To Bash Credential Tool
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_command_line contains "mimipenguin" or (actor_process_image_name = "curl" and action_process_image_command_line contains "raw.githubusercontent.com")
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line, causality_actor_process_image_name

