# TTP-2026-0175 — Adversary Capability Development — Phishing-Kit and LLM Prompt-Farm Staging Detected Before Weaponization
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — First Estate Contact With Pre-Weaponization Staging Infrastructure (behavioral-ML, causality-anchored)
# severity: medium
# behavioral_profile: machine-learning
# causality_anchor: The client process making first contact owns the endpoint chain; it is joined to the intel record on the shared FQDN, which is the only entity the feed and the session have in common.
# The match, and the only leg of this scenario that involves the customer's own telemetry at all. First-ever contact from the estate to a host that the platform already held intel on before the contact happened. Anchored on first-contact rather than on volume because capability-development infrastructure is touched once, quietly, by whoever clicks first — there is no beacon cadence to profile yet, and waiting for one means waiting for weaponization.

dataset = panw_ngfw_traffic_raw
| filter cortexsim_run_tag = "TIM009"
| filter dest_fqdn contains "adversary-dev.example" and intel_match = true
| comp count() as sessions, min(_time) as first_contact_time, count_distinct(source_ip) as internal_hosts by dest_fqdn, indicator_confidence
| filter sessions >= 1 and indicator_confidence >= 70
| sort desc sessions
| fields dest_fqdn, indicator_confidence, internal_hosts, sessions, first_contact_time

## VALIDATION — Adversary Obtained a Commodity Prompt-Farm Tool for Lure Mass-Production
# purpose: validation
# dataset: threat_intel

dataset = threat_intel
| filter _time > to_timestamp(current_time() - 86400)
| filter cortexsim_run_tag = "TIM009"
| filter capability_class = "tool" and acquisition = "commodity_marketplace"
| comp count() as reports by tool_name, capability_purpose, indicator_source
| filter reports >= 1
| sort desc reports
| fields tool_name, capability_purpose, indicator_source, reports

## VALIDATION — Capability Intel Landed Strictly Before Any Estate Contact With the Staging Host
# purpose: validation
# dataset: threat_intel

dataset = threat_intel
| filter _time > to_timestamp(current_time() - 86400)
| filter cortexsim_run_tag = "TIM009" and indicator_source = "taxii"
| alter lead_seconds = timestamp_diff(first_estate_contact_time, indicator_ingest_time, "SECOND")
| filter lead_seconds > 0
| comp min(lead_seconds) as smallest_lead, max(lead_seconds) as largest_lead, count() as indicators by indicator_value
| sort desc smallest_lead
| fields indicator_value, indicators, smallest_lead, largest_lead

## VALIDATION — Campaign Attribution and Actor Context Attach to the Live Match
# purpose: validation
# dataset: threat_intel

dataset = threat_intel
| filter _time > to_timestamp(current_time() - 86400)
| filter cortexsim_run_tag = "TIM009" and attached_to_case = true
| comp count() as attributed_matches, count_distinct(campaign_name) as campaigns by indicator_value, actor_context_present
| filter attributed_matches >= 1 and actor_context_present = true
| sort desc attributed_matches
| fields indicator_value, campaigns, actor_context_present, attributed_matches

## VALIDATION — Retro-Hunt Swept Historical Telemetry When the Capability Intel Landed
# purpose: validation
# dataset: threat_intel

dataset = threat_intel
| filter _time > to_timestamp(current_time() - 86400)
| filter cortexsim_run_tag = "TIM009" and retro_hunt_triggered = true
| comp count() as sweeps, sum(historical_matches_found) as historical_matches, max(retention_days_searched) as days_searched by indicator_value
| filter sweeps >= 1
| sort desc historical_matches
| fields indicator_value, sweeps, days_searched, historical_matches

## VALIDATION — Low-Confidence Control Indicator From the Same Batch Was Scored and Not Promoted
# purpose: validation
# dataset: threat_intel

dataset = threat_intel
| filter _time > to_timestamp(current_time() - 86400)
| filter cortexsim_run_tag = "TIM009" and indicator_source = "taxii"
| filter confidence < 30 and promoted_to_detection = false
| comp count() as suppressed_indicators by indicator_value, confidence, feed_batch_id
| filter suppressed_indicators >= 1
| fields indicator_value, confidence, feed_batch_id, suppressed_indicators

## VALIDATION — Estate Contact With Any Pre-Weaponization Staging Indicator in the Retention Window
# purpose: hunt
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 604800)
| filter intel_match = true and intel_kill_chain_phase = "resource-development"
| comp count() as sessions, min(_time) as first_seen by dest_fqdn, source_ip, indicator_confidence
| sort desc sessions
| limit 200
| fields dest_fqdn, source_ip, indicator_confidence, first_seen, sessions

