# TTP-2026-0174 — Compromise Infrastructure — A Dangling-DNS Subdomain Takeover Weaponized as Allowlisted C2
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — Periodic Low-Variance Egress to an Owned Subdomain Whose Resolution Target Left the Estate (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: The beaconing client process on the internal host owns the endpoint chain; it is joined to the ASM inventory finding and to the intel promotion on the shared FQDN, which is the only entity the three planes have in common.
# The behavioural half of the claim, and the half that cannot be replaced by any reputation lookup. Internal hosts hold a steady, low-jitter session cadence to a name inside the customer's own namespace whose resolution target is outside their address space. Beaconing alone would be indistinguishable from an internal service the analyst has not heard of — the name looks like theirs, because it is theirs — which is exactly why the resolution-target condition is part of the detection rather than context beside it.

dataset = panw_ngfw_traffic_raw
| filter cortexsim_run_tag = "TIM008"
| filter app in ("ssl", "web-browsing") and dest_fqdn contains "corp-demo.example"
| comp count() as sessions, count_distinct(source_ip) as internal_hosts, avg(bytes_sent) as avg_sent, count_distinct(bytes_sent) as size_variants by dest_fqdn, dest_ip
| filter sessions >= 10 and size_variants <= 3
| sort desc sessions
| fields dest_fqdn, dest_ip, internal_hosts, sessions, avg_sent, size_variants

## VALIDATION — Owned Subdomain Resolving to an Unclaimed Third-Party Provider Endpoint
# purpose: validation
# dataset: asm_findings

dataset = asm_findings
| filter _time > to_timestamp(current_time() - 86400)
| filter cortexsim_run_tag = "TIM008"
| filter finding_type = "dangling_dns_record" and resolution_target_claimed = false
| comp count() as findings by rrname, rrtype, resolution_target, owning_zone
| filter findings >= 1
| sort desc findings
| fields rrname, rrtype, resolution_target, owning_zone, findings

## VALIDATION — Negative Control — Reputation, Category, Domain Age and Feed Match All Pass the Takeover Host
# purpose: validation
# dataset: pan_dns

dataset = pan_dns
| filter _time > to_timestamp(current_time() - 7200)
| filter cortexsim_run_tag = "TIM008"
| filter domain_reputation = "clean" and newly_registered_domain = false and threat_feed_match = false
| comp count() as benign_verdicts by fqdn, url_category, parent_domain_age_days
| filter benign_verdicts >= 1
| fields fqdn, url_category, parent_domain_age_days, benign_verdicts

## VALIDATION — Locally-Minted Indicator Promoted to the Enforcement List Within the Push Budget
# purpose: validation
# dataset: threat_intel

dataset = threat_intel
| filter _time > to_timestamp(current_time() - 7200)
| filter cortexsim_run_tag = "TIM008"
| filter indicator_source = "local-asm-ndr-correlation" and enforcement_state = "blocked"
| alter push_seconds = timestamp_diff(enforcement_time, indicator_minted_time, "SECOND")
| comp min(push_seconds) as fastest_push, max(push_seconds) as slowest_push, count() as promotions by indicator_value, enforcement_list
| sort desc promotions
| fields indicator_value, enforcement_list, promotions, fastest_push, slowest_push

## VALIDATION — Exposure Queue Re-Ranks the Dangling Record Above Higher-Severity Unexploited Findings
# purpose: validation
# dataset: asm_findings

dataset = asm_findings
| filter _time > to_timestamp(current_time() - 86400)
| filter cortexsim_run_tag = "TIM008"
| comp min(queue_rank) as best_rank, max(base_severity_score) as base_severity, count() as findings by finding_type, active_exploitation_intel
| sort desc findings
| fields finding_type, active_exploitation_intel, base_severity, best_rank, findings

## VALIDATION — Estate-Wide Dangling Resource Records Pointing at Unclaimed Provider Endpoints
# purpose: hunt
# dataset: asm_findings

dataset = asm_findings
| filter _time > to_timestamp(current_time() - 604800)
| filter finding_type = "dangling_dns_record"
| comp count() as records, count_distinct(resolution_target) as targets by owning_zone, rrtype, resolution_target_claimed
| sort desc records
| limit 200
| fields owning_zone, rrtype, resolution_target_claimed, targets, records

