# TTP-2026-0133 — ROADtools/roadtx Entra Token Abuse — Rogue Device Registration to PRT Theft to Bulk Graph Enumeration (Identity-Owned Causality Chain)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — ITDR-014 PRT-Backed Silent Token Minting With MFA Satisfied By Refresh Token
# severity: high
# Deterministic Entra sign-in catch: a token acquisition where the incoming token type is a Primary Refresh Token and MFA is satisfied by a claim already carried in the token (no interactive challenge), originating from the rogue device registered seconds earlier. This is the MFA-bypass signature of the ROADtools chain — a PRT minted on a freshly-registered device silently issuing fresh access tokens — complementing the behavioral ABIOCs with an evidence-grade rule keyed to the PRT token type and the satisfied-by-token MFA result.

dataset = msft_azure_ad_signin
| filter incoming_token_type = "primaryRefreshToken"
| filter authentication_requirement = "multiFactorAuthentication" and mfa_detail_auth_method = "PreviouslySatisfied"
| filter is_interactive = false
| comp count() as prt_silent_tokens by user_principal_name, device_detail_device_id, ip_address
| filter prt_silent_tokens >= 1
| fields user_principal_name, device_detail_device_id, ip_address, prt_silent_tokens

## ABIOC — ITDR-014 Programmatic Entra Sign-In From Rogue roadtx Automation User-Agent (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-identity sign-in baseline (interactive/browser only) -> the same user_principal_name produces a non-interactive device-code/refresh-token sign-in from a Python/roadtools user-agent; anchors the chain root to that user_principal_name.
# An identity whose learned Cortex sign-in profile is interactive (browser) only produces a non-interactive, scripted Entra sign-in whose user-agent is a Python HTTP stack / roadtools rather than a browser. The ABIOC anchors the deviation to the per-identity sign-in baseline rather than to the user-agent string alone — roadtx blends into legitimate API traffic, so the catch is WHO is suddenly authenticating programmatically. This is the opening move of the ROADtools chain and the root of the causality graph.

dataset = msft_azure_ad_signin
| filter is_interactive = false
| filter user_agent contains "python-requests" or user_agent contains "roadtools" or client_app_used = "Mobile Apps and Desktop clients"
| filter authentication_protocol in ("deviceCode", "refreshToken", "ropc")
| comp count() as programmatic_signins by user_principal_name, ip_address, user_agent, authentication_protocol
| filter programmatic_signins >= 1
| fields user_principal_name, ip_address, user_agent, authentication_protocol, programmatic_signins

## ABIOC — ITDR-014 Rogue Device Registration Burst Following First Programmatic Sign-In (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Programmatic sign-in (same user_principal_name) -> Device Registration Service 'Add device' within minutes; the minted rogue device_id is the shared entity that links this registration to every subsequent PRT-backed token.
# Within minutes of its first programmatic sign-in the same identity registers a device against the Azure Device Registration Service (Azure AD audit 'Add device' / 'Register device'), the synthetic roadtx device presenting OS build 10.0.19041.928 and a DESKTOP-<8 digits> display name. The ABIOC fires on the sign-in -> device-registration LINEAGE for an identity whose baseline never registers devices — a genuine device join is performed once by a real endpoint, not seconds after a scripted sign-in — anchoring the registration to the same user_principal_name as the programmatic sign-in and emitting the rogue device_id that owns the rest of the chain.

dataset = msft_o365_audit
| filter workload = "AzureActiveDirectory"
| filter operation in ("Add device", "Register device", "Add registered owner to device")
| filter device_os_version = "10.0.19041.928" or device_display_name contains "DESKTOP-"
| comp count() as device_registrations, values(target_device_id) as rogue_device_ids by user_principal_name, client_ip
| filter device_registrations >= 1
| fields user_principal_name, client_ip, rogue_device_ids, device_registrations

## ABIOC — ITDR-014 roadrecon Graph Enumeration Process Descends From roadtx Causality Owner (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: roadtx (Causality Group Owner) -> roadrecon/python enumeration process (action_process) under the same causality_actor_process_instance_id; the process_lineage edge that stitches the endpoint tradecraft to the roadtx-owned cloud-token abuse.
# Endpoint process-lineage catch keyed to XDR causality: a roadrecon / python enumeration process is started whose Causality Group Owner (causality_actor_process_image_name) is roadtx. The ABIOC anchors on the roadtx CGO and the causality_actor_process_instance_id rather than on the child image name alone — python is ubiquitous, so the signal is that THIS python descends from the roadtx token-theft process that owns the whole chain. This is the process_lineage spine that ties the endpoint tradecraft to the cloud-identity abuse.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter causality_actor_process_image_name = "roadtx"
| filter action_process_image_name in ("python3", "python", "roadrecon")
| filter action_process_image_command_line contains "roadrecon" or action_process_image_command_line contains "graph.microsoft.com"
| comp count() as enum_process_starts by agent_hostname, causality_actor_process_instance_id, causality_actor_process_image_name, actor_effective_username
| filter enum_process_starts >= 1
| fields agent_hostname, causality_actor_process_instance_id, causality_actor_process_image_name, actor_effective_username, enum_process_starts

## ABIOC — ITDR-014 Bulk Microsoft Graph Directory Enumeration Burst From Rogue Device Identity (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Rogue device identity (device_detail_device_id from the DRS registration) -> a >100 calls/hour burst across >=3 distinct directory-read Graph endpoints; the enumeration tail of the chain, bound back to the same rogue device that minted the PRT.
# The PRT-backed access tokens drive roadrecon to bulk-read the directory: a burst of repetitive Microsoft Graph calls to /users, /groups, /devices, /servicePrincipals and /applications — well above any interactive-admin rate — bound to the rogue device identity. The ABIOC anchors the volume/endpoint-mix deviation to the per-identity Graph-usage baseline (an interactive user never enumerates the whole directory in an hour), surfacing the Discovery stage as the tail of the identity-owned chain.

dataset = msft_o365_audit
| filter workload = "MicrosoftGraphActivityLogs"
| filter request_uri contains "/users" or request_uri contains "/groups" or request_uri contains "/devices" or request_uri contains "/servicePrincipals" or request_uri contains "/applications"
| comp count() as graph_reads, count_distinct(request_uri) as distinct_endpoints by user_principal_name, device_detail_device_id
| filter graph_reads >= 100 and distinct_endpoints >= 3
| fields user_principal_name, device_detail_device_id, graph_reads, distinct_endpoints

## VALIDATION — ITDR-014 Validate Rogue Device Registration By Programmatically-Authenticated Identity
# purpose: validation
# dataset: msft_o365_audit

dataset = msft_o365_audit
| filter _time > to_timestamp(current_time() - 900)
| filter workload = "AzureActiveDirectory"
| filter operation in ("Add device", "Register device")
| filter device_os_version = "10.0.19041.928" or device_display_name contains "DESKTOP-"
| comp count() as registrations by user_principal_name, device_display_name
| filter registrations >= 1
| fields user_principal_name, device_display_name, registrations

## VALIDATION — ITDR-014 Hunt roadtx PRT Reuse To Graph-Enumeration Identity Chain
# purpose: hunt
# dataset: msft_azure_ad_signin

dataset = msft_azure_ad_signin
| filter _time > to_timestamp(current_time() - 3600)
| filter incoming_token_type = "primaryRefreshToken"
| filter is_interactive = false
| comp count() as prt_token_events by user_principal_name, device_detail_device_id
| filter prt_token_events >= 1
| fields user_principal_name, device_detail_device_id, prt_token_events

