# TTP-2026-0111 — Post-Consent OAuth Token Abuse — Salesforce Bulk API Mass Export with Query-Job Deletion (Bling Libra)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — Post-Consent OAuth Token High-Volume Bulk API Export Deviating from Integration Baseline (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned integration-identity Bulk API baseline (low row volume, narrow object set, scheduled cadence, stable user-agent) -> trusted OAuth token reused -> high-volume multi-object export whose volume/diversity/user-agent diverge from the baseline, anchored to the originating Connected App + integration user.
# A Connected App integration identity whose learned Cortex baseline is low-volume, narrow-object, scheduled Bulk API activity suddenly drives high-volume query jobs across Account/Contact/Case/Opportunity from an automation user-agent. No consent, MFA, or login event exists to alert on; the ABIOC anchors the deviation (export volume + object diversity + user-agent) to the integration identity's learned baseline rather than to any known-bad object or SOQL string, catching post-consent token abuse a static rule would miss.

dataset = cloud_audit_logs
| filter cloud_service = "salesforce" and event_type = "BulkApi" and api_type = "Bulk"
| filter operation in ("query", "queryAll")
| filter object_name in ("Account", "Contact", "Case", "Opportunity")
| comp sum(rows_processed) as run_rows, count_distinct(object_name) as run_objects by connected_app, integration_user, user_agent
| join type = inner (dataset = cloud_audit_logs | filter cloud_service = "salesforce" and event_type = "BulkApi" and api_type = "Bulk" | filter operation in ("query", "queryAll") and _time < to_timestamp(current_time() - 3600) | comp avg(rows_processed) as baseline_avg_rows, max(rows_processed) as baseline_max_rows, count_distinct(object_name) as baseline_objects by connected_app) as base connected_app = base.connected_app
| filter run_rows >= (base.baseline_max_rows * 5) and run_objects > base.baseline_objects
| sort desc run_rows
| fields connected_app, integration_user, user_agent, run_rows, run_objects, base.baseline_max_rows, base.baseline_objects

## ABIOC — Export-Then-Erase Bulk API Query Job Deletion by Exfiltration Token (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: High-volume Bulk API query on job_id N by the integration token -> deleteJob targeting that same job_id N by the same token, delete-after-query within a 30m window, a query-then-delete sequence outside this identity's learned delete behaviour, anchored to the mass-export event chain.
# The same integration identity that just ran a high-volume Bulk API query job then issues deleteJob on that SAME job_id within the same short window — a query-then-erase sequence keyed on job linkage and ordering (delete after query), not a bucketless co-occurrence. Deleting completed Bulk jobs is normal housekeeping for some ETL/backup integrations, so this does not fire on job deletion alone; it fires when a large export and the deletion of that same job happen in-window for an identity whose learned baseline is to leave its query jobs in place, anchored to the mass-export causality chain.

dataset = cloud_audit_logs
| filter cloud_service = "salesforce" and api_type = "Bulk"
| filter operation in ("query", "queryAll", "deleteJob")
| bin _time span = 30m
| comp count_distinct(operation) as op_kinds, sum(rows_processed) as exported_rows, min(if(operation in ("query", "queryAll"), _time, null)) as first_query_time, max(if(operation = "deleteJob", _time, null)) as last_delete_time by _time, connected_app, integration_user, user_agent, job_id
| filter op_kinds >= 2 and exported_rows >= 50000 and last_delete_time > first_query_time
| sort desc exported_rows
| fields connected_app, integration_user, user_agent, job_id, exported_rows, first_query_time, last_delete_time

## VALIDATION — Salesforce Integration Identity Bulk API Baseline Learned
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 86400)
| filter cloud_service = "salesforce" and api_type = "Bulk"
| filter operation in ("query", "queryAll")
| comp sum(rows_processed) as baseline_rows, count_distinct(object_name) as baseline_objects by connected_app, integration_user
| filter baseline_rows >= 0
| fields connected_app, integration_user, baseline_rows, baseline_objects

## VALIDATION — Salesforce Bulk API Mass Export with aiohttp Exfil User-Agent
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 3600)
| filter cloud_service = "salesforce" and api_type = "Bulk" and operation in ("query", "queryAll")
| filter user_agent = "Python/3.11 aiohttp/3.12.15"
| filter object_name in ("Account", "Contact", "Case", "Opportunity")
| comp sum(rows_processed) as exported_rows, count() as query_jobs by integration_user, connected_app, src_ip
| filter exported_rows >= 1
| sort desc exported_rows
| fields integration_user, connected_app, src_ip, exported_rows, query_jobs

## VALIDATION — Salesforce Bulk API Query-Job Deletion Anti-Forensics Hunt
# purpose: hunt
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 86400)
| filter cloud_service = "salesforce" and api_type = "Bulk" and operation = "deleteJob"
| comp count() as deleted_jobs by integration_user, connected_app, user_agent
| filter deleted_jobs >= 1
| sort desc deleted_jobs
| fields integration_user, connected_app, user_agent, deleted_jobs

