# TTP-2026-0035 — Linux Defense Evasion — Log Tampering, Timestomping, Masquerading (T1070.002)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — EDR-004 Bash History Clearing And HISTFILE Manipulation
# severity: high
# Bash history clearing — HISTFILE manipulation and history -c execution detected. A shell unsets/redirects HISTFILE or truncates .bash_history.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter action_process_image_command_line contains_any ("history -c", "HISTFILE=/dev/null", "unset HISTFILE", "> ~/.bash_history", "rm -f ~/.bash_history", "HISTSIZE=0")

## BIOC — EDR-004 System Log Access Or Truncation
# severity: high
# System log file access and truncation attempt — log tampering to hide intrusion evidence. A non-syslog process reads, copies or truncates auth.log/syslog.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter action_file_path contains_any ("/var/log/auth.log", "/var/log/syslog", "/var/log/secure", "/var/log/messages", "/var/log/wtmp", "/var/log/btmp")
| filter actor_process_image_name not in ("rsyslogd", "syslog-ng", "systemd-journald", "logrotate", "auditd")

## BIOC — EDR-004 File Timestomp Via Touch
# severity: high
# File timestamp modification via touch -t — timestomping to evade forensic analysis. touch is invoked with -t (explicit time) or -r (reference file).

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name = "touch"
| filter action_process_image_command_line contains_any (" -t ", " -r ", " -d ", "--date", "--reference")

## BIOC — EDR-004 Binary Masquerade As Kernel Thread
# severity: high
# Binary copied and renamed to match kernel thread name — process masquerading as kworker. A shell/binary is copied to a [kworker..]/systemd-* style name.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("cp", "mv", "install", "ln")
| filter action_process_image_command_line contains_any ("[kworker", "[kthreadd]", "systemd-journald", "[migration", "[ksoftirqd")

## BIOC — EDR-004 Security Product Enumeration
# severity: medium
# Security product enumeration — process search for EDR/AV agent names indicates evasion preparation. The process table is grepped for common EDR/AV vendor strings.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("grep", "egrep", "pgrep", "ps")
| filter action_process_image_command_line contains_any ("falcon", "crowdstrike", "crowd", "cortex", "traps", "sentinel", "cylance", "carbon", "defender", "clamav")

## VALIDATION — EDR-004 Analytics History Evasion Sequence
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_command_line contains_any ("history -c", "HISTFILE", ".bash_history")
| fields _time, agent_hostname, actor_effective_username, action_process_image_command_line

## VALIDATION — EDR-004 Analytics Auth Log Access Non-Syslog Process
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.FILE and action_file_path contains_any ("/var/log/auth.log", "/var/log/syslog")
| filter actor_process_image_name not in ("rsyslogd", "systemd-journald", "logrotate")
| fields _time, agent_hostname, actor_process_image_name, action_file_path

## VALIDATION — EDR-004 Analytics Timestomp Reference File
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name = "touch"
| filter action_process_image_command_line contains_any (" -r ", " -t ")
| fields _time, agent_hostname, action_process_image_command_line

## VALIDATION — EDR-004 Analytics Shell Binary Copied To System Name
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("cp", "mv")
| filter action_process_image_command_line contains_any ("/bin/sh", "/bin/bash") and action_process_image_command_line contains_any ("kworker", "systemd-", "/tmp/")
| fields _time, agent_hostname, action_process_image_command_line

## VALIDATION — EDR-004 Analytics Security Tool Discovery Via Process Listing
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("grep", "egrep", "pgrep")
| filter action_process_image_command_line contains_any ("falcon", "crowd", "cortex", "sentinel", "cylance", "carbon")
| fields _time, agent_hostname, actor_effective_username, action_process_image_command_line

