# TTP-2026-0082 — Container-Native Ransomware via Host Filesystem Escape — Cortex Cloud CDR (T1486 / T1611)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — CDR-010 Container chroot to Host Filesystem Mount
# severity: critical
# A process inside a container invokes chroot against a host-root mount path immediately after reading /proc/self/mountinfo. This is the container-to-host escape primitive used by the ransomware-in-container payload (T1611 Escape to Host) before it detonates an encryptor on the node.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_container_info != null
| filter action_process_image_name = "chroot" or action_process_image_command_line contains "chroot"
| filter action_process_image_command_line contains "/host" or action_process_image_command_line contains "mountinfo"
| comp count() as escape_events by agent_hostname, actor_process_image_name
| filter escape_events >= 1
| fields agent_hostname, actor_process_image_name, escape_events

## BIOC — CDR-010 Host Filesystem Escape via Mountinfo Read
# severity: high
# A containerized process reads /proc/self/mountinfo to enumerate the host-root mount, the reconnaissance step that anchors the chroot escape causality chain. Pairing the mountinfo read with a subsequent privileged action inside the same container distinguishes a real escape attempt from benign mount introspection.

dataset = xdr_data
| filter event_type = ENUM.FILE and event_sub_type = ENUM.FILE_OPEN
| filter actor_container_info != null
| filter action_file_path in ("/proc/self/mountinfo", "/proc/1/mountinfo")
| filter actor_process_image_name in ("sh", "bash", "grep", "awk")
| comp count() as mountinfo_reads by agent_hostname, actor_process_image_name
| filter mountinfo_reads >= 1
| fields agent_hostname, actor_process_image_name, mountinfo_reads

## VALIDATION — CDR-010 Container Workload Projection
# purpose: hunt
# dataset: xdr_data

dataset = xdr_data
| fields actor_container_info as container_info
| filter container_info != null
| alter pod_namespace = json_extract_scalar(container_info, "$.pod_namespace")
| alter pod_name = json_extract_scalar(container_info, "$.pod_name")
| alter image_name = json_extract_scalar(container_info, "$.image_name")
| alter image_id = json_extract_scalar(container_info, "$.image_id")
| alter container_id = json_extract_scalar(container_info, "$.id")
| alter privileged = json_extract_scalar(container_info, "$.privileged")
| filter actor_process_image_name in ("chroot", "openssl", "sh", "bash")

## VALIDATION — CDR-010 In-Container Mass File Encryption Rate
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 600)
| filter event_type = ENUM.FILE and event_sub_type in (ENUM.FILE_WRITE, ENUM.FILE_RENAME, ENUM.FILE_CREATE_NEW)
| filter actor_container_info != null
| filter action_file_path contains ".locked" or actor_process_image_name in ("openssl", "gpg", "ccrypt")
| comp count() as modified_files by agent_hostname, actor_process_image_name
| filter modified_files >= 10
| sort desc modified_files
| fields agent_hostname, actor_process_image_name, modified_files

