# TTP-2026-0049 — APT29 Hybrid Cloud Credential Theft → Cloud Pivot → S3 Exfil Stitch (T1552.001)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — MP-004 Recursive AWS Key Pattern Grep From Service Account
# severity: high
# XDR — recursive credential-pattern grep from non-interactive service account. The endpoint credential-access leg: www-data greps the filesystem for AWS key material.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("grep", "egrep", "rg", "find")
| filter action_process_image_command_line contains_any ("AKIA", "aws_secret_access_key", ".aws/credentials")
| filter actor_effective_username in ("www-data", "nobody", "apache", "nginx")

## BIOC — MP-004 AWS CLI Invoked By www-data With Inline Access Key Env
# severity: high
# XDR — aws cli invoked by www-data with inline access-key env vars. The hybrid pivot: the endpoint process that turns discovered keys into cloud API calls — the 'who/where' the cloud_audit leg cannot see.

preset = xdr_data
| filter event_type = ENUM.PROCESS
| filter event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name = "aws"
| filter actor_effective_username in ("www-data", "nobody", "apache", "nginx")
| filter action_process_image_command_line contains_any ("sts", "get-caller-identity", "ec2", "s3", "iam")

## BIOC — MP-004 Cloud Multi Service Describe List Burst From Single Principal
# severity: high
# CDR — multi-service describe/list burst (EC2+IAM+S3) from single principal in <30s. Cloud discovery: one principal touches three services in a tight window.

dataset = cloud_audit
| filter cloud_provider = "AWS"
| filter event_name in ("DescribeInstances", "ListUsers", "ListBuckets", "ListAccessKeys", "GetAccountSummary")
| comp count_distinct(event_source) as service_count, count() as call_count by user_identity_access_key_id, bin(_time, 30s) as window
| filter service_count >= 3

## BIOC — MP-004 GetBucketAcl And ListObjects On Sensitive Tagged Bucket
# severity: high
# CDR — GetBucketAcl + ListObjects on sensitivity-tagged bucket by unauthorized principal. Cloud collection: targeted access to the sensitive bucket.

dataset = cloud_audit
| filter cloud_provider = "AWS" and event_source = "s3.amazonaws.com"
| filter event_name in ("GetBucketAcl", "ListObjects", "ListObjectsV2", "GetObject")
| filter request_parameters_bucket_name = "cortexsim-sensitive-demo"
| comp count() as access_count by user_identity_access_key_id, request_parameters_bucket_name

## BIOC — MP-004 S3 CopyObject To Non Owned Destination Bucket
# severity: critical
# CDR — S3 CopyObject to non-owned destination account/bucket. Cloud exfil: data copied from the sensitive source to the attacker-owned bucket.

dataset = cloud_audit
| filter cloud_provider = "AWS" and event_source = "s3.amazonaws.com"
| filter event_name in ("CopyObject", "PutObject")
| filter request_parameters_bucket_name = "cortexsim-attacker-drop"
| comp count() as copy_count by user_identity_access_key_id, request_parameters_bucket_name

## VALIDATION — MP-004 Service Account Traversing Home And Root Dirs
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("grep", "find", "egrep", "rg")
| filter action_process_image_command_line contains_any ("/home", "/root", "/opt", "/var/www")
| filter actor_effective_username != "root"
| fields _time, agent_hostname, actor_effective_username, action_process_image_command_line

## VALIDATION — MP-004 CloudTrail GetCallerIdentity From Unenrolled Source IP
# purpose: validation
# dataset: cloud_audit

dataset = cloud_audit
| filter _time > to_timestamp(current_time() - 1800)
| filter cloud_provider = "AWS" and event_source = "sts.amazonaws.com" and event_name = "GetCallerIdentity"
| fields _time, user_identity_access_key_id, user_identity_arn, source_ip, user_agent

## VALIDATION — MP-004 Stitch Endpoint Process With Cloud Audit By Principal
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter (event_type = ENUM.PROCESS and actor_process_image_name = "aws") or (_product = "cloud_audit" and event_name = "GetCallerIdentity")
| comp count_distinct(_product) as plane_count, count_distinct(incident_id) as incident_count by actor_effective_username
| filter plane_count >= 2 and incident_count = 1
| fields actor_effective_username, plane_count, incident_count

## VALIDATION — MP-004 UEBA First Time Broad Cloud Discovery Pattern
# purpose: validation
# dataset: cloud_audit

dataset = cloud_audit
| filter _time > to_timestamp(current_time() - 1800)
| filter cloud_provider = "AWS"
| filter event_name contains_any ("Describe", "List", "Get")
| comp count_distinct(event_source) as services_touched, count() as total_calls by user_identity_access_key_id, bin(_time, 5m) as window
| filter services_touched >= 3
| fields window, user_identity_access_key_id, services_touched, total_calls

## VALIDATION — MP-004 Cloud Data Egress Volume Anomaly From Tagged Source
# purpose: validation
# dataset: cloud_audit

dataset = cloud_audit
| filter _time > to_timestamp(current_time() - 1800)
| filter cloud_provider = "AWS" and event_source = "s3.amazonaws.com"
| filter event_name in ("CopyObject", "GetObject", "PutObject")
| filter request_parameters_bucket_name in ("cortexsim-sensitive-demo", "cortexsim-attacker-drop")
| comp count() as object_ops by user_identity_access_key_id, request_parameters_bucket_name
| fields user_identity_access_key_id, request_parameters_bucket_name, object_ops

## VALIDATION — MP-004 Stitch Full Kill Chain Cred Dump To Cloud Exfil
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter (event_type = ENUM.PROCESS and actor_process_image_name in ("grep", "aws")) or (_product = "cloud_audit" and event_name in ("GetCallerIdentity", "DescribeInstances", "ListObjects", "CopyObject"))
| comp count_distinct(_product) as plane_count, count_distinct(incident_id) as incident_count, count_distinct(event_name) as stage_count by actor_effective_username
| filter plane_count >= 2 and incident_count = 1
| fields actor_effective_username, plane_count, incident_count, stage_count

