# TTP-2026-0020 — Prisma Browser — Cross-Origin SaaS Copy-Paste DLP (T1567)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — Prisma Browser — cross-origin paste from sanctioned CRM into personal webmail (DLP rule)
# severity: high
# Prisma Browser — cross-origin paste from sanctioned CRM into personal webmail (DLP rule). A paste whose clipboard-source origin is a sanctioned CRM lands in a personal webmail destination origin.

dataset = prisma_browser_events
| filter action = "paste"
| filter clipboard_origin in ("crm.cortexsim-test.invalid", "crm.corp.example.com", "salesforce.com")
| filter origin in ("mail.cortexsim-test.invalid", "mail.google.com", "outlook.live.com")
| filter clipboard_origin != origin

## VALIDATION — Pre-flight: plugin metadata visible to operator
# purpose: validation
# dataset: prisma_browser_events

dataset = prisma_browser_events
| filter _time > to_timestamp(current_time() - 1800)
| filter campaign_id = "BC-BROWSER-004"
| filter action in ("navigate", "copy", "paste")
| fields _time, campaign_id, action, origin, clipboard_origin, url
| sort asc _time

## VALIDATION — Prisma Browser — clipboard origin tag mismatch with paste destination origin
# purpose: validation
# dataset: prisma_browser_events

dataset = prisma_browser_events
| filter _time > to_timestamp(current_time() - 1800)
| filter action = "paste"
| filter clipboard_origin != null and clipboard_origin != origin
| fields _time, user, clipboard_origin, origin, url, clipboard_payload_hash, data_classification
| sort desc _time

## VALIDATION — XSIAM stitching — copy + paste correlated by clipboard payload hash
# purpose: validation
# dataset: prisma_browser_events

dataset = prisma_browser_events
| filter _time > to_timestamp(current_time() - 1800)
| filter action in ("copy", "paste")
| filter clipboard_payload_hash != null
| comp count_distinct(action) as action_count, values(origin) as origins by user, clipboard_payload_hash
| filter action_count >= 2
| fields user, clipboard_payload_hash, action_count, origins

## VALIDATION — XSIAM — stitched cross-origin DLP incident with both origins on the timeline
# purpose: validation
# dataset: prisma_browser_events

dataset = prisma_browser_events
| filter _time > to_timestamp(current_time() - 1800)
| filter action in ("copy", "paste")
| filter clipboard_payload_hash != null
| comp min(_time) as first_seen, max(_time) as last_seen, values(origin) as origins, values(action) as actions by user, clipboard_payload_hash
| filter array_length(origins) >= 2
| fields user, clipboard_payload_hash, first_seen, last_seen, origins, actions

