# TTP-2026-0142 — Ransomware Precursor Auto-Containment — BlackSuit DCSync-to-ESXi Kill Chain Fires XSOAR Auto-Containment (T1003.006 / T1053.005 / T1486)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — BlackSuit VPN Valid-Account Anomalous GlobalProtect Sign-In
# severity: medium
# The vished VPN credential surfaces as an anomalous but authenticated GlobalProtect gateway sign-in — a legitimate account from an unfamiliar source region or a first-seen device. No known-bad indicator; the anomaly against the account's learned sign-in geography/device is the signal (T1078 initial access).

dataset = panw_ngfw_globalprotect_raw
| filter event_type = "gateway-auth" and auth_result = "success"
| filter source_region_is_approved = false or device_is_first_seen = true
| comp count() as logins by source_user, source_ip, source_region
| filter logins >= 1
| fields source_user, source_ip, source_region, logins

## BIOC — DCSync Replication Request from a Non-Domain-Controller Account
# severity: critical
# A DRSUAPI DsGetNCChanges directory-replication request (Windows event 4662 carrying the DS-Replication-Get-Changes control-access right) originates from an account/host that is not a domain controller — the canonical DCSync signature Ignoble Scorpius used to extract NTDS.dit hashes including the stolen service account (T1003.006).

dataset = msft_windows_security
| filter event_id = 4662
| filter object_properties contains "DS-Replication-Get-Changes" or object_properties contains "1131f6aa-9c07-11d1-f79f-00c04fc2dcd2"
| filter src_host_is_domain_controller = false and subject_account not in ("SYSTEM", "LOCAL SERVICE")
| comp count() as replication_requests by subject_account, src_host
| filter replication_requests >= 1
| fields subject_account, src_host, replication_requests

## BIOC — AnyDesk RAT Registered as a Scheduled Task for Persistence on a Domain Controller
# severity: high
# AnyDesk or a custom RAT is registered as a scheduled task (schtasks.exe /create) on a domain controller so it survives reboots — matching the source's 'configured as a scheduled task to survive reboots.' A DC is never a legitimate place for a remote-access-tool scheduled task, so the host role plus the schtasks /create + AnyDesk command line is the signal (T1053.005).

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_name = "schtasks.exe" and action_process_command_line contains "/create"
| filter action_process_command_line contains "AnyDesk"
| filter agent_host_is_domain_controller = true
| comp count() as persistence_events by agent_hostname, actor_effective_username, action_process_command_line
| filter persistence_events >= 1
| fields agent_hostname, actor_effective_username, action_process_command_line, persistence_events

## ABIOC — DCSync-to-Persistence Behavioral Chain on a Domain Controller (behavioral-ML, causality-anchored)
# severity: critical
# behavioral_profile: machine-learning
# causality_anchor: Domain-controller identity performing a DCSync/DsGetNCChanges replication read -> the SAME identity subsequently writing an AnyDesk/RAT scheduled-task persistence entry on the same DC within the correlation window (replication strictly precedes persistence), anchored to the stolen service account's causality chain.
# Cortex's behavioral-ML fuses two events that individually look administrative — a directory-replication (DCSync) read and a subsequent scheduled-task persistence write — into one causally-linked, TIME-ORDERED chain on the SAME domain controller under the SAME identity within the correlation window. The replication read MUST precede the persistence write; neither event alone fires. This is the junction the auto-containment playbook fires on: no single event is known-bad, but the DCSync-then-persist sequence on a DC is the ransomware precursor's behavioral fingerprint (T1003.006 -> T1053.005).

dataset = xdr_data
| filter agent_host_is_domain_controller = true and event_type = ENUM.DIRECTORY_SERVICE and action_directory_service_operation = "replication"
| comp min(_time) as dcsync_t0 by agent_hostname, actor_effective_username
| join type = inner (
    dataset = xdr_data
    | filter agent_host_is_domain_controller = true and event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
    | filter action_process_image_name = "schtasks.exe" and action_process_command_line contains "/create" and action_process_command_line contains "AnyDesk"
    | comp min(_time) as persist_t1 by agent_hostname, actor_effective_username
  ) as persist persist.agent_hostname = agent_hostname and persist.actor_effective_username = actor_effective_username
| alter chain_seconds = timestamp_diff(persist_t1, dcsync_t0, "SECOND")
| filter chain_seconds >= 0 and chain_seconds <= 600
| fields agent_hostname, actor_effective_username, dcsync_t0, persist_t1, chain_seconds

## VALIDATION — RDP and SMBExec Lateral Movement from the Stolen Service Account
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_name in ("mstsc.exe", "psexesvc.exe", "smbexec.py", "wmiexec.py", "PSEXESVC.exe")
| filter actor_effective_username = "svc-backup"
| comp count_distinct(agent_hostname) as hosts_touched by actor_effective_username, action_process_image_name
| filter hosts_touched >= 2
| fields actor_effective_username, action_process_image_name, hosts_touched

## VALIDATION — Renamed rclone Bulk Egress from the Domain-Controller Segment
# purpose: validation
# dataset: pan_ngfw_traffic

dataset = pan_ngfw_traffic
| filter app in ("ssl", "webdav", "rclone") and dest_is_internal = false
| comp sum(bytes_sent) as egress_bytes, count() as sessions by source_ip, dest_ip, app
| filter egress_bytes > 10000000000
| sort desc egress_bytes
| fields source_ip, dest_ip, app, egress_bytes, sessions

## VALIDATION — XSOAR Response and Remediation Playbook Fired and Closed the Precursor Incident
# purpose: metric
# dataset: xsiam_incidents

dataset = xsiam_incidents
| filter correlation_rule_id = "CR-MP-0020"
| filter playbook_name contains "Ransomware-Precursor-AutoContain" and playbook_status = "completed"
| filter automation_actions contains "isolate-endpoint" and automation_actions contains "disable-account"
| comp count() as remediations, min(time_to_contain_seconds) as fastest_mttc by incident_id
| filter remediations >= 1
| fields incident_id, remediations, fastest_mttc

