# TTP-2026-0037 — ITDR — Impossible Travel (Okta + Entra sign-ins from US-West and APAC-East)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — ITDR-001 Pre-Flight idp_signin_emulator Metadata Visible
# severity: informational
# Pre-flight: idp_signin_emulator metadata visible to operator. Confirms the EAL plugin is registered and exposes IdP sign-in targets before any events are emitted, so a null result means a harness fault rather than a detection miss.

dataset = okta_sso
| filter eventType in ("system.api_token.create", "application.lifecycle.activate") or _raw_log contains "idp_signin_emulator"
| comp count() as preflight_events by actor_effective_username
| filter preflight_events >= 0

## VALIDATION — ITDR-001 Impossible Travel Two Distant Geos Within Window
# purpose: validation
# dataset: okta_sso

dataset = okta_sso
| filter _time > to_timestamp(current_time() - 1800)
| filter eventType = "user.session.start" and auth_outcome = "SUCCESS"
| comp count_distinct(src_geo_country) as geo_count, count_distinct(src_ip) as ip_count, earliest(_time) as first_seen, latest(_time) as last_seen, values(src_geo_city) as cities by actor_effective_username
| alter window_minutes = divide(subtract(last_seen, first_seen), 60000000)
| filter geo_count >= 2 and window_minutes <= 300
| fields actor_effective_username, geo_count, ip_count, cities, window_minutes, first_seen, last_seen

## VALIDATION — ITDR-001 NGFW Outbound POST Burst To Identity Collector
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter _time > to_timestamp(current_time() - 1800)
| filter app in ("web-browsing", "ssl") and dst_port = 443
| filter uri_path contains "/idp/events" or url contains "/idp/events"
| comp count() as post_count, sum(bytes_sent) as bytes_out by src_ip, dst_host
| filter post_count >= 1
| fields src_ip, dst_host, post_count, bytes_out

## VALIDATION — ITDR-001 Impossible Travel Microsoft SignInLogs Shape
# purpose: validation
# dataset: msft_azure_ad_signin

dataset = msft_azure_ad_signin
| filter _time > to_timestamp(current_time() - 1800)
| filter auth_outcome = "SUCCESS"
| comp count_distinct(src_geo_country) as geo_count, earliest(_time) as first_seen, latest(_time) as last_seen, values(src_geo_city) as cities by user_name
| alter window_minutes = divide(subtract(last_seen, first_seen), 60000000)
| filter geo_count >= 2 and window_minutes <= 300
| fields user_name, geo_count, cities, window_minutes, first_seen, last_seen

