# TTP-2026-0168 — Intel-to-Enforcement Rollback — A Withdrawn Indicator Must Retract From the EDL and Restore Traffic Unattended
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — SIM-TIM-007 Feed-Matched Control FQDN Session Denied at the Enforcement Point
# severity: medium
# An estate host's session to the feed-matched control FQDN is denied, reset or dropped at the firewall while the indicator is promoted. Keying on the specific control FQDN rather than on a broad 'any EDL-blocked destination' predicate is deliberate: an unqualified rule fires on every legitimate EDL block in the estate and tells the DC nothing about this particular loop. This BIOC establishes the phase-A baseline that the rollback is measured against — without it, the phase-B allow proves nothing.

dataset = panw_ngfw_traffic_raw
| filter dst_fqdn contains "rollback-control."
| filter action in ("deny", "reset-both", "reset-client", "reset-server", "drop")
| comp count() as denied_sessions, earliest(_time) as first_deny, latest(_time) as last_deny by agent_hostname, src_host, dst_fqdn, action
| filter denied_sessions >= 1
| fields agent_hostname, src_host, dst_fqdn, action, denied_sessions, first_deny, last_deny

## VALIDATION — SIM-TIM-007 Control Indicator Promoted to the EDL
# purpose: validation
# dataset: threat_intel

dataset = threat_intel
| filter indicator_type = "DOMAIN"
| filter indicator_value contains "rollback-control."
| filter lifecycle_state = "promoted" and enforcement_target contains "EDL"
| comp count() as promoted_indicators, latest(_time) as promoted_at by indicator_value, lifecycle_state, enforcement_target
| filter promoted_indicators >= 1
| fields indicator_value, lifecycle_state, enforcement_target, promoted_indicators, promoted_at

## VALIDATION — SIM-TIM-007 Phase A Sessions to the Control FQDN Denied While Promoted
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter dst_fqdn contains "rollback-control."
| filter action in ("deny", "reset-both", "reset-client", "reset-server", "drop")
| comp count() as denied_sessions, earliest(_time) as first_deny, latest(_time) as last_deny by dst_fqdn, src_host
| filter denied_sessions >= 1
| fields dst_fqdn, src_host, denied_sessions, first_deny, last_deny

## VALIDATION — SIM-TIM-007 Indicator Withdrawal Recorded in the Intel Audit Trail
# purpose: validation
# dataset: threat_intel

dataset = threat_intel
| filter indicator_value contains "rollback-control."
| filter lifecycle_action in ("withdraw", "retract", "expire", "demote")
| comp count() as withdrawal_events, latest(_time) as withdrawn_at, values(actor) as withdrawn_by by indicator_value, lifecycle_action
| filter withdrawal_events >= 1
| fields indicator_value, lifecycle_action, withdrawal_events, withdrawn_at, withdrawn_by

## VALIDATION — SIM-TIM-007 Phase B Sessions to the Same FQDN Allowed After Withdrawal
# purpose: validation
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter dst_fqdn contains "rollback-control."
| filter action = "allow"
| comp count() as allowed_sessions, earliest(_time) as first_allow, latest(_time) as last_allow by dst_fqdn, src_host
| filter allowed_sessions >= 1
| fields dst_fqdn, src_host, allowed_sessions, first_allow, last_allow

## VALIDATION — SIM-TIM-007 Enforcement Rollback Completeness
# purpose: metric
# dataset: panw_ngfw_traffic_raw

dataset = panw_ngfw_traffic_raw
| filter dst_fqdn contains "rollback-control."
| comp count() as total_sessions, sum(if(action = "allow", 1, 0)) as allowed_sessions, sum(if(action in ("deny", "reset-both", "reset-client", "reset-server", "drop"), 1, 0)) as denied_sessions, earliest(if(action = "allow", _time, null)) as first_allow, latest(if(action in ("deny", "reset-both", "reset-client", "reset-server", "drop"), _time, null)) as last_deny by dst_fqdn
| alter rollback_completeness_pct = multiply(divide(allowed_sessions, total_sessions), 100)
| fields dst_fqdn, total_sessions, denied_sessions, allowed_sessions, rollback_completeness_pct, last_deny, first_allow

