# TTP-2026-0113 — Machine-Tempo Autonomous Agent-Swarm Cloud Attack Chain — Cortex Analytics ABIOC (T1580 / T1552.005 / T1548.005 / T1537)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — Machine-Tempo Multi-Stage Cloud Attack Chain Under a Single Derived Identity (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned per-identity cloud-API baseline (a service account touches a narrow, stable set of operations at human/scheduled cadence) -> IMDS-minted derived identity -> fan-out of distinct control-plane stages at sub-minute inter-stage latency, anchored to the single derived identity threading every stage.
# A newly-observed service-account identity (one with no operation history in the prior 24h — the token minted from the instance metadata service) performs an abnormally broad set of distinct high-risk GCP control-plane operations — infrastructure discovery, IAM enumeration, bucket creation, BigQuery export — within a sub-two-minute window. Known automation principals (terraform / cloudbuild / config-connector / deploymentmanager service accounts, which produce the same broad op-set on every IaC apply) are excluded, and the identity must be first-seen, so a normal Terraform/Config-Connector run does not fire. Every call is individually legitimate; the ABIOC anchors on the cadence-and-breadth deviation under one newly-derived identity, not on any single known-bad API. This is the core 'Zealot' signal: inter-stage latency and stage diversity under an identity that has no baseline history, not a signature.

dataset = cloud_audit_logs
| filter cloud_provider = "gcp"
| filter identity_type = "serviceAccount"
| filter _time > to_timestamp(current_time() - 3600)
| filter identity_name not contains "terraform" and identity_name not contains "cloudbuild" and identity_name not contains "config-connector" and identity_name not contains "deploymentmanager"
| filter operation_name in ("compute.instances.list", "compute.networks.list", "resourcemanager.projects.getIamPolicy", "bigquery.datasets.get", "bigquery.tables.export", "storage.buckets.create", "storage.setIamPermissions")
| comp count_distinct(operation_name) as distinct_stages, count() as api_calls, min(_time) as first_call, max(_time) as last_call by identity_name, caller_ip
| alter chain_span_seconds = timestamp_diff(last_call, first_call, "SECOND")
| filter distinct_stages >= 5 and chain_span_seconds <= 120
| join type=left (dataset = cloud_audit_logs
| filter cloud_provider = "gcp"
| filter identity_type = "serviceAccount"
| filter _time < to_timestamp(current_time() - 86400)
| comp count() as prior_calls by identity_name) as baseline baseline.identity_name = identity_name
| alter prior_calls = coalesce(prior_calls, 0)
| filter prior_calls = 0
| fields identity_name, caller_ip, distinct_stages, api_calls, chain_span_seconds

## ABIOC — Autonomous IAM Self-Escalation via storage.objectAdmin Grant Following IMDS Token Theft (behavioral-ML, causality-anchored)
# severity: critical
# behavioral_profile: machine-learning
# causality_anchor: IMDS-minted service-account identity -> IAM setIamPolicy adding roles/storage.objectAdmin to itself -> immediate export/read of the newly accessible bucket, anchored to the derived identity that first appeared via instance-metadata token use.
# The derived service-account identity grants roles/storage.objectAdmin to ITSELF (setIamPermissions / setIamPolicy where the added member equals the acting identity) — the exact work-around 'Zealot' used to defeat a BigQuery access denial by creating a bucket, self-granting object admin, exporting the table, and reading it back. The `granted_member = identity_name` predicate is the discriminator: a routine IaC-managed objectAdmin grant to a DIFFERENT principal (the normal google_storage_bucket_iam_member case) does not fire — only a true self-grant does. The ABIOC anchors the self-grant to the IMDS-minted identity's causality chain rather than to any single API, catching autonomous privilege escalation that a static rule keyed on a benign setIamPolicy would miss.

dataset = cloud_audit_logs
| filter cloud_provider = "gcp"
| filter identity_type = "serviceAccount"
| filter operation_name in ("storage.setIamPermissions", "resourcemanager.projects.setIamPolicy", "compute.instances.setIamPolicy")
| filter granted_role = "roles/storage.objectAdmin" or policy_delta contains "storage.objectAdmin"
| filter granted_member = identity_name
| comp count() as self_grants, min(_time) as first_grant by identity_name, granted_member, target_resource
| filter self_grants >= 1
| fields identity_name, granted_member, target_resource, self_grants, first_grant

## ABIOC — SSRF-Driven Instance Metadata Token Theft from an Anomalous Workload Process (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned workload-process baseline (the web service never contacts the metadata IP) -> SSRF -> outbound request to 169.254.169.254 from that process, anchored to the workload host+identity so it stitches forward to the cloud-plane fan-out.
# A workload process (node, python3, java, ruby, php-fpm, curl) on the exposed VM reaches the instance metadata service IP (169.254.169.254) for the FIRST time — the host's learned baseline shows no prior IMDS contact in the preceding day, then a sudden reach appears. The novelty gate (prior_imds_requests = 0 from the baseline join) is the discriminator: a GCP workload that routinely mints Application-Default-Credentials tokens has a non-zero IMDS baseline and does NOT fire, so the rule no longer alerts on the normal ADC credential flow — only on a first-ever metadata reach, the endpoint-side tell of the SSRF that 'Zealot' used to steal the attached service-account token. The deviation is anchored to the workload host+identity so the endpoint signal can be stitched to the cloud-plane stages that follow.

dataset = xdr_data
| filter event_type = ENUM.NETWORK
| filter action_remote_ip = "169.254.169.254"
| filter _time > to_timestamp(current_time() - 3600)
| filter actor_process_image_name in ("node", "python3", "java", "ruby", "php-fpm", "curl")
| comp count() as imds_requests_now, min(_time) as first_seen by agent_hostname, actor_effective_username, actor_process_image_name
| join type=left (dataset = xdr_data
| filter event_type = ENUM.NETWORK
| filter action_remote_ip = "169.254.169.254"
| filter _time < to_timestamp(current_time() - 3600)
| comp count() as prior_imds_requests by agent_hostname) as baseline baseline.agent_hostname = agent_hostname
| alter prior_imds_requests = coalesce(prior_imds_requests, 0)
| filter imds_requests_now >= 1 and prior_imds_requests = 0
| fields agent_hostname, actor_effective_username, actor_process_image_name, imds_requests_now, prior_imds_requests, first_seen

## VALIDATION — SIM-MP-009 Derived-Identity Stage Fan-Out in Cloud Audit Logs
# purpose: validation
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 900)
| filter cloud_provider = "gcp"
| filter identity_type = "serviceAccount"
| comp count_distinct(operation_name) as distinct_operations, count() as api_calls by identity_name
| filter distinct_operations >= 3
| sort desc distinct_operations
| fields identity_name, distinct_operations, api_calls

## VALIDATION — SIM-MP-009 BigQuery Export to Newly Created Storage Bucket
# purpose: hunt
# dataset: cloud_audit_logs

dataset = cloud_audit_logs
| filter _time > to_timestamp(current_time() - 900)
| filter cloud_provider = "gcp"
| filter operation_name in ("bigquery.tables.export", "bigquery.jobs.insert", "storage.buckets.create", "storage.objects.create")
| comp count() as export_ops, count_distinct(operation_name) as distinct_ops by identity_name, target_resource
| filter export_ops >= 1
| fields identity_name, target_resource, export_ops, distinct_ops

