# TTP-2026-0045 — Malicious VS Code Extension Reads Credentials On Activation (T1176 / T1195)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## BIOC — KOI-004 VSCode Extension Reads AWS Credentials And SSH Keys In Activate
# severity: critical
# Code scan — extension reads ${HOME}/.aws/credentials and ${HOME}/.ssh/ via fs.readFile in activate(). A VS Code / node child process reads credential and SSH key files during extension activation.

preset = xdr_data
| filter event_type = ENUM.FILE
| filter event_sub_type in (ENUM.FILE_OPEN, ENUM.FILE_READ)
| filter action_file_path contains_any (".aws/credentials", ".ssh/id_rsa")
| filter actor_process_image_name in ("code", "node", "Code", "code-server") or causality_actor_process_image_name in ("code", "node", "Code")

## BIOC — KOI-004 VSCode Extension Activate Beacons Outbound To Non Microsoft Domain
# severity: high
# Code scan — extension activate() opens outbound HTTPS to non-Microsoft domain. The VS Code extension host process opens an outbound connection to a non-Microsoft / non-canonical domain right after activation.

preset = xdr_data
| filter event_type = ENUM.NETWORK
| filter actor_process_image_name in ("code", "node", "Code", "code-server") or causality_actor_process_image_name in ("code", "node", "Code")
| filter dst_action_external_hostname not contains "microsoft.com"
| filter dst_action_external_hostname not contains "visualstudio.com"
| filter dst_action_external_hostname not contains "vscode.dev"
| filter action_external_port in (80, 443)

## VALIDATION — KOI-004 VSCode Extension Manifest Declares Wildcard Activation Events
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter actor_process_image_name in ("jq", "grep", "cat", "cortexcloud", "checkov")
| filter action_process_image_command_line contains "package.json"
| filter action_process_image_command_line contains_any ("activationEvents", "helpful-ai-assistant")
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

## VALIDATION — KOI-004 VSCode Marketplace VSIX Fetch From Non Canonical CDN
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.NETWORK
| filter dst_action_external_hostname contains "cortexsim-canary" or dns_query_name contains "cortexsim-canary"
| filter action_external_url contains "/vsx/" or action_external_url contains ".vsix"
| fields _time, agent_hostname, causality_actor_process_image_name, causality_id, actor_process_image_name, actor_process_instance_id, dst_action_external_hostname, action_external_url

## VALIDATION — KOI-004 Extension Marketplace Risk Unverified Publisher Overbroad Permissions
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_command_line contains "helpful-ai-assistant"
| filter action_process_image_command_line contains_any ("activationEvents", "package.json", "unknown-publisher")
| fields _time, agent_hostname, actor_process_image_name, action_process_image_command_line

## VALIDATION — KOI-004 VSCode Child Process Emits Post Install Beacon Traffic
# purpose: validation
# dataset: xdr_data

preset = xdr_data
| filter _time > to_timestamp(current_time() - 1800)
| filter event_type = ENUM.NETWORK
| filter causality_actor_process_image_name in ("code", "node", "Code", "code-server") or actor_process_image_name in ("code", "node")
| filter dst_action_external_hostname contains "cortexsim-canary" or dst_action_external_hostname not contains "microsoft.com"
| fields _time, agent_hostname, causality_actor_process_image_name, causality_id, actor_process_image_name, actor_process_instance_id, dst_action_external_hostname, action_external_port

