# TTP-2026-0125 — Lateral Tool Transfer + Chisel Tunnel + PsExec Fan-Out (Muddled Libra Playbook) — First T1570 ABIOC (SIM-EDR-015)
# XQL paste-buffer generated by detection_scanner/scripts/export_artifacts.py

## ABIOC — Lateral Tool Transfer to Never-Before-Seen Tunneler over HTTPS (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Learned endpoint software/transfer baseline -> HTTPS downloader process (curl/certutil/powershell/s3browser) -> never-before-seen tunneler/remote-exec binary executed as its child, anchored to the downloading causality parent.
# An HTTPS downloader process (curl / certutil / powershell / s3browser) is the direct causality parent of a never-before-seen tunneler or remote-exec binary (chisel / psexec) written to disk and executed — the T1570 lateral-tool-transfer signal. Every tool is legitimate/dual-use, so a hash- or string-keyed BIOC is brittle; the ABIOC fires on the download -> first-seen-tool-execution deviation from the host's learned software baseline and anchors it to the downloader causality parent, not to any known-bad indicator. This is the corpus's first T1570 ABIOC.

dataset = xdr_data
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_name in ("chisel.exe", "chisel", "psexec.exe", "psexec")
| filter causality_actor_process_image_name in ("curl.exe", "curl", "certutil.exe", "powershell.exe", "s3browser-12-6-1.exe")
| comp count() as first_seen_tool_execs by agent_hostname, actor_effective_username, action_process_image_name
| filter first_seen_tool_execs >= 1
| sort desc first_seen_tool_execs
| fields agent_hostname, actor_effective_username, action_process_image_name, first_seen_tool_execs

## ABIOC — Anomalous Remote-Service Fan-Out from Newly-Written Tool (behavioral-ML, causality-anchored)
# severity: high
# behavioral_profile: machine-learning
# causality_anchor: Never-before-seen tool (from the lateral-tool-transfer ABIOC) -> fan-out of SMB/RDP/WinRM connections to multiple distinct internal peers exceeding the host's learned peer-connection diversity, anchored to the spawning tool.
# A newly-transferred tool (chisel / psexec) opens remote-service connections (SMB/445, RDP/3389, WinRM/5985) to two or more distinct internal peers within a short window — the PsExec/RDP fan-out stage. The ABIOC fires on the peer-diversity deviation from the host's learned peer-connection baseline (a workstation rarely initiates admin-protocol connections to several servers at once) and anchors it to the tool that spawned them, catching remote-service lateral movement that reuses legitimate protocols.

dataset = xdr_data
| filter event_type = ENUM.NETWORK and event_sub_type = ENUM.NETWORK_CONNECTION
| filter action_remote_port in (445, 3389, 5985)
| filter causality_actor_process_image_name in ("psexec.exe", "psexec", "chisel.exe", "chisel")
| comp count_distinct(action_remote_ip) as peer_targets by agent_hostname, actor_effective_username
| filter peer_targets >= 2
| sort desc peer_targets
| fields agent_hostname, actor_effective_username, peer_targets

## VALIDATION — Lateral Tool Transfer Lineage Observable in xdr_data
# purpose: validation
# dataset: xdr_data

dataset = xdr_data
| filter _time > to_timestamp(current_time() - 900)
| filter event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START
| filter action_process_image_name in ("chisel.exe", "chisel", "psexec.exe", "psexec")
| comp count() as tool_execs by agent_hostname, actor_effective_username, causality_actor_process_image_name
| filter tool_execs >= 1
| fields agent_hostname, actor_effective_username, causality_actor_process_image_name, tool_execs

## VALIDATION — Long-Lived TCP-443 Tunnel Session Observable in network_story
# purpose: validation
# dataset: network_story

dataset = network_story
| filter _time > to_timestamp(current_time() - 3600)
| filter dst_port = 443 and protocol = "tcp"
| comp sum(duration) as tunnel_seconds, count() as sessions by src_ip, dst_ip
| filter tunnel_seconds >= 900
| sort desc tunnel_seconds
| fields src_ip, dst_ip, sessions, tunnel_seconds

