#!/usr/bin/env python3
"""Build the GitHub wiki tree from the live scenario corpus.

Why this exists
---------------
The wiki is a *published artifact*, like the Pages site — it is built from
source, not stored. Two earlier attempts stored it instead, and both drifted:

  * ``docs/wiki/`` carried 16 hand-written pages describing a 53-scenario,
    13-plane tree that stopped being true in May 2026.
  * The live wiki carried 57 generated per-scenario pages from a one-shot
    script that was never re-run, frozen at 39 scenarios across 8 planes.

Meanwhile ``.github/workflows/wiki-sync.yml`` does ``git rm -rfq .`` before
copying, so turning it on with only the 16 hand-written pages present would
have deleted all 57 catalog pages. This generator makes ``docs/wiki/`` a
superset: hand-written narrative pages plus a catalog regenerated from the
corpus on every publish, so the destructive sync is safe and neither half can
drift from the YAML again.

Usage
-----
    python3 scripts/gen_wiki.py --out build/wiki      # build the tree
    python3 scripts/gen_wiki.py --check               # build to a temp dir, report counts

Reads the corpus through the REAL loader (``_parse_and_validate``), so a
scenario the engine rejects never reaches the wiki. That is deliberate: a
published page for a scenario that does not load is a claim the engine cannot
back.
"""

from __future__ import annotations

import argparse
import collections
import os
import shutil
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "core"))
os.environ.setdefault("CORTEXSIM_BASE_DIR", str(REPO))

from engine.scenario_loader import _find_yaml_files, _parse_and_validate  # noqa: E402

HAND_WRITTEN = REPO / "docs" / "wiki"
SCENARIOS = REPO / "scenarios"

#: Human-facing engine name per plane. Keys must match ``ScenarioSchema.plane``.
PLANE_ENGINE = {
    "EDR": "Cortex XDR Agent",
    "CDR": "Cortex Cloud / Prisma Cloud Compute",
    "NDR": "Network Security / Firewall Analytics",
    "ITDR": "Cortex ITDR",
    "CSPM": "Cortex Cloud Posture Management",
    "ASM": "Cortex Attack Surface Management",
    "TIM": "Cortex Threat Intel Management",
    "CLOUD_APP": "Cortex Cloud App Security",
    "ANALYTICS": "XSIAM Correlation Engine",
    "AI_ACCESS": "Cortex AI Access Security",
    "AIRS": "Cortex AI Runtime Security",
    "BROWSER": "Prisma Browser",
    "KOI": "Agentic endpoint / supply chain",
    "AI_SPM": "Cortex AI Security Posture Management",
    "EMAIL": "XSIAM / NG-SIEM (Proofpoint TAP + M365 ingestion)",
}

BANNER = (
    "<!-- GENERATED by scripts/gen_wiki.py from the scenario corpus. "
    "Do not edit in the GitHub wiki UI — edits are overwritten on the next "
    "merge to main. Change the scenario YAML instead. -->"
)


def attack_url(tid: str) -> str:
    """T1003.008 -> https://attack.mitre.org/techniques/T1003/008/"""
    if not tid:
        return ""
    return "https://attack.mitre.org/techniques/" + tid.replace(".", "/") + "/"


def tech_link(tid: str, name: str = "") -> str:
    if not tid:
        return "—"
    label = f"`{tid}`" + (f" {name}" if name else "")
    return f"[{label}]({attack_url(tid)})"


def fence(cmd: str, lang: str = "bash") -> str:
    """Fence a command, widening the fence if the body contains backticks."""
    body = (cmd or "").rstrip()
    ticks = "```"
    while ticks in body:
        ticks += "`"
    return f"{ticks}{lang}\n{body}\n{ticks}"


def esc(text: str | None) -> str:
    """Make a value safe inside a markdown table cell."""
    if text is None:
        return "—"
    return str(text).replace("|", "\\|").replace("\n", " ").strip() or "—"


# ───────────────────────────── page builders ─────────────────────────────


def scenario_page(s) -> str:
    out: list[str] = [BANNER, "", f"# {s.scenario_id} — {s.name}", ""]

    detection_types = " · ".join(f"`{d}`" for d in s.detection_types) or "—"
    modes = []
    if s.pull_supported:
        modes.append("pull")
    if s.push_supported:
        modes.append("push")

    rows = [
        # NB: the pipe inside a [[target|label]] wikilink must be escaped or it
        # terminates the surrounding markdown table cell.
        ("Plane", f"[[Plane-{s.plane}\\|{s.plane}]] — {PLANE_ENGINE.get(s.plane, '')}"),
        ("Status", f"`{s.status}`"),
        ("Version", f"`{s.version}`"),
        ("Detection types", detection_types),
        ("MITRE tactic", f"`{s.mitre_tactic}` {s.mitre_tactic_name}"),
        ("Primary technique", tech_link(s.mitre_technique, s.mitre_technique_name)),
    ]

    if s.additional_techniques:
        extra = ", ".join(
            tech_link(getattr(t, "technique", "") or "", getattr(t, "name", "") or "")
            for t in s.additional_techniques
        )
        rows.append(("Additional techniques", extra))

    rows += [
        ("Use case", f"`{s.uc_ref}` — {esc(s.uc_name)}"),
        ("Test case", f"`{s.tc_ref}` — {esc(s.tc_name)}"),
    ]
    if len(s.tc_refs) > 1:
        rows.append(("Evidence set", ", ".join(f"`{t}`" for t in s.tc_refs)))
    if s.pov_scenario_id:
        rows.append(("POV payload", f"`{s.pov_scenario_id}`"))

    rows.append(("Execution modes", " · ".join(modes) or "—"))
    ident = s.execution_identity
    idrow = f"default `{ident.default}`"
    others = [o for o in (ident.options or []) if o != ident.default]
    if others:
        idrow += " · options " + " ".join(f"`{o}`" for o in others)
    rows.append(("Execution identity", idrow))

    if s.methodology_family or s.validation_methodology:
        rows.append(
            ("Methodology", f"`{s.methodology_family or '—'}` {esc(s.validation_methodology)}")
        )
    if s.primary_kpi:
        rows.append(("Primary KPI", esc(s.primary_kpi)))
    if s.threshold is not None:
        t = s.threshold
        parts = [f"{k}: `{v}`" for k, v in t.model_dump().items() if v is not None]
        rows.append(("Threshold", ", ".join(parts) or "—"))
    if s.moat_tier:
        rows.append(("Moat tier", f"`{s.moat_tier}`"))
    if s.correlation_window_seconds:
        rows.append(("Correlation window", f"{s.correlation_window_seconds}s"))
    if s.stitching_key:
        rows.append(("Stitching key", f"`{s.stitching_key}`"))
    if s.required_planes_in_incident:
        rows.append(
            ("Planes required in incident", " · ".join(f"`{p}`" for p in s.required_planes_in_incident))
        )
    if s.cgo_anchor:
        cgo = s.cgo_anchor
        who = f"`{cgo.image_name}`"
        if getattr(cgo, "primary_username", None):
            who += f" as `{cgo.primary_username}`"
        rows.append(("Causality group owner", who))
    if s.threat_report:
        label = esc(s.threat_report)
        rows.append(
            ("Threat report", f"[{label}]({s.threat_report_url})" if s.threat_report_url else label)
        )
    if s.tags:
        rows.append(("Tags", " ".join(f"`{t}`" for t in s.tags)))

    out.append("| | |")
    out.append("|---|---|")
    out += [f"| **{k}** | {v} |" for k, v in rows]
    out.append("")

    if s.success_criteria:
        out += ["## Success criteria", "", s.success_criteria.strip(), ""]

    # ── steps ────────────────────────────────────────────────────────────
    out += [f"## Steps ({len(s.steps)})", ""]
    for i, st in enumerate(s.steps, 1):
        out.append(f"### {i}. {st.name}")
        out.append("")
        meta = [f"`id: {st.id}`", f"identity `{st.identity}`", tech_link(st.mitre_technique)]
        if st.platforms:
            meta.append("platforms " + " ".join(f"`{p}`" for p in st.platforms))
        if st.causality:
            pivot = getattr(st.causality, "pivot", None) or "process_lineage"
            meta.append(f"descends from `{st.causality.parent_step}` via `{pivot}`")
        out += [" · ".join(m for m in meta if m and m != "—"), "", fence(st.command), ""]

        if st.platform_variants:
            out.append("<details><summary>Per-OS variants</summary>")
            out.append("")
            for osk, cmd in sorted(st.platform_variants.items()):
                out += [f"**{osk}**", "", fence(cmd), ""]
            out += ["</details>", ""]

        if st.expected_detections:
            out += [
                "| Expected detection | Plane | Type | Card |",
                "|---|---|---|---|",
            ]
            for d in st.expected_detections:
                card = f"`{d.ttp_ref}`" if d.ttp_ref else "—"
                if d.detection_id:
                    card += f"<br/>`{d.detection_id}`"
                out.append(f"| {esc(d.description)} | `{d.plane}` | `{d.type}` | {card} |")
            out.append("")

    # ── tools / cleanup ──────────────────────────────────────────────────
    if s.external_tools:
        out += ["## External tools", "", "| Tool | Type | Adapter | Staged as |", "|---|---|---|---|"]
        for t in s.external_tools:
            out.append(
                f"| {esc(t.name)} | `{t.type}` | "
                f"{f'`{t.adapter_ref}`' if t.adapter_ref else '—'} | "
                f"{f'`{t.stage_as}`' if t.stage_as else '—'} |"
            )
        out.append("")

    if s.infra_modules_needed:
        out += [
            "## IaC modules",
            "",
            " ".join(f"`{m}`" for m in s.infra_modules_needed),
            "",
        ]

    if s.cleanup and s.cleanup.commands:
        out += ["## Cleanup", "", fence("\n".join(s.cleanup.commands)), ""]

    out += [
        "---",
        "",
        f"Source: `scenarios/{s.plane.lower()}/…` · "
        f"See [[Plane-{s.plane}]] · [[Scenario Index]] · [[Home]]",
        "",
    ]
    return "\n".join(out)


def plane_page(plane: str, items: list) -> str:
    engine = PLANE_ENGINE.get(plane, "—")
    steps = sum(len(s.steps) for s in items)
    dets = sum(len(st.expected_detections) for s in items for st in s.steps)
    tactics = sorted({f"`{s.mitre_tactic}` {s.mitre_tactic_name}" for s in items})
    dtypes = collections.Counter(d for s in items for d in s.detection_types)

    out = [
        BANNER,
        "",
        f"# {plane}",
        "",
        f"**Cortex engine:** {engine}",
        "",
        f"**{len(items)} scenarios · {steps} steps · {dets} expected detections**",
        "",
        "| Detection type | Scenarios |",
        "|---|---:|",
    ]
    out += [f"| `{k}` | {v} |" for k, v in dtypes.most_common()]
    out += ["", "**MITRE tactics exercised**", ""]
    out += [f"- {t}" for t in tactics]
    out += ["", "## Scenarios", "", "| ID | Name | Technique | Steps | Modes |", "|---|---|---|---:|---|"]

    for s in sorted(items, key=lambda x: x.scenario_id):
        modes = "".join(c for c, on in (("↓", s.pull_supported), ("↑", s.push_supported)) if on)
        out.append(
            f"| [[{s.scenario_id}]] | {esc(s.name)} | "
            f"{tech_link(s.mitre_technique)} | {len(s.steps)} | {modes or '—'} |"
        )
    out += ["", "`↓` pull (agent)  ·  `↑` push (bundle)", "", "---", "", "[[Scenario Index]] · [[Home]]", ""]
    return "\n".join(out)


def index_page(scen: list) -> str:
    by_plane = collections.Counter(s.plane for s in scen)
    out = [
        BANNER,
        "",
        "# Scenario Index",
        "",
        f"**{len(scen)} loadable scenarios across {len(by_plane)} detection planes.** Every row "
        "below parsed clean through the engine's own loader "
        "(`core/engine/scenario_loader.py`) at publish time — a scenario the engine "
        "rejects never reaches this page.",
        "",
        "| Plane | Engine | Scenarios |",
        "|---|---|---:|",
    ]
    for p, c in by_plane.most_common():
        out.append(f"| [[Plane-{p}\\|{p}]] | {PLANE_ENGINE.get(p, '—')} | {c} |")
    out += [f"| | **Total** | **{len(scen)}** |", "", "## All scenarios", ""]
    out += ["| ID | Plane | Name | Tactic | Technique |", "|---|---|---|---|---|"]
    for s in sorted(scen, key=lambda x: (x.plane, x.scenario_id)):
        out.append(
            f"| [[{s.scenario_id}]] | `{s.plane}` | {esc(s.name)} | "
            f"`{s.mitre_tactic}` {s.mitre_tactic_name} | {tech_link(s.mitre_technique)} |"
        )
    out += ["", "---", "", "[[ATT-CK-Coverage]] · [[Home]]", ""]
    return "\n".join(out)


def attack_page(scen: list) -> str:
    by_tactic: dict[str, dict[str, set]] = collections.defaultdict(lambda: collections.defaultdict(set))
    names: dict[str, str] = {}
    for s in scen:
        key = f"{s.mitre_tactic} {s.mitre_tactic_name}"
        by_tactic[key][s.mitre_technique].add(s.scenario_id)
        names[s.mitre_technique] = s.mitre_technique_name
        for t in s.additional_techniques:
            tid = getattr(t, "technique", "") or ""
            if tid:
                by_tactic[key][tid].add(s.scenario_id)
                names.setdefault(tid, getattr(t, "name", "") or "")

    total_tech = len({t for d in by_tactic.values() for t in d})
    out = [
        BANNER,
        "",
        "# ATT&CK Coverage",
        "",
        f"**{len(by_tactic)} tactics · {total_tech} distinct techniques** across "
        f"{len(scen)} scenarios, fusing each scenario's primary technique with its "
        "`additional_techniques[]`.",
        "",
    ]
    for tactic in sorted(by_tactic):
        techs = by_tactic[tactic]
        n = sum(len(v) for v in techs.values())
        out += [f"## {tactic}", "", f"{len(techs)} techniques · {n} scenario bindings", "",
                "| Technique | Scenarios |", "|---|---|"]
        for tid in sorted(techs):
            sims = " ".join(f"[[{x}]]" for x in sorted(techs[tid]))
            out.append(f"| {tech_link(tid, names.get(tid, ''))} | {sims} |")
        out.append("")
    out += ["---", "", "[[Scenario Index]] · [[Home]]", ""]
    return "\n".join(out)


# ─────────────────────────────── driver ───────────────────────────────


def build(out_dir: Path) -> dict:
    files = _find_yaml_files(str(SCENARIOS))
    scen, rejected = [], []
    for f in files:
        s, err = _parse_and_validate(f)
        (scen.append(s) if s else rejected.append((f, err)))

    out_dir.mkdir(parents=True, exist_ok=True)

    # 1. hand-written narrative pages (README.md is source-tree only)
    copied = 0
    for md in sorted(HAND_WRITTEN.glob("*.md")):
        if md.name == "README.md":
            continue
        shutil.copy2(md, out_dir / md.name)
        copied += 1

    # 2. generated catalog
    for s in scen:
        (out_dir / f"{s.scenario_id}.md").write_text(scenario_page(s), encoding="utf-8")

    by_plane: dict[str, list] = collections.defaultdict(list)
    for s in scen:
        by_plane[s.plane].append(s)
    for plane, items in by_plane.items():
        (out_dir / f"Plane-{plane}.md").write_text(plane_page(plane, items), encoding="utf-8")

    (out_dir / "Scenario-Index.md").write_text(index_page(scen), encoding="utf-8")
    (out_dir / "ATT-CK-Coverage.md").write_text(attack_page(scen), encoding="utf-8")

    return {
        "discovered": len(files),
        "scenarios": len(scen),
        "rejected": rejected,
        "planes": len(by_plane),
        "hand_written": copied,
        "pages": len(list(out_dir.glob("*.md"))),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="build/wiki", help="output directory (default: build/wiki)")
    ap.add_argument("--check", action="store_true", help="build to a temp dir and report only")
    args = ap.parse_args()

    if args.check:
        with tempfile.TemporaryDirectory() as td:
            r = build(Path(td))
    else:
        out = Path(args.out)
        if out.exists():
            shutil.rmtree(out)
        r = build(out)

    print(
        f"wiki: {r['pages']} pages "
        f"({r['hand_written']} hand-written + {r['scenarios']} scenario "
        f"+ {r['planes']} plane + 2 index) "
        f"from {r['discovered']} discovered YAML"
    )
    if r["rejected"]:
        print(f"\n{len(r['rejected'])} scenario(s) rejected by the loader and EXCLUDED:")
        for f, err in r["rejected"]:
            head = str(err).replace("\n", " ")[:100]
            print(f"  - {Path(f).name}: {head}")
        print("\nThese are excluded on purpose — publishing a page for a scenario the")
        print("engine will not load is a claim the engine cannot back.")
    if not args.check:
        print(f"\nwrote {args.out}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
