# TTP-2026-0081 — XDM Container Telemetry Normalization — Modeling-Rule Substrate Proof (T1610 / T1613)
# XDM modeling-rule paste-buffer (normalization substrate) generated by detection_scanner/scripts/export_artifacts.py

## MODELING RULE — Container Telemetry XDM Normalization (XDM normalization substrate)
# raw source dataset: cortexsim_container_raw
# vendor/product: PANW / Cortex XSIAM
# XDM fields populated: xdm.target.container.pod_namespace, xdm.target.container.pod_name, xdm.target.container.image_name, xdm.target.container.id, xdm.target.container.privileged
# Maps the raw actor_container_info JSON blob the Linux agent emits into addressable XDM container fields. Derived from the xsiam-prisma-cdr-lab container_info.sql. This is the normalization substrate beneath the privileged-container BIOC — it enables firing, it does not itself fire.

[MODEL: dataset = cortexsim_container_raw]
| fields actor_container_info as container_info
| filter container_info != null
| alter pod_namespace = json_extract_scalar(container_info, "$.pod_namespace")
| alter pod_name = json_extract_scalar(container_info, "$.pod_name")
| alter image_name = json_extract_scalar(container_info, "$.image_name")
| alter image_id = json_extract_scalar(container_info, "$.image_id")
| alter container_id = json_extract_scalar(container_info, "$.id")
| alter privileged = json_extract_scalar(container_info, "$.privileged")

